### ISSUE TITLE
Runescape UF Font error during build

### ISSUE THREAD

**Issue by DanoThom** [CompletelyFairGames/dwarfcorp#1]
Building the DwarfCorpXNA project requires the Runescape UF font to be installed on the users OS.

If you add the font to the build somewhere I guess you could either script the font install or enhance the build instructions in the repo.

**Comment by mklingen** [comment]
Oops, I forgot to remove this from the repository. It should not need it.

**Comment by mklingen** [comment]
Fixed by the latest commit.
