### ISSUE TITLE
Trade quantity

### ISSUE THREAD

**Issue by alphapriest** [CompletelyFairGames/dwarfcorp#1033]
When i trade goods for good or goods for dwarf bucks often it will not give me the agread upon quantity.  Example being i was going to trade the motherland gems and refined mana for gold.  I went to trade for there 30 gold and some dwarf bucks.  When I hit trade the game only gave me 2 gold and took all my refined mana and gems.  It is not exclusive to my current save file as i have started over many times tiring to fix it.

**Comment by Blecki** [comment]
Would it be possible for you to get a screenshot of the trade screen, with your proposed trade? I want to make sure I am setting up the trade the same way so I can see what is going wrong.

**Comment by alphapriest** [comment]
So with this example I am trading 6 gold, to the mole-men, for 13 amethyst.  Just so you know I ctrl clicked the amethyst don't now if that is important, it has also done it with shift click.  I don't know think I have tried single click though.  I currently have 1 amethyst.  You can see this in the first screen shot.  
![20190315194919_1](https://user-images.githubusercontent.com/48602846/54467630-c342a980-475c-11e9-9806-64cd8fccd41c.jpg)


The second screen shot shows that I was given only 7 in the trade making my total 8 Amethyst.  Their items show that all 13 were traded however.

![20190315194948_1](https://user-images.githubusercontent.com/48602846/54467633-c76ec700-475c-11e9-99da-6bbbaaf5b86a.jpg)

**Comment by Blecki** [comment]
Are you on the latest update?

If so, are you able to share your save?

**Comment by alphapriest** [comment]
I would be glad to but, I am not sure how to.  I saw a page that gave the instructions earlier on how to share a save but, i cant find it now.  Can you link it or give instructions on how to share my save?

**Comment by Blecki** [comment]
https://steamcommunity.com/app/252390/discussions/0/1742220359684341260/

**Comment by alphapriest** [comment]
Here are the files you requested.

[DwarfCorp Save File Alphapriest.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2973767/DwarfCorp.Save.File.Alphapriest.zip)

**Comment by mklingen** [comment]
Just opened up your save and confirmed that something very very wrong is happening with either shift click or control click and trade. Working on a solution.

**Comment by mklingen** [comment]
Issue located. This is a logic bug. When there is a stockpile that is almost (but not quite) full, adding resources to the stockpile adds what can fit and throws away the remainder. Working on a fix.

**Comment by mklingen** [comment]
Fixed in master. Fix will be in the next release. Thanks for the report!

**Comment by alphapriest** [comment]
Thank you for taking the time to fix it.  I have enjoyed the game and I am ready to play some more.
