### ISSUE TITLE
Quit confirmation & menu button order

### ISSUE THREAD

**Issue by bcmpinc** [CompletelyFairGames/dwarfcorp#1037]
I had pressed 'escape' to pause the game and bring up the in game menu. I wanted to continue playing, so I pressed the top button. However, unlike most games, the continue button was the bottom most button, the top button is 'quit'. That wouldn't have been an issue if the game noticed that I hadn't saved in a while and asked for confirmation. It didn't however so I lost several minutes of progress.

Can you please add a confirmation dialog for quit? And can you maybe reorder the menu buttons to be more in line with the order that other games use?

**Comment by Blecki** [comment]
These are good ideas and have been implemented. They'll be in the unstable branch this weekend and the main branch in the next major release.
