### ISSUE TITLE
Linux launch problems

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#133]
Currently the executable distributed for 64/32 bit linux doesn't have the right permissions to run. Need to figure out how to set the permissions in the build system. Otherwise the user has to set permissions manually using chmod (might be related to #5 )

**Comment by mklingen** [comment]
https://github.com/FNA-XNA/FNA/wiki/3:-Distributing-FNA-Games
 
Can probably distribute an installer with the game for linux easily to make this happen. On Mac it might be another story.

**Comment by mappu** [comment]
If you use a .tar.gz file instead of a .zip, the +x permission will be preserved.

**Comment by com1clyf3** [comment]
@mklingen Close?
