### ISSUE TITLE
Sound and music initialized too late.

### ISSUE THREAD

**Issue by Solsund** [CompletelyFairGames/dwarfcorp#14]
Initializing the SoundManager class currently doesn't happen until inside PlayState which stops sounds from being used until the game has entered into that state.  This stops the ability to have music at the main menu or any sort of GUI button click sounds before fully loading a world.

A new location is needed for this initialization.

**Comment by mklingen** [comment]
Good idea. It should probably be initialized statically.

**Comment by mklingen** [comment]
Fixed.
