### ISSUE TITLE
Documentation Request: Add Build Instructions For Linux

### ISSUE THREAD

**Issue by naclander** [CompletelyFairGames/dwarfcorp#140]
First off, thanks for the efforts so far, this game looks great.

I was wondering if you can add instructions to the README on how to build this on Linux, starting from
 `git clone https://github.com/CompletelyFairGames/dwarfcorp`, and listing out which dependencies are needed to perform a Linux build.

**Comment by mklingen** [comment]
The game is built in [XNA/FNA.](https://github.com/FNA-XNA/FNA), where the build environment is Visual Studio on a Windows machine, using .NET and XNA binaries. The build then gets cross-compiled to Linux/Mac from within Windows. It may be possible to get the FNA project building directly in Linux (minus the content pipeline) but I have not tried it. In that case the content would still have to be processed on windows (and converted to .xnb) and the resulting binaries would have to be loaded for windows.

**Comment by naclander** [comment]
So from reading the various documentation, it looks like it is not possible, or very difficult, to build this under Linux, just with the source code provided in this repository. That's unfortunate. Feel free to close this issue.
