### ISSUE TITLE
64 bit Linux: $ARCH not guaranteed to be set

### ISSUE THREAD

**Issue by naclander** [CompletelyFairGames/dwarfcorp#143]
Running on Arch Linux, the $ARCH environment variable is not set. This causes `DwarfCorp.sh` to look for `DwarfCorpFNA.bin.x86` instead of `DwarfCorpFNA.bin.x86_64`, but DwarfCorpFNA.bin.x86_64 does not exist. 

I only see a Linux 64 bit build on dwardcorp website. Should `DwarfCorpFNA.bin.x86` even exist at all?

**Comment by mklingen** [comment]
There are 64 and 32 bit binaries on the releases page

**Comment by naclander** [comment]
> There are 64 and 32 bit binaries on the releases page

I'm only able to find a [link](https://github.com/CompletelyFairGames/dwarfcorp/releases/download/v17.04.08/Linux32.zip) to what appears to be the 64 bit Linux binary located on [this page](http://www.dwarfcorp.com/site/download/). However the file downloaded is called Linux32.zip?

Am I missing something? Can you post the links for the Linux 32 bit build,and the 64 bit build?

> What's the best way to look for the architecture in Arch linux?

I'm not sure what the _best_ way that would work across all distributions is. You could try 
``` basg
uname -a | grep -q 86_64
```
Or you could just add to the README that this is only supported for Ubuntu. Or you could add to the README that the user should populate $ARCH with the correct variables for the OS.

**Comment by mklingen** [comment]
Sorry, the website hasn't been updated. @naclander here is the [releases page](https://github.com/CompletelyFairGames/dwarfcorp/releases).

Specifically the latest 64 bit release is [here](https://github.com/CompletelyFairGames/dwarfcorp/releases/download/v17.05.15/DwarfCorpLinux64.zip)

Thank you for the suggestion, I will edit the script and add some information to the readme.
