### ISSUE TITLE
Dwarves are not very smart about digging downwards.

### ISSUE THREAD

**Issue by Solsund** [CompletelyFairGames/dwarfcorp#17]
Trying to craft a little 3-block wide zig-zag staircase into a cliff has shown that dwarves will jump off of blocks above a block that is marked and try to mine it on their way past.  Sometimes this will oddly work even if the block is two above them and one over.  Other times they will just fall right past it and will either enter a semi-inifinite loop of walking back up above and jumping down or they will just lock into place under the tile and refuse to do any more work.

They appear to think they are actually mining the block despite failing the call to strike it.

They can also try to do this same thing by stepping off a block to the side before they fall.  I had all three miner dwarves lock up this way despite me choosing the perfectly reachable block just to the right of it as well.

**Comment by mklingen** [comment]
This is the same issue as #15 . I put some comments there. It would be helpful to include screenshots.
