### ISSUE TITLE
Reduce size of save files

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#171]
Specifically, the component files, which uncompressed are megabytes large.

**Comment by mklingen** [comment]
This is getting much better.  Still need to not serialize the following:

- [ ] Resource entities
- [ ] Bobber
- [ ] Box
- [ ] LightEmitter
- [ ] Mesh
- [ ] SelectionCircle

**Comment by com1clyf3** [comment]
@mklingen  Close?

**Comment by Blecki** [comment]
All of the low-hanging fruit has been squashed.  There are still some opportunities but the save files are pretty lean compared to what they were.
