### ISSUE TITLE
World terrain "clamps" past edges when starting near the edge/corner of a world

### ISSUE THREAD

**Issue by ccajas** [CompletelyFairGames/dwarfcorp#176]

**Comment by mklingen** [comment]
Nice catch. You can figure out why this is the case by looking at the voxel generation code here:
https://github.com/CompletelyFairGames/dwarfcorp/blob/master/DwarfCorp/DwarfCorpXNA/Voxels/ChunkGenerator.cs#L272

You see that it clamps to the boundaries of the "overworld", which gets generated before the game starts. I attempt to prevent the world from overstepping the bounds of the overworld in the generator screen, right here:

https://github.com/CompletelyFairGames/dwarfcorp/blob/master/DwarfCorp/DwarfCorpXNA/GameStates/WorldGeneration/WorldGeneratorPreview.cs#L156


But maybe that isn't working correctly?

**Comment by ccajas** [comment]
Could be fixable by increasing WorldScale to 3.0 here:
https://github.com/CompletelyFairGames/dwarfcorp/blob/master/DwarfCorp/DwarfCorpXNA/GameStates/WorldGeneration/WorldGenerationSettings.cs

It also increases the size of the square which more accurately covers the area to be loaded.

**Comment by mklingen** [comment]
I don't follow. `WorldScale` is the mapping from pixels in the overworld to voxels in the game. How would changing it from 2.0 to 3.0 affect this?

**Comment by mklingen** [comment]
Facts I discovered
- `ColonySize` is in *chunks*
- `WorldScale` is in units of *voxels per pixel* (of the overworld)
- `WorldGeneratorPreview` is assuming `ColonySize` is in *voxels* (which is obviously incorrect).
- `ColonySize` is actually the *extents* of the generated scene in chunks, so a 4x4 world is actually going to be 8x8 chunks.
- `WorldGeneratorPreview` sometimes assumes that a 4x4 world has 4x4 chunks, other times its assuming 8x8.

These facts combined are creating this bug.

**Comment by ccajas** [comment]
Looks like the problem has gotten worse. If you pick a spawn point by the southern or eastern edge of a custom map, the game crashes during the loading screen.

`A first chance exception of type 'System.IndexOutOfRangeException' occurred in DwarfCorp.exe
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. 
The program '[820] DwarfCorp.exe' has exited with code -1 (0xffffffff).`

Error happens in VoxelHandle.cs.

Sometimes the Out Of Range exception happens in the the 'get' property of WaterCell (`get { return Chunk.Data.Water[Index]; }` and other times in 'IsExplored' (`get { return !GameSettings.Default.FogofWar || Chunk.Data.IsExplored[Index]; }`). The index is out of array bounds.

**Comment by mklingen** [comment]
Not sure how that could be related. Can you verify that (A) this happens every time, and (B) that it is indeed caused by spawning on the edge of the map?

**Comment by Blecki** [comment]
Crash fixed in master. Clamping not fixed.

**Comment by ccajas** [comment]
Fixed clamping issue. It should no longer be possible to pick a location that will result in the colony area crossing the world bounds.

As followed by @mklingen's comment on what the variables stand for:

- `WorldGenerationSettings.Width` and `WorldGenerationSettings.Height` are set to 512. This is the total width and height of the overworld map units, also the total number of pixels.
- `WorldScale` is 2, so 2 voxels per pixel. The world is 1024x1024 voxels in size.
- `ColonySize` is in chunks, as previously stated. Problem is, there is no way to convert chunks to voxels and therefore to overworld units because there is no reference to a `chunkSize`.

The solution was to multiply `ColonySize` by chunkSize and then divide by `WorldScale`. A world 8x8 chunks in size is 64x64 pixels of the map, or 128x128 voxels. Conversion to voxels happens in WorldManager-Loading.cs, with `globalOffset` as the location in voxels.

This produced two changes: 

- The yellow square depicting the colony area was inaccurate in size. The center location is correct, but the boundaries actually had to be made bigger.
- With voxel placement now accurate, there's no longer a need to round to chunk coordinates to "snap" the starting location to the edge of a chunk.

**Comment by mklingen** [comment]
Nice! Chunk size is in `VoxelConstants.cs`

**Comment by Blecki** [comment]
I moved it to a compile time variable because having it configurable at runtime prevented some simple optimization in the voxel handles.

**Comment by ccajas** [comment]
New commit pushed using VoxelConstants. Issue will be closed.
