### ISSUE TITLE
Resource Library not serialized

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#181]
This leads to some resources simply not existing on game load, causing crash. Remember that resources are dynamically generated at runtime and so need to be serialized.

**Comment by Blecki** [comment]
I wonder if the correct fix would be to recreate the resources on load. If they are always the same, why serialize them?

**Comment by mklingen** [comment]
In my branch I now save the resource library. They must be serialized because some resources (like "Bird Egg", or "So and so's Corpse" get generated procedurally during gameplay.
