### ISSUE TITLE
Problems related to loading Large or Huge size colony maps

### ISSUE THREAD

**Issue by ccajas** [CompletelyFairGames/dwarfcorp#196]
Loading a Large or Huge colony from the world preview screen creates two problems:

1. Loading screen freezes for a longer time at the point of chunk generation (it no longer tells you how many chunks are done in real time). This would hurt user experience, as the game becomes unresponsive during this time.

2. Sometimes the game crashes after loading the map with an Out Of Memory exception. It runs out of memory trying to allocate space for RenderTarget2D lightmaps, in GeometricPrimitive.cs. A large colony map will obviously use more/larger lightmaps.

**Comment by mklingen** [comment]
We should either abandon the use of large/huge maps or do a push to make them viable. For the lightmaps, we should maybe disable lightmaps once there are too many of them. For loading I can bring some of the stuff I moved out of the loading thread back in.

**Comment by Blecki** [comment]
What value are lightmaps adding? With our voxel world, vertex lighting is pretty good.

What we should consider:
1. Do we need them at all?
2. Can we unload them for distant or out of view chunks?
3. Can they be compacted or shared?

**Comment by mklingen** [comment]
The lightmaps just make lighting happen per texel rather than per fragment. They don't add much, tbh. They can be removed altogether or kept around as an advanced graphics option for people with particularly beefy graphics cards.
