### ISSUE TITLE
New feature: native towns and other landmarks

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#197]
- [ ] Find a procedural way of generating towns 
- [ ] Generate roads
- [ ] Name natural landmarks in the world
- [ ] Add lost temples, dungeons or other such procedural goodies

**Comment by com1clyf3** [comment]
@mklingen Still interested in doing this?

**Comment by com1clyf3** [comment]
Officially out of scope. Closing for regression.
