### ISSUE TITLE
On Mac, full-screening the game doesn't turn off the application bar (unless it gets auto-hidden)

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#216]
Not sure why, but when the game is in fullscreen on a Mac, the main OSX menu bar shows up on top of the game. There is probably some manifest setting I have to fix or something.

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/37611872-eff44592-2b79-11e8-9c06-0b408371612f.png)
