### ISSUE TITLE
Crash resuming crashed game

### ISSUE THREAD

**Issue by Vorgon1** [CompletelyFairGames/dwarfcorp#219]
Game crashes a lot, expected though getting close to steam release, lots of crashes is not good. After a few times, the game reaches a point where selecting resume just crashes the game again. I zipped up the saves folder which has 2 folders for the same game. I'm assuming one of them is the point where it keeps crashing: 
https://www.dropbox.com/s/qnttclxdyg1d7zf/Vorg-Saves.zip?dl=0

**Comment by mklingen** [comment]
Thank you.

Somewhere near that folder there should be a file called "log.txt". That might contain some useful information for us in figuring out why the game is crashing.

**Comment by Vorgon1** [comment]
The zip I put on dropbox includes the save folder tree with 2 save folders and 2 files, log.txt and settings.json

**Comment by Vorgon1** [comment]
There is an option for generating a "debug" map. Does that activate any debug info you are looking for?

**Comment by mklingen** [comment]
> There is an option for generating a "debug" map. Does that activate any debug info you are looking for?

no, that's okay. I'm going to activate crash reporting for the next build.

I loaded your save Rgorkland. It actually loaded for me without crashing (after I made a fake overworld in the `Worlds` directory), so I'm not sure what's going on. There were some other issues with that save I found like animal pens not getting registered on load. In general saving/loading is the least stable and untested part of the game.

**Comment by SamuelRowe** [comment]
I too have been crashing on 2 worlds when I load them. 
[SavedGames1.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1286445/SavedGames1.zip)
[SavedGames2.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1286448/SavedGames2.zip)

Happens on both XNA and FNA.

**Comment by mklingen** [comment]
Okay I will try them.

**Comment by Vorgon1** [comment]
>(after I made a fake overworld in the Worlds directory)
full maps are not saved with the game save or at least a copy in the save folder for a given game? Would that cause big problems if someone deletes the map in the worlds directory that is used in a saved game?

Also, could we at least have the option to keep all game related files in the game tree instead of dumping stuff in user tree? I like to keep my drives organized and programs in their own trees. I also keep most of my games on a different drive and save drive C: an, ssd drive for the os and programs that really need the speed. I don't want it cluttered up with game saves and other stuff for programs on other drives. Kerbal Space Program is a good example. Everything is in the ksp tree, so if you want to move it to another drive or even another computer you can and pick up where you left off without problems. All data, saves, mods, etc. are in the tree.

**Comment by Blecki** [comment]
Appdata is the standard location for these things on Windows.

**Comment by Vorgon1** [comment]
It what ms wants, not what I want. I want data on my computer kept together making it easier to maintain, clean out unused software, etc.. ms admitted that the biggest problem with windows 3x was the dumping of stuff in the 2 ini files and windows folders instead of keeping programs in their place. And their answer to the problem in win95? When it was released everyone said it was designed to self-distruct within 6 months to a year of use by not only having every program dump all there setting junk in.... 2 files now called the registry, but increasing the amount of data by an order of magnitude. They also want programs to dump crap in "program files". Tell a program where to install and you have crap dumped in program files or program filesx86, the registry, and that apdata tree. It's a mess. Go to unstall the program and all that other crap gets left clogging the computer, eating up disk space so the ms can sell you their next crappy version "so that your computer runs faster". It's not the new version that makes it faster, it's having to do a clean install, which under windows means re-installing everything instead of just copying over like it should be.

Just because ms says to do it, doesn't mean it's the right way to do it. And what do they know about standards? They are very big on proprietary to keep their monopoly.

Not mad at you, just hate when people say "its the way windows is setup" or something like that. There was another game, an mmo that started out as a zip dl. Un zip it where you want and it stayed there. But then the idiot decided to do an installer "the way it is supposed to be on windows". The installer put the launcher where you said, but then dumped EVERYTHING else in the user folder.  So much for keeping games on a different drive.

**Comment by mklingen** [comment]
Okay, I will look into that. At the moment, we need a directory that we're guaranteed to have permissions for. Right now, that's `AppData` on Windows. Will look into alternatives.

**Comment by mklingen** [comment]
Also, multiple `Saves` can be associated with one `World`. The `World` is the overworld (races, biomes, terrain, etc.) wheras the Save contains all the player's dwarves, rooms, etc.

**Comment by mklingen** [comment]
@SamuelRowe 

I managed to load your saves without crashing, but I did notice odd things about the saves such as dwarves standing around doing nothing due to having thousands of invalid queued up gather tasks. I will fix that particular issue. The next build will also have crash reporting, which should help track down some of these things.

**Comment by Vorgon1** [comment]
> we need a directory that we're guaranteed to have permissions for. 
You are not guaranteed to have access to game folder and sub folders in that folder? Example I am using D:\Games\DwarfCorp-windowsXNA. Seems you should have access to that folder and any sub folder there. People trying to put it in folders such as Program Files or other windows controlled folders should know better. :)

**Comment by SamuelRowe** [comment]
@mklingen I got visual studio and can debug if you want, too.

**Comment by Blecki** [comment]
Simple solution - default to appdata but make it configurable.

**Comment by mklingen** [comment]
> You are not guaranteed to have access to game folder and sub folders in that folder?

Not sure if I do when its distributed through Steam...

**Comment by Vorgon1** [comment]
I don't know where the default install is for steam, likely Program Files(x86) like everything else. The first install creates the Steam folder with all the steam stuff. along with the other sub folders, it creates steamapps which is where it puts anything you install on that drive. If you then select another folder or drive, it creates another steamapps folder there for installs at that location. So any install should always end up in a folder called steamapps. Maybe Steam could answer what if any permissions they set for folders and sub folders of things they install.

**Comment by Vorgon1** [comment]
Another crash save. This zip has 2 saves. The newer one crashes while loading entities. The older one does not. Also includes the map. I just zipped the whole dwarfcorp folder in apdata.
https://www.dropbox.com/s/uqtqeprh7xuqzfg/Vorg-DwarfCorp.zip?dl=0

**Comment by mklingen** [comment]
Okay, I fixed the issues related to this save and many others. In the next release, bugs during saving/loading will get shown on the screen which should help with bug reporting.

**Comment by mklingen** [comment]
possibly fixed.
