### ISSUE TITLE
Some tools need better feedback.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#221]
Need a dev spiral on some tools to make them clearer. 

Farming:
- [x] Tooltips while moving mouse during tilling and planting
- [x] Clearly mark which tiles are plantable
- [ ] Draw ghost plants in planting mode
- [ ] Sounds

Guarding:
- [x] Tooltips while dragging guard designations. (inform of how to cancel)
- [ ] Allow guarding of creatures as well as tiles.

Building:
- [x] Items to be built should be displayed as a blueprint while in build mode, rather than opaque work piles.
- [ ] Build designations should be able to be cancelled more easily with more feedback

Moving:
- [ ] Highlight objects when you mouse over them

Attacking:
- [x] Tooltips and confirmations

**Comment by plasticware** [comment]
another suggestion: when going up a level in the menu, revert the cursor to default instead of continuing to do the lower-level action. for example, [build->block->select stone->'esc' to go up a level] should not still build stone blocks, and neither should [build->block->select stone->'esc' to go up a level->objects (but don't select anything yet)].

**Comment by mklingen** [comment]
Yeah you're right about that. Will attach "go back to select tool" to all back buttons.

**Comment by mklingen** [comment]
Okay, pressing back goes back to the selection tool now.

**Comment by plasticware** [comment]
Clicking a button with submenus should also revert the cursor - for example, try selecting 'mine', then going into the build submenus without making a bottom-level selection - mine tool is still active.

**Comment by Blecki** [comment]
Going to disagree on this one (actually disagree with switching back to select on backing out a level) - current tool should remain active until another tool is chosen.

**Comment by mklingen** [comment]
Problem is that users can get stuck in a particular tool and don't know it. At least pressing "esc" should get you out of the tool.

**Comment by Blecki** [comment]
I want to do some kind of indicator for the current tool, especially as the existing indicator is broken and possibly incompatible with the way the menu is setup now.

**Comment by mklingen** [comment]
Could attach a small sub-tooltip to the cursor saying which tool is selected. It is already changing the cursor shape, but that could be confusing.

**Comment by mklingen** [comment]
Currently improving guarding behavior. Dwarves will guard entire regions and not just one block. Dwarves that have been told to guard will guard all areas.
