### ISSUE TITLE
Make context sensitive tools.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#222]
Generalize the selection tool so that right clicking sometimes opens a context menu for certain objects. For example, holding right click should bring up a context menu on a tree with options "go-to" and "chop down". Right clicking on a voxel and holding should open selection "mine" , "go-to" , "till soil" and "guard". Right clicking and holding on a farm tile should have "Plant x resource".  There are many others. 

This will require querying entity tags and using that to infer the appropriate actions.

**Comment by mklingen** [comment]
Blecki has made some progress on this. Will probably not be in for release.

**Comment by com1clyf3** [comment]
#627 most current version of this. Closing for dupe purposes.
