### ISSUE TITLE
Better Task Management

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#225]
Right now here is how task management works:

1. The player clicks on a dwarf or dwarfs.
2. The player selects an object/block in the world, triggering task assignment.
3. The tasks get immediately assigned to the selected dwarves.
4. Later the player can cancel tasks for *all* dwarves by right clicking on something.

It used to be a pool of tasks like other games in this genre. I think we should go back to this model, but still allow dwarf selection for inspecting the dwarf and giving him/her direct orders.

It should happen like this:

1. The player clicks an object or tool to assign a task.
2. The task goes into a task pool.
3. Dwarves pull tasks off the task pool according to their abilities.
4. Tasks can be cancelled, which just takes them off the task pool for all dwarves.
5. Maybe Dwarves can be disallowed from doing certain tasks altogether in a menu of some kind.

**Comment by Searthh** [comment]
I wanted to suggest exactly the same! Glad to see this here.
Some things to consider: 
- Sometimes you'll want your best craftdwarf to be crafting gold trinkets, so you have a better chance of making excellent or legendary trinkets.
- Some actions you want to be done by a specific dwarf - eg go somewhere, guard something, attack something.
- Some actions you want done urgently - the current system does a good job of making dwarves prioritize abiding to the latest whim of the player

These things can be solved by either

-having an intelligent pool system where dwarves will choose priority based on their distance to the task, their level (if it's crafting) and how recently that task was added to the pool, on top of the things it already considers.
- having  the pool work for building/placing/mining/farming/chopping only and dwarves still prioritizing recent tasks.

**Comment by mklingen** [comment]
Bumping this up in priority as likely the next big feature that will be implemented.

**Comment by mklingen** [comment]
This was implemented some time ago.
