### ISSUE TITLE
Text on retina screens difficult to read

### ISSUE THREAD

**Issue by ChainsawBaby** [CompletelyFairGames/dwarfcorp#229]
I find the text difficult to read on a 15" MacBook Pro 2016 with Retina display
Maybe it's some anti-aliasing on the text, or it could be a pixel or three bigger to make it more readable
https://i.bratteng.me/w7grMY8gWO.png

**Comment by Blecki** [comment]
It actually looks like the text is aliasing there - but it shouldn't be. What are your graphics settings?

Also, try the gui scale feature. Does that help?

**Comment by ChainsawBaby** [comment]
Yeah, you're right. It looks like text aliasing is there.
I set the game resolution to the max I can have, 3360x2100 and the text seems to be a little bit better to read. But a still bit small I think

**Comment by mklingen** [comment]
Okay, part of this is a technology issue (scaling the GUI even more), and part of it is an art issue (making the text more readable).

**Comment by mklingen** [comment]
Some thoughts from experimenting with this issue: there is definitely a screen-wide scaling issue in your screenshot. This seems to imply that something is going on with the resolution we're telling the game to be at vs. what it's actually getting rendered at. I'm wondering if there's a "feature" on Macs that does this, or if we're not correctly interpreting the screen resolution.

**Comment by BombBloke** [comment]
[This sounds very relevant](https://9to5mac.com/2016/12/02/15-inch-macbook-pro-screen-resolution-blurry/).
