### ISSUE TITLE
Revert settings after 10 seconds

### ISSUE THREAD

**Issue by ChainsawBaby** [CompletelyFairGames/dwarfcorp#230]
I think it would be nice to have a popup that asks you if the settings you changed are OK (especially for resolution changes).
I just did a resolution change, and the Apply button went out of the screen so I couldn't revert it

**Comment by Blecki** [comment]
That should not be possible. Is your os offering resolutions your hardware can't actually display?

Anyway I'll see if I can add this.

**Comment by ChainsawBaby** [comment]
I can choose 1024x640, 1280x800, 1440x900, 1680x1050, 1920x1200 in Control Panel, and the game offers me up to 3360x2100.

That might be because of Retina display, not sure actually.

The only time this issue occurs if I have the game as a window, and not full screen

**Comment by mklingen** [comment]
Okay, that's a good idea. We had issues with resolution selection on Mac before and made a patch for it, but I wonder if our solution was general enough.

**Comment by mklingen** [comment]
Fixed by this commit https://github.com/CompletelyFairGames/dwarfcorp/commit/a4c28390d01f798798c1d4e5f30de8b69dd2ec69 Will be in the release.

**Comment by ChainsawBaby** [comment]
Awesome!
