### ISSUE TITLE
No texture underneath blocks

### ISSUE THREAD

**Issue by ChainsawBaby** [CompletelyFairGames/dwarfcorp#232]
I can see through walls, or something like that, when I'm viewing from a lower or same height as a block. See image
https://i.bratteng.me/w7grMY8gWO.png

**Comment by mklingen** [comment]
Ooh nice catch. We actually don't draw the bottom of blocks to save GPU. We will need another pass at mesh generation to prevent this kind of thing.

**Comment by mklingen** [comment]
possible duplicate of #238 and #298

**Comment by Blecki** [comment]
I think this is working as intended. Block bottoms are culled. 

Shall I change that?

**Comment by com1clyf3** [comment]
Sounds like fixed! Closed for now.
