### ISSUE TITLE
Option list is out of frame

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#235]
On several resolution settings, the options menu is out of it's background frame.
This makes the "Apply" and "Close" buttons unreachable.
![dwarfcrop_keys_selection_out_of_frame](https://user-images.githubusercontent.com/3519989/30784965-ec8e3b88-a15e-11e7-9a10-d62f9510006c.PNG)

**Comment by Blecki** [comment]
Looks like you're also using the gui scale setting.

I suppose I shall have to add a scrollbar!

**Comment by Blecki** [comment]
Fixed. A couple things at play -

- It is now impossible to set GuiScale 'too high', so it cannot render the gui unusable.
- There is a scrollbar on the keys screen.
