### ISSUE TITLE
Dismiss button for some tutorials not working in some cases

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#236]
First case:
* start a new game
* immediately hit ESC
* The tutorial on "Time" pops up.
* The "Dismiss" button on the tutorial on "Time" does now work until the escape menu is closed.

Second case:
* "Hire new Employee"
* The "Hiring Dwarfs" tutorial pops up.
* The dismiss button for "Hiring Dwarfs" tutorial is not working and blocks selection of some applicants.
* The "Hire new Employee" window must be closed. Then the dismiss button works again.

**Comment by mklingen** [comment]
First case is caused by game being paused, so GUI is not updating. Second case is caused by there being two modal popups open at once but for some reason tutorial is drawing over the hire dwarfs window.

**Comment by Blecki** [comment]
First case, while maybe not ideal, is technically working as intended.

Second case is because the hire popup is what triggers the tutorial. The tutorial should be on top and interactive in this case.

**Comment by mklingen** [comment]
Okay, so let's figure out why the tutorial is not interactive in these cases

**Comment by Blecki** [comment]
Both problems fixed.

**Comment by Blecki** [comment]
Fix is applied to HIRE TUTORIAL ONLY. I couldn't identify any others; but if there is a similar tutorial that should be opened over a modal dialog, it needs to be identified and flagged.
