### ISSUE TITLE
Saving/Loading needs a serious dev spiral

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#239]
We've been putting off fixing the save system for a while now, and it just needs to be done. Here are some things which will make our lives easier:

- [ ] Write an integration test that creates a world, saves it, and then loads it again while making some asserts. The test should create every possible entity in the entity factory, and every room.

- [ ] Force all objects to have paramaterless constructors. Do an audit to make sure this is true of everything.

- [ ] Force all objects to implement `OnDeserialized` and use it correctly. Maybe this could be accomplished by forcing everything to extend from an abstract interface.

- [ ] Start keeping track of save versioning.

**Comment by Blecki** [comment]
Save versioning is going to be impossible in the current system. My proposed design solves it, however.

**Comment by com1clyf3** [comment]
@mklingen  Close?

**Comment by mklingen** [comment]
We never made much progress on this.
