### ISSUE TITLE
Empty save token crash

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#242]
Deleting all saves from the "load game" option (there have to be saves to begin with) results in there being an empty save token with "no image" and red background which, if deleted, crashes the game.

![dc save token](https://user-images.githubusercontent.com/22550054/30894454-af4cb9e8-a2f8-11e7-9374-aabcf2105398.PNG)

Edit: sorry for weirdness with this issue; I opened it, couldn't repeat the issue, and then replicated it properly.

**Comment by Blecki** [comment]
Fixed and in master for next update.
