### ISSUE TITLE
DwarfCorp has problems with localization.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#243]
We've logged several crashes related to float parsing on Russian, German and Dutch machines. We need to be careful to set the locale to `US_EN` in our parsers to avoid these crashes while loading settings files, logs and saves.

This will require enforcing `en-US` as a culture game-wide and especially in the JSON serializers/deserializers. This will also mean forcing the game displays of money, decimals, dates, etc. to conform to `en-US` localization.

**Comment by Blecki** [comment]
Research indicates that Newtonsoft.Json defaults to InvariantCulture and we do not appear to be changing it.

That seems contrary to what we're observing, however, so I suspect that it is using the culture of the current thread instead - forcing InvariantCulture at game start may work.

**Comment by mklingen** [comment]
There are some places where we parse floats from strings directly. That's where its crashing mostly.

**Comment by mklingen** [comment]
Possibly fixed.

**Comment by kbauer** [comment]
With the update received via Steam today, loading a save-game on a German locale works.
