### ISSUE TITLE
Cannot abort task successfully

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#244]
You can delete tasks, but if you've gone to the task and begun selecting, but decide to abort (escape), it still creates the region for that task as if it had been selected, but then doesn't assign it a task. The next time you go to assign a task, the region selected will be designated to the new task as soon as your mouse hovers over the world when leaving the menu.

1. Initiate a task (any)
2. Select the region for that task, but hit escape before releasing the mouse button.
3. Observe red-outlined region.
4. Initiate another of the same task (or mining).
5. Old red region will be assigned to the task as soon as your mouse moves from the menu to the world.

**Comment by mklingen** [comment]
This is fixed now. Will be in the next build.
