### ISSUE TITLE
Always rectangular selection

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#245]
Every time you click on the world for any reason, instead of point-clicking, it always uses the rectangular selector (like for dragging) instead of allowing you to click a single spot. This is extremely annoying if I've paused and two dwarves are right next to each other and I want to select my miner and not my crafter.

**Comment by mklingen** [comment]
Need more information. Clicking once will create a rectangle of size 1, which is selecting a point?

**Comment by Orangicus** [comment]
In my game, it's never a single width. It's usually at least two-wide (but flat). I can screencap when I'm not working.

Essentially, it never creates a point-like selection area (small enough for me to consider a 'point'). It's always much larger than a single point (but smaller than an in-game block).

**Comment by mklingen** [comment]
Will need a screenshot to clarify.

**Comment by Orangicus** [comment]
GIF:
![dcmouseselect](https://user-images.githubusercontent.com/22550054/30936040-6d2633c0-a387-11e7-94a7-ece6f80d1ff3.gif)

Seems to snap to some sort of grid.
This is Windows 10 64-bit on an iMac with Bootcamp

**Comment by mklingen** [comment]
fixed by https://github.com/CompletelyFairGames/dwarfcorp/commit/ea2dc3ab9b58210f464fda366c554f179f7cc0a2
