### ISSUE TITLE
Settings Load Location

### ISSUE THREAD

**Issue by LunaMoonborn** [CompletelyFairGames/dwarfcorp#247]
**The game does not load settings from settings.json in Steam\SteamApps\common\DwarfCorp; it instead loads from %userprofile%\AppData\Roaming\DwarfCorp.**

I found this as I set the game to 4K, while the window was fit perfectly on screen, the game extended beyond the boundaries of the window. As seen here:
<img width="1459" alt="aa866cadbe96ed565383ef8e667a22c2" src="https://user-images.githubusercontent.com/32338454/30926964-c9d9586e-a3ae-11e7-89ae-03eec409393b.png">

I had to use ProcMon to find where the settings file was being loaded from so I could either reduce the resolution or set the game to full screen.

**Comment by mklingen** [comment]
Hey quick question: what platform are you running on? Also, when you select a setting, does the game create a prompt that says "settings will revert after 10 seconds..." ? If not, we messed up badly and an old version of the game is still on steam.

**Comment by Blecki** [comment]
Press f10 at the main menu and look for the version id. It's only displayed in the Windows version, unfortunately.

**Comment by LunaMoonborn** [comment]
@mklingen Windows 7 Pro x64 - It does prompt to revert, but that was off screen.

**Comment by mklingen** [comment]
So it did prompt to revert? If you just let it sit there for 10 seconds it will go back to the way it was before. Sorry about that.

**Comment by mklingen** [comment]
possibly fixed
