### ISSUE TITLE
Game Pauses Upon Auto-Save

### ISSUE THREAD

**Issue by BombBloke** [CompletelyFairGames/dwarfcorp#248]
I don't know whether it's *intended* to pause or not, but the UI still indicates that time should be running. However, time stands still until I both *manually pause* and then *unpause* - either I should be able to unpause directly, or a pause shouldn't occur in the first place.

**Comment by mklingen** [comment]
should be fixed by this https://github.com/CompletelyFairGames/dwarfcorp/commit/4d25be6c75dfb3fa809b2d57b8256eb410c657ff
