### ISSUE TITLE
Craftsdwarf glitch issue??

### ISSUE THREAD

**Issue by mikkjr** [CompletelyFairGames/dwarfcorp#255]
I've noticed that most of the glitches I've been encountering come from the craftsdwarf. For example, I was using him and then when the game autosaved, I was stuck in his build-mode, and it wouldn't let me place anything. If I remember correctly I got out of it by using G and using the delete option and got the cursor back. 

An issue I just ran into is when I hired a bunch of new dwarves, I couldn't select any of them. I saved and quit, and when I came back I couldn't select any of my dwarves. I think this came from the craftsdwarf as well because it would let me choose if I wanted to build something, but if I selected it I wouldn't be able to place it and the object I clicked to place would just follow my mouse around. I took a gyazo of it happening here: https://gyazo.com/e20c0e7dc3fa4eaf56031d1ae56fabfc

I've tried closing the game and reopening it, but it looks like the save keeps it glitched - if I go back to the old save before the glitch happened, the game works. I've also tried using the G menu to get my mouse back but I still have the bed following my cursor around. 
#

**Comment by BombBloke** [comment]
Does Esc resolve this? It should let you back out of most anything.

**Comment by mklingen** [comment]
My guess is that this is an issue with serialization (saving), and tasks. Unrelated to hiring new dwarfs or the craftsdwarf.

**Comment by mklingen** [comment]
As for the build tool being selected, pushing ESC should resolve that, but you shouldn't be stuck in that state in the first place.

**Comment by Orangicus** [comment]
You can also use number navigation to back out of menus.
> 1 > 1 
and you're back to the top menu.

**Comment by mklingen** [comment]
fixed by https://github.com/CompletelyFairGames/dwarfcorp/commit/065444fd7ceae05bbbf05a771d9e320aee6f2394
