### ISSUE TITLE
Money input in trade screen is whack

### ISSUE THREAD

**Issue by Blecki** [CompletelyFairGames/dwarfcorp#256]
I know what I was trying to achieve, but in practice it's super annoying. Just let the user type and treat blanks as 0.

**Comment by laserlight** [comment]
One question about the money input fields on the trade screen. Could you add support to use keyboard up and down arrows for adjusting the dollar amount?

I find it tedious at times to keep clicking the little arrows with my mouse while trying to read the profit difference on my monitor. Sometimes my hand/mouse drifts from the click area. I know this probably needs to be created as an additional issue.

**Comment by com1clyf3** [comment]
Fixed in #579. Closing.
