### ISSUE TITLE
Camera rotation causes endless spin

### ISSUE THREAD

**Issue by AsavarTzeth** [CompletelyFairGames/dwarfcorp#258]
Using either left shift or pressing the mouse wheel results in the camera spinning out of control, faster and faster.

The direction of the spin varies depending on where the mouse pointer is located. If I put it on the side from the center it spins in that direction (clockwise), if I put it on the right it does the reverse.

I made a funny observation. If I lift the mouse so that there is basically no mouse input and press left shift or the mouse wheel there is no issue. Further, if I then slowly return the mouse to the mouse pad everything works as expected and I can rotate and turn without losing control.

Might it be sensitivity issue, perhaps even an issue with high dpi mouses?

Oh and I am running this under Linux (Arch Linux) and Gnome Shell 3.24 and it is under Xorg, not Wayland since I use a Nvidia GPU. More details can be found on my [Steam profile page](https://steamcommunity.com/id/asavartzeth).

**Comment by mklingen** [comment]
Known bug, found in #198 , specific to linux. Will be fixed in the next build as it requires an update of SDL libraries for linux.

**Comment by mklingen** [comment]
Was fixed by this build of FNA, which includes new binaries for SDL.

https://github.com/FNA-XNA/FNA/issues/127

Will update the build when able.

**Comment by mklingen** [comment]
This is fixed now. Build will be out tomorrow.

**Comment by mklingen** [comment]
I have heard that this is still broken. Will test and see if I can fix. Possible I did not update to the new SDL libs properly.

**Comment by mklingen** [comment]
I believe this is now fixed, but I have not tested on linux.

**Comment by AsavarTzeth** [comment]
I will make sure to test it for you later when I get home. If it works I will close this.

**Comment by AsavarTzeth** [comment]
It does indeed work now.

**Comment by mklingen** [comment]
Great!
