### ISSUE TITLE
Stockpile full crash

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#263]
Dwarf (same one from "get paid" glitch #259 so I'm not sure if it's related or not) is transporting a bunch of items and gold to a new stockpile. Stockpile becomes full as he's doing that.
Bam.
Crash as soon as all the items hit the stockpile, but I know he has more because I know what he picked up at the time.

**Comment by mklingen** [comment]
Cant' seem to reproduce. I believe you that it crashed but it might be something I fixed already or it could be totally unrelated to stockpiles being full.
