### ISSUE TITLE
"Follow" command weirdness

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#270]
Following is great, and:
1. You can control any dwarf you are following with the WASD key configuration for movement (no jumping, though.
2. Controlling a dwarf with the WASD keys cancels any active tasks and gives them the task "look interesting" when you stop controlling them. Sucks if they were doing something important like collecting items.

**Comment by mklingen** [comment]
You should definitely be able to jump. Cancelling tasks is intentional.

**Comment by Orangicus** [comment]
Closed because not an issue.
