### ISSUE TITLE
[SUG] Dwarf controls

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#271]
I like that you can control the dwarf, but would it be possible to expand the capabilities to include full control of a dwarf for things like jumping, combat, or other tasks, like mining?

Like, I might set all of my available dwarves to do a task, and I'll have nothing to do but watch them. So I might as well mine a bit, or hunt down some spiders because why not?

**Comment by com1clyf3** [comment]
Closing for regression, but labeled so it can be examined for reference.
