### ISSUE TITLE
[SUG] Edit tool is not in the correct menu (potentially)

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#276]
Very straight-forward.
The (compass) edit tool only effects objects (afaik), so it should only be in the "object" menu.
Having it in the "build" menu with every other type of construction (most of which aren't effected by the edit tool) is confusing unless the intention is to later make the edit tool cover all those bases (instead of having to select each item type to delete it).

![asdasdads](https://user-images.githubusercontent.com/22550054/30983489-6ff03746-a43f-11e7-9314-49c403d265fb.PNG)

![dfsdfsdfsd](https://user-images.githubusercontent.com/22550054/30983494-72789616-a43f-11e7-84ee-21e6fb405da3.PNG)

**Comment by com1clyf3** [comment]
Noted in design prospectus. Closing for regression.
