### ISSUE TITLE
The Perspective Camera

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#279]
It behaves in an annoying way; namely, it relies on actual blocks to be below it (which I think causes a couple other issues).

Firstly, instead of "floating" as would be normal. It seems to function as "I am [number] of blocks above [specific block]," which results in things like having to navigate around terrain when moving around the map, which just should not be an issue, really.

Secondly, it creates glitches when zooming out. Maybe I want to take in a view of the whole map to get an idea of what I have to work with without deferring to the minimap feature. Maybe I'm trying to mass chop some wood. Or Mass wrangle some critters. I'm not sure. But I know when I zoom out, it triggers a glitch where the perspective gets stuck against the "wall" (as it cannot travel over the ground without blocks below it).

This creates a 'Box" kind of feel, where not even the perspective camera can go outside of the terrain limits, meaning that I can look at the map from the actual outside. I realize this might be due to correct programming limitations within the core game itself and may be expanded later, but I also wanted to reference it for the sake of thoroughly explaining the issue.

**Comment by mklingen** [comment]
All working as intended. The camera automatically floats above the terrain, and is also constrained to the world bounds. this is all intentional and not a bug. This is to prevent you from constantly having to back the camera out to get over mountains and such. Perhaps the behavior could be smoother.

**Comment by Orangicus** [comment]
Referring mostly to how the camera has to navigate around the terrain - or it's position is (apparently) in some way oriented based on the surrounding terrain so that navigating over a hole drops my perspective down the depth of the hole instead of allowing my to fly over it as you might expect. I can make a quick gif of this if you prefer to see it.

**Comment by mklingen** [comment]
Nope, I know what you're talking about, that's intentional!

**Comment by Orangicus** [comment]
Closing because not an issue.
I'll make a separate suggestion for my thoughts on this.
