### ISSUE TITLE
[SUG] Perspective Camera

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#280]
Related to #279.

I would like to see camera control function statically (not reliant upon or interactive with terrain elements).

Or, an option to have it behave that way.

**Comment by BombBloke** [comment]
Regarding the inability to move the camera outside of the map, I assume this was initially to prevent users from seeing underground caves / resources without digging down - but with fog of war that should be a non-issue, and it's not like we can't hide layers anyway...

Regarding the camera automatically adjusting itself to according to the terrain height, maybe I've played too much Magic Carpet, but I personally prefer it that way. A problem with locking it to the height the user sets is that when you move the camera against a mountain, the game is left with a choice between either clipping the camera into blocks (which'll look a bit weird, to say the least) or simply disallowing the camera to move that way at all (which is a very frustrating system to play with).

**Comment by Orangicus** [comment]
As for the inability to move the camera outside of the map, your argument doesn't make sense considering the function of the FOW that doesn't reveal a block until it has been 'discovered.' Your suggestion  makes it seem like you should be able to see all the blocks in a map by simply switching to slice mode, which there's a system in place when shows a 'blank' sort of block if you've yet to discover it.

Clipping the camera into blocks is already done with slice mode, which could be implemented to automatically, I suppose, to change over when the user wants to clip into the side of a mountain, for instance. In that way, clipping doesn't look weird at all.
Conversely, disallowing the camera to move that way makes sense to me because that's how reality works. You can't just clip through things in passing. This is easily reinforced by the idea that slice mode is for terrain penetration, as far as seeing into the ground goes.

This is really only a suggestion because if I feel that i would enjoy it more this way, others may as well, and a large enough userbase inclined to that effect might raise developer consideration for its implementation.

**Comment by mklingen** [comment]
we constrained the camera to the map because we found some players accidentally scrolled way far away and were unsure of how to get back to the game. I can instead constrain it to a box that's, say, 64 voxels away from the ege or something.

**Comment by mklingen** [comment]
Okay, I'm going to re-open this and add an option for a fixed height camera.

**Comment by mklingen** [comment]
Added a setting for turning off surface height adjustment. When in that mode, you can press the middle mouse button to adjust the camera height, otherwise it remains stationary.

**Comment by mklingen** [comment]
Scratch that, it's just press left or right CTRL now and it will snap to the terrain height.
