### ISSUE TITLE
incompletely hidden areas

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#281]
Pretty straight-forward. In slice mode, underground areas yet to be discovered can be detected like so:
![dsdfsdf](https://user-images.githubusercontent.com/22550054/30999482-4ece1fce-a48a-11e7-9800-493d6be3061f.PNG)

That's cave mushrooms showing me where mushroom caves are.

**Comment by BombBloke** [comment]
You can also detect caves by simply dragging selection rectangles across layers with the dig tool. #211 has that marked off as "resolved", but it's still a thing in 17.09.27?

Wizards allow for similar shenanigans with their scanning abilities, but I'm assuming that'll be sorted when some sort of range-limiter gets implemented on their spells, assuming they even get to keep those particular ones.

**Comment by Orangicus** [comment]
The selection bug is difficult to prevent without procedurally generating subterranean areas in maps. It could also keep a sort of database of each map's blocks and then implement a kind of 'false block' which takes the place of the original and is only replaced when it is marked as discovered, including air blocks.

As for the wizard, that's definitely likely to be fixed whenever they get around to it.

**Comment by mklingen** [comment]
> You can also detect caves by simply dragging selection rectangles across layers with the dig tool. #211 has that marked off as "resolved", but it's still a thing in 17.09.27?

I thought for sure we had fixed that! Maybe not.

The cave shrooms showing up is definitely a bug. They are not supposed to exist until the cave is revealed.

The wizard spell is intentional (that's all its good for really).

**Comment by Blecki** [comment]
Are the cave shrooms instances? This is likely my fault if so.

**Comment by mklingen** [comment]
@Blecki yes they are, but the objects are invisible and inactive. If we want to avoid this and other problems it might be better for us to create invisible "placeholder" objects there instead which generate the creatures/plants when the cave gets revealed. They already waste a lot of space during serialization for example.

**Comment by Blecki** [comment]
Let me check if the new instance manager is honoring the visible flag first.

**Comment by Blecki** [comment]
Fixed on blecki-dev.
