### ISSUE TITLE
"Select dwarves" menu button

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#283]
![sdfsdfsdf](https://user-images.githubusercontent.com/22550054/31000669-61ce8b88-a492-11e7-99f4-7d183cb3455d.PNG)

Doesn't work when using the cursor to select it (it doesn't change the menu at all, nor does it select any dwarves that aren't already selected).

It functions normally with number key menu navigation; pressing the "1" key in the top level of the menu does select all dwarves, as it should.

Although you can't see that I press the "1" key, I've included a gif to illustrate this more easily.
![majig](https://user-images.githubusercontent.com/22550054/31000736-cdbebb9c-a492-11e7-9147-56f67438d673.gif)

**Comment by Blecki** [comment]
The toolbar is not for selecting all dwarves; drag a box around the dwarves you want.

**Comment by mklingen** [comment]
This is the intended behavior. Pushing "1" selects all dwarves. Clicking "select dwarves' activates the dwarf selector marquee tool.
