### ISSUE TITLE
Exiting crash report sometimes does not work.

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#285]
After a crash report displays, the game doesn't return to some main menu or anything.
It just gets stuck on the loading screen after you click 'okay' following the report.
In order to continue playing after the crash report, I have to exit and reopen DwarfCorp.

**Comment by Aikhjarto** [comment]
Maybe this depends on the type of crash report. The one I got could be dismissed with the 'okay' button and i was brought back to the main menu.

**Comment by mklingen** [comment]
That's weird. It is definitely supposed to take you back to the main menu. What was the crash?

**Comment by mklingen** [comment]
hopefully fixed by this https://github.com/CompletelyFairGames/dwarfcorp/commit/af625369ce311e7f8128a3e89f09591728625ba7

If something terrible happens and the user clicks on the crash report it should completely clear the game's state and start over.
