### ISSUE TITLE
Automation of going up or down slices

### ISSUE THREAD

**Issue by TRvanRossum** [CompletelyFairGames/dwarfcorp#287]
Currently, in order to go up or down multiple slices, you have to press the page up/page down key repeatedly. This is quite inconvenient, especially because you are reset to the top slice often. A way to deal with this would be to allow for going up or down multiple slices if the page up/down keys are held down.

**Comment by BombBloke** [comment]
The best way to micromanage slices is actually (AFAIK) an undocumented feature: try Ctrl + mousewheel.

Q is still the fastest way to get away from the top slice, mind you.

**Comment by mklingen** [comment]
How I do it usually is with Q and E. I almost never hit page up or page down, and almost never use the mousewheel. However, your suggestion of holding down the key to speed through the slices is a good one.

**Comment by mklingen** [comment]
implemented. Will be in the next build.
