### ISSUE TITLE
Better mining task assignment.

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#290]
Not really sure if bug or just weird.
So I'm trying to dig a kind of hole from the top of a mountain to the bottom with a corridor at the bottom to allow access.

Anyway, the dwarves prefer whatever side is closer instead of whatever side makes sense for pathing. So they go up underneath the build zone (5x5 with a staircase) by digging the corridor and then proceed to climb the sheer walls upward to dig from below instead of the gravity-assisted top-side downward dig (which was my intention for digging it and I even started the project from that side because I thought they'd pick whatever task I assigned first as the starting point for ease of control). It takes frickin' forever the way they decided to do it, so I manually removed the last bottom-side layer to force them to go in from the top and it worked.

It seems like the dwarves only, right now, consider the closest task to perform.
I feel like I should be able to have a bit of control over their task order, so my suggestions are:
1. Make the AI do tasks I tell them in the order I tell them to do them (a queue), possibly with a list in the profile I can edit.
2. Make the AI briefly compare the amount of work needed to complete a task and always perform the method which requires the least work or is most efficient (more memory/CPU).
3. Make the AI strictly prefer stairs over climbing sheer cliffs (but admittedly, some blocks could not have been reached without climbing; however, using the stairs at least <b>some</b> of the time would have considerably reduced build time).

**Comment by mklingen** [comment]
Okay, dwarfs already mine from top to bottom as a rule. I'm surprised they didn't do that. Specifically they mine in the order you assign (per assignment) in top-to-bottom order nearest to furthest. So it seems that's not working properly anymore.

As for assigning in an order that takes the minimum time, that's actually an NP-hard problem so I don't think we're going to solve that. Instead we'll have to rely on simple heuristics which will sometimes fail.

**Comment by mklingen** [comment]
This was addressed in the task management update.
