### ISSUE TITLE
Zone build task loading.

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#291]
1. Set build task (stockpile).
2. Save because stockpiles are touchy and might crash (it did not).
3. Later, reload this save (stockpile is tasked, but not yet built).
4. Craftdwarf tries to build stockpile.
5. On completion, crash.
.
.
1. Reload.
2. Try to remove stockpile before it gets built to stop crash.
3. On stockpile tool right-click (for removal), crash.

Similar, but not the same as, #257.
Definitely related to the saving issues.
Is an issue with all zones (stockpile / port / treasury).

**Comment by mklingen** [comment]
fixed by https://github.com/CompletelyFairGames/dwarfcorp/commit/8de40d98596ee4872bf237270c3fbd14244e0540
