### ISSUE TITLE
Zoom in/out on mouse location behavior not configurable

### ISSUE THREAD

**Issue by csp256** [CompletelyFairGames/dwarfcorp#293]
Please add an option to disable scroll wheel zooming being dependent upon mouse location. As a user I would like my "object selection" and "view movement" behaviors to be decoupled.

**Comment by mklingen** [comment]
Added option in this commit. will be in the next build https://github.com/CompletelyFairGames/dwarfcorp/commit/931eccac9cdf5debb7fd82ac8ac3e3d9e8cdbad5
