### ISSUE TITLE
AI pathing

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#296]
Just wanted to mention this before work. Not sure if it's been handled before the pending updates.

Built a tunnel into a mountain directly beside my initial starting position.
Build spiral staircase up to the top of that mountain to have the perfect spot to build a balloon port.
Craftdwarf decides to climb the mountain instead of take the tunnel path for some reason.

![fsadfasdfasdf](https://user-images.githubusercontent.com/22550054/31056494-376966a0-a687-11e7-9897-2238c550cb46.PNG)

**Comment by mklingen** [comment]
dwarfs need a free space above their head to jump. Are you sure your spiral staircase had adequate space? You could also build a shaft with a ladder.

**Comment by com1clyf3** [comment]
No response. Closing.
