### ISSUE TITLE
Sometimes built blocks don't show up

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#298]
Likely some kind of chunk rebuild race condition.

![image](https://user-images.githubusercontent.com/241184/31057082-ae5b1704-a6aa-11e7-8d1b-6c410e762efd.png)

**Comment by Blecki** [comment]
Believe this is related to another known issue - fix in progress.

**Comment by mklingen** [comment]
possible duplicate of #238

**Comment by mklingen** [comment]
seems fixed?
