### ISSUE TITLE
Massive Performance Drop

### ISSUE THREAD

**Issue by Tearakudo** [CompletelyFairGames/dwarfcorp#301]
![performance](https://user-images.githubusercontent.com/32318529/31060236-c03f7842-a6c4-11e7-9326-53d78e1789dd.jpg)
Got to about this state...

Suddenly i couldn't pull better than 10fps at any point, with minimal graphics settings (unable to disable vsync)

**Comment by mklingen** [comment]
Hm, TIL what the game looks like when you've been playing for more than a few minutes. Snow everywhere and bird eggs. My guess is that there are simply a ton of entities and the game can't keep up. If you can post a save file of some kind I can try to load it and figure out where the bottlenecks are.

**Comment by Tearakudo** [comment]
Unfortunately, i can't seem to get them to pick up the eggs to see if that helps. 

Hopefully this is what you needed for a save
[Manifest Vale_974.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1347712/Manifest.Vale_974.zip)

**Comment by Timvdleur** [comment]
Hi there,

In the linked clip you can see a huge performance drop. If I check my taskmanager my pc is handling just fine. I think it might hit an application limit (is it 32-bit?) in how much it can handle. selecting large chunks of rock to dig seems to make the problem worse.

https://www.youtube.com/watch?v=-tJmrf2c56g

**Comment by mklingen** [comment]
@Timvdleur can you try hitting F10 when this happens? That will show a list of functions and how much time they're taking. Yes the game is 32 bit. However this looks to me to be something like the path planner or another process that only happens intermittently.

**Comment by com1clyf3** [comment]
Currently being tackled by #651. Closing.
