### ISSUE TITLE
when generating a world: New game (advanced) crash. Caused by missing font.

### ISSUE THREAD

**Issue by Cowderp** [CompletelyFairGames/dwarfcorp#302]
When I try to generate a map to play on the game immediately crashes. It was working before the last update.

**Comment by mklingen** [comment]
Sorry. Which screen does it crash in? Can you fully generate the world, or does it crash before that happens? What platform are you running?

**Comment by Orangicus** [comment]
Just experienced this.

>New Game (Advanced)
> Set your logo and stuff
> Generate Map
> Crash

**Comment by mklingen** [comment]
Oh no. Will try to reproduce/fix tonight.

**Comment by Orangicus** [comment]
Probably important:
A tiny bit more exploring this and it makes it to the map screen, but it immediately freezes and breaks down to a crash after the mouse turns into the hourglass for loading the map.

**Comment by mklingen** [comment]
Okay, thankfully this crash got reported! #312 

Will look into this tonight.

**Comment by mklingen** [comment]
fixed by this https://github.com/CompletelyFairGames/dwarfcorp/commit/6908465d93bdcbc0e8d3a95ed6b2b48aa2e3a071

will push patch tonight. Bug was literally that I had a trailing space in the font name. D'oh!
