### ISSUE TITLE
Hired Dwarf not selectable

### ISSUE THREAD

**Issue by DCDragoner** [CompletelyFairGames/dwarfcorp#314]
This is the second time I've hired a dwarf and been unable to select it. Hovering over the dwarf its name is read as elf. The next line has gundrop, bow level o elf.

![dcissue1](https://user-images.githubusercontent.com/32471503/31105285-97227ad8-a7a8-11e7-91b3-a2e946027656.png)

**Comment by lemonrev** [comment]
This also happens when you quit and load back your game again.

It mostly happens when you restart your game no matter if its from a new load up or go back to the menu and load that way.

**Comment by mklingen** [comment]
Okay, definitely a bug of some kind. What is the dwarf's behavior? Does he act like the other dwarfs other than being unselectable?

**Comment by DCDragoner** [comment]
Well he seemed to. However all my dwarves were refusing to do any type of crafting task; cooking, making trinkets, etc. Which is why i hired the extra guy. I ended up quiting that save after writing the bug report.

**Comment by EdmundCyl** [comment]
I have the same problem and When i hovered over the dwarf that  i have just hired, it said palm tree..nothing below.

**Comment by mklingen** [comment]
okay interesting. Is this after you loaded from a file, or is this on a new game?

**Comment by EdmundCyl** [comment]
That was after i clicked save but did not exit the game or quit to the main menu. The same thing also happened before in games that i just started though.

**Comment by mklingen** [comment]
issue fixed by this commit, will be in the next build https://github.com/CompletelyFairGames/dwarfcorp/commit/207727da0ba4da1d2d8bdb3fd009549c53fbd2f8
