### ISSUE TITLE
Stockpiles getting destroyed creates many thousands of entities, which cause performance drop.

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#316]
So, I wanna move my stockpile after the first day or two (an important period of resource gathering, of course).

I make a new stockpile, treasury, and balloon port each because I don't want the old ones to even be visible from above ground.

It comes time to remove the old stock/treasury/port.
Huge number of items (of course); image included.
Lagging like all get out (24 FPS 1x speed; 2FPS at 3x speed), which didn't happen before (I've used pretty much the same process as I always have for initial stock migration.
It took me like ten seconds to get an actual pause menu open while jabbing Esc repeatedly because it was so bad.

I'm not sure what is causing it specifically, but I'm going to suggest that items of the same type that are near each other, or items that are all spawned at the same time by the same event, merge into a single drop for graphical convenience.

![ssfsdfsdfsdf](https://user-images.githubusercontent.com/22550054/31137795-22af14da-a821-11e7-9e3a-44f2fcd36c7a.PNG)

**Comment by mklingen** [comment]
Better yet, instead of dropping items on the ground like this (unless the zone is really destroyed by an enemy or something), we could just automatically stick them in dwarf inventories or other stockpiles.

**Comment by Orangicus** [comment]
Uh. So then stockpiles wouldn't pose the danger they normally do, I guess? I like the realistic bit of dwarves having to actually go and pick up individual items from stock and transport them.

How my understanding of what you're suggesting works is that stockpiles wouldn't actually contain droppable items unless an enemy destroys them (then having infinite containment space)?

**Comment by Aikhjarto** [comment]
Teleporting the stockpile content to a dwarf's inventory or to another stockpile is a bit "unrealistic".
What about making heaps? Other similar games (I don't know if I'm allowed to post the name of a competitor) solve the problem of considering large quantities of stuff lying in a stockpile by just reendering a small number of heaps of said items which represents like 100ish items.

**Comment by mklingen** [comment]
that's a good idea. We already do that for coins, we could also do that for resources pretty easily. We could heap them by item type.

**Comment by Aikhjarto** [comment]
@mklingen maybe not a single heap per type but a heap per 100 items of a type. Otherwise it might look like the destroyed stockpile dropped close to nothing.

**Comment by Orangicus** [comment]
For resource-saving purposes (related directly to the lagging part of this issue), I think it would be reasonable to have all items of a given type pop into a single stack with an indicator much like the one in the resource bar to show how many are in it. Dwarves will still have to collect one entity at a time from the stack like a stockpile, but it would serve to be semi-realistic (logistically speaking, not physically speaking) and reduce lag to have a single big ass pile of stuff for each item type that they have to transport in tidbits instead of many smaller piles of the various entity types.

**Comment by Aikhjarto** [comment]
@Orangicus I like your idea. Maybe also render it larger (or even scale with amount) than a single item. This will also reduce the lag significantly but the user gets a better feeling for the amount.

**Comment by mklingen** [comment]
okay, I implemented piles. These will be in the next build. There are no extra graphics for piles yet, but they work.

![piles](https://user-images.githubusercontent.com/241184/31309231-de51aa5e-ab50-11e7-85d5-2a052be371a2.png)

**Comment by mklingen** [comment]
The other piece of this problem will be making many thousands of resources not be a performance bottleneck. They're just sprites and should be much simpler to update/render than they are now.

**Comment by mklingen** [comment]
good, will close this.
