### ISSUE TITLE
While in world generator IndexOutOfRangeExceptionDwarfCorp.Gui.Widgets.WorldGenerationSettingsDialog+<>c__DisplayClass3_0`1 in <CreateCombo>b__0

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#317]
DwarfCorp.Gui.Widgets.WorldGenerationSettingsDialog+<>c__DisplayClass3_0`1 in CreateCombo { <lambda> } at line 48:21
Void <CreateCombo>b__0(DwarfCorp.Gui.Widget)
DwarfCorp.Gui.Root in SafeCall at line 296:33
DwarfCorp.Gui.Widgets.ComboBox in set_SelectedIndex at line 25:21
DwarfCorp.Gui.Widgets.ComboBox+<>c__DisplayClass10_0 in Construct { <lambda> } at line 84:41
DwarfCorp.Gui.Root in SafeCall at line 296:33
DwarfCorp.Gui.Widgets.ListView in set_SelectedIndex at line 23:17
DwarfCorp.Gui.Widgets.ListView in Construct { <lambda> } at line 58:21
DwarfCorp.Gui.Root in SafeCall at line 285:33
DwarfCorp.Gui.Root in CallOnClick at line 451:13
DwarfCorp.Gui.Root in HandleInput at line 401:33
DwarfCorp.GameStates.WorldGeneratorState in Update at line 291:17
DwarfCorp.GameStates.GameStateManager in Update at line 117:17
DwarfCorp.DwarfGame in Update at line 306:17

**Comment by Blecki** [comment]
Fixed.
