### ISSUE TITLE
NullReferenceExceptionDwarfCorp.Gui.Widgets.AnnouncementPopup in Redraw

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#320]
DwarfCorp.Gui.Widgets.AnnouncementPopup in Redraw at line 116:17
DwarfCorp.Gui.Mesh Redraw()
DwarfCorp.Gui.Widget in GetRenderMesh at line 428:17
DwarfCorp.Gui.Widget in GetRenderMesh at line 430:21
DwarfCorp.Gui.Root in Draw at line 556:13
DwarfCorp.GameStates.PlayState in Render at line 399:21
DwarfCorp.GameStates.GameStateManager in Render at line 149:29
DwarfCorp.DwarfGame in Draw at line 327:17

**Comment by Blecki** [comment]
Possibly fixed. Believe it may have been caused by the autosave callback making an announcement from a different thread.

**Comment by mklingen** [comment]
okay, will keep an eye on it and see if it pops up in the next release.
