### ISSUE TITLE
On world generation screen, must wait for initial generation before advanced options screen becomes interactive.

### ISSUE THREAD

**Issue by Blecki** [CompletelyFairGames/dwarfcorp#325]
Also, tooltips show up behind the advanced screen.

**Comment by mklingen** [comment]
I'm torn on this, because if we force the user to click "generate" or enter the advanced options first it increases the number of clicks they have to do.

**Comment by Blecki** [comment]
The way I originally set it up, you could make changes and hit generate again and it would abort and start over. Just need to fix it.
