### ISSUE TITLE
Some basic UI enhancements.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#332]
Just making a thread to remember this:

- [ ] Add an explicit "destroy room" and "destroy object" tool to the toolbar.
- [ ] Put the brush selector within or near the toolbar.
- [ ] Put info in upper left in tray to make it more readable. Also make its text smaller.
- [ ] Clean up fonts in dwarf info panel
- [ ] When any new tool is activated/changed make a little sound and put some text near the cursor.
- [x] Make dwarf inventory visible in dwarf info panel.

**Comment by Blecki** [comment]
I've been thinking about some kind of 'tray' - such that things can be shown or hidden. What would go in here: Minimap, Dwarf info panel, brush selector, designation filter, company info.

**Comment by Aikhjarto** [comment]
If I may add something: the trade-menu is quite annoying. Please add the following
- Pressing TAB should switch between the two fields for adding money.
- A filter (or at least sorting) for the item lists (the list of sellable items become quite long after a few hours of playing)

**Comment by com1clyf3** [comment]
Old news. Closing.
