### ISSUE TITLE
dwarves occasionally stuck in ceilings

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#334]
![stuckagain](https://user-images.githubusercontent.com/10678405/31259341-fbd531f6-aa13-11e7-90b1-7eeb6d430706.png)

I didn't see it happen onscreen, but this dwarf got stuck, possibly when jumping out of a chair after eating. He got free after a save+load, but it's possible he could've escaped before then, either on his own or by being dislodged by the blocks designated for building.

**Comment by mklingen** [comment]
I think what's going on is dwarf state isn't getting cleaned up properly after a sit or sleep. I think their physics must be disabled still (not that they're stuck in a ceiling).

**Comment by mklingen** [comment]
reproduced and fixed by https://github.com/CompletelyFairGames/dwarfcorp/commit/7266752bed1a532371d45a27e3abdc2a0eb252a7 will be in next build.
