### ISSUE TITLE
[SUG] blocks should collapse when mined underneath.

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#338]
I mined under a block of snow. The snow is now floating in the air.
![dwarfcrop_mine_under_snow](https://user-images.githubusercontent.com/3519989/31310368-64fbef88-ab97-11e7-856f-76a513dacb37.PNG)

**Comment by mklingen** [comment]
Not a bug. That's just how things work in this game. Blocks do not fall.

**Comment by Aikhjarto** [comment]
Ok, I understand this design decision, since it avoids dwarfs gets stuck/killed by a falling block when mining.
However, non-falling snow feels awkward. Maybe some type of block should be allowed to fall, like snow or sand.

**Comment by mklingen** [comment]
Not saying that they *shouldn't* fall, just that they don't. We probably can and should make blocks fall.

**Comment by com1clyf3** [comment]
@mklingen This still seems relevant.

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/39263114-3f824118-488f-11e8-8398-bfe394a23221.png)
