### ISSUE TITLE
[SUG] Long unsorted list for encursting

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#339]
Played a while and got like 100 different items and qualities for encrusted trinkets. Finding certain items in the unsorted list is quite a challenge.
![dwarfcorp_encrust_unsorted_list](https://user-images.githubusercontent.com/3519989/31310516-9e0262ec-ab99-11e7-98c4-4c890de42ef1.png)

**Comment by mklingen** [comment]
Hehe yes that's a consequence of having so many items. Will make sure that we sort by alphabetical order at least.

**Comment by Aikhjarto** [comment]
Having an option for sorting by number might be cool for bulk-encrusting.

**Comment by mklingen** [comment]
Could also just have the first option by "Any"

**Comment by mklingen** [comment]
Okay, list is sorted now. Will be in next build. https://github.com/CompletelyFairGames/dwarfcorp/commit/2c46d875096776fd4db8bb2538d6494bacc3e5b3
