### ISSUE TITLE
Make save system smarter about versions so as not to break backwards compatibility.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#34]
Right now all the entities in the game are serialized as raw data to the disk. If anything changes about the game version, the game files will end up being broken. Find out a way to gracefully support old game save files when new features are added.

**Comment by Blecki** [comment]
Okay. Here is the system I was describing. It's worked well for me in several pieces of not-game software.

To save:

A) Serialize game state intermediate object format. Each serializable class gets an associated serialization type. This can be as simple as a Dictionary<String, Object> for most types. Likely it will be a thin shell class wrapped around a dictionary.

B) Each bit of this is tagged with the current save file version number.

C) Write all this to disc using JSON or whatever.

Some notes: Everytime the data to be saved for a specific object is broken in some way, the version number of that object's save data needs to be incremented. 


To load - somewhat more complicated:

A) Deserialize the file into the intermediate object format.

B) For each deserialized object, check if a newer version is available. If so, upgrade the object. Upgraders must be provided each time an object's version number is incremented, and they must all be run when upgrading through multiple steps. For example, object X has version 3, but the current version is 5. So the upgrader for version 4 is run, then for version 5.

C) Turn these objects, now in the current format, back into the world.

**Comment by com1clyf3** [comment]
Has this fix been implemented?

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/39261223-d625b5c4-4889-11e8-90ed-ddc961353153.png)
