### ISSUE TITLE
encrust item selection drop-down menu does not vanish

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#341]
Open the drop-down menu for encrusting an item. Then press "1" to select dwarfs. The encrust menu disappears but the drop-down menu stays.
![dwarfcorp_press_1_while_dropdownselecting_encrust_item](https://user-images.githubusercontent.com/3519989/31310559-4ba4068a-ab9a-11e7-8358-da6ff458be8a.PNG)

**Comment by mklingen** [comment]
@Blecki how about we kill combo box selector when its parent gets destroyed/closed?

**Comment by Blecki** [comment]
It already should be doing this. It's likely because when the menu is closed, the combo box isn't destroyed, it's HIDDEN. Will fix.

**Comment by mklingen** [comment]
@Blecki already fixed!

**Comment by mklingen** [comment]
did it in a janky way, but its done https://github.com/CompletelyFairGames/dwarfcorp/commit/a1039cf75983d99a6b85e8091737c619ccf4a09d

**Comment by Blecki** [comment]
But I need things to do. :|

**Comment by mklingen** [comment]
try #332 ?
