### ISSUE TITLE
Spell tree state is not saved at all.

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#342]
Have a wizard doing research. The blue bar is filling up. Then save and load the world. The wizard looses all knowledge and canceled the task.

**Comment by mklingen** [comment]
I think its possible spell research is not saved at all at the moment. will check.

**Comment by mklingen** [comment]
yep, spells are not saved at all! adding that in right now.

**Comment by mklingen** [comment]
This has been fixed and will be in the next build.
