### ISSUE TITLE
Beds unused

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#343]
Despite having accessible beds, most of the time dwarfs all of a sudden fall asleep on the floor during work.
![dwarfcorp_beds_unused](https://user-images.githubusercontent.com/3519989/31310845-a5e4d9c6-ab9f-11e7-9302-b6b2e60215cf.PNG)

**Comment by mklingen** [comment]
I can't reproduce this. What were the steps you might have taken?

**Comment by Orangicus** [comment]
Based on the image, might be related to beds being inaccessible due to being too close together.

**Comment by Aikhjarto** [comment]
@Orangicus early in the game, I had 5 of these beds that close together. The dwarfs slept there.

**Comment by mklingen** [comment]
probably a save/load bug... do the dwarves sleep in *new* beds?

**Comment by mklingen** [comment]
being close together should not be a problem.

**Comment by mklingen** [comment]
fixed by https://github.com/CompletelyFairGames/dwarfcorp/commit/b7b479f48d57787a10223dc9cedddfd331f307bb will be in the patch today.
