### ISSUE TITLE
Trading Parties Head to Stockpile First

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#344]
I have a balloonport and several stock piles. One next to the balloon port, the others in my fortress in the mountain. When a trading partie of molemen, skeletons or the peter-pan-type-party arrives, they first head to a stockpile deep inside my fortress. Their second goal is the balloonport.

**Comment by mklingen** [comment]
okay, can reproduce, though I have no idea why it happens. investigating.

**Comment by mklingen** [comment]
fixed here https://github.com/CompletelyFairGames/dwarfcorp/commit/7af00a22d8b30c121eff40dadc94e6f39a968a48 will be in the next build.
