### ISSUE TITLE
Swamp golem sprite visible whilest beeing unexplored.

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#345]
The swamp golem sprite is larger than a common block. When scrolling (STRG+mousewheel) through unexplored areas, the golems eyes and forehead is visible.

**Comment by mklingen** [comment]
this should not be possible. Anything in an unexplored cave should be invisible. Will test.

**Comment by mklingen** [comment]
Was this after loading a save by chance?

**Comment by mklingen** [comment]
This is very likely to be fixed now by some changes we made to saving/loading.

**Comment by Aikhjarto** [comment]
Yes, this was in a loaded game.

**Comment by Aikhjarto** [comment]
Why is this closed? Already fixed for new games?

**Comment by mklingen** [comment]
yes it is fixed.
