### ISSUE TITLE
Lags and path-finding problem in large natural cave

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#346]
I dug up a large natural cave with a huge amount of bats, scorpions and other beasts.
The game started to lag immensly (like 2 fps) after the dwarfs started fighting. My dwarfs fought bravely and killed lots of beasts (one dwarf died doing so). But even now when the situation is quietly and no fights are going on, the lags continue and the dwarfs cannot find a path out of the large natural cave.
Savegame is attached.
[DwarfCorp.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1366369/DwarfCorp.zip)

**Comment by mklingen** [comment]
It's not unusual for very large caves to slow down the game. However I'm surprised you were only getting 2 FPS. What are your system specs?

**Comment by Aikhjarto** [comment]
Intel I7-3770k
16 GB RAM
Windows 10 64-bit

**Comment by mklingen** [comment]
GPU?

**Comment by Aikhjarto** [comment]
Radeon 7970

**Comment by mklingen** [comment]
Likely this was caused by #433
