### ISSUE TITLE
Wrangle Animal Glitch

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#349]
Build a animal pen. During build, assign dwarfs to wrangle animals. Of course, they won't until the animal pen is finished but selecting animals for wrangling is possible already.
However, they also do not wrangle the selected animal once the animal pen is finished. They do also not wrangle other animals until all animal wrangling is canceled. As free animal roam around, it is quite tedious to find the ones which have been selected during the build of the animal pen.

**Comment by mklingen** [comment]
Fixed by this https://github.com/CompletelyFairGames/dwarfcorp/commit/3a7b687969123beb832b387cc086f17696257e4e will be in the next build.
