### ISSUE TITLE
Suggestion: World Seed

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#350]
Sometimes a world is generated which is just perfect for some purpose.
Then it would be nice to get the seed of the random generator and set it in the "New Game (Advanced)" menu to be able to play the perfect world again.

It would be also very beneficial for debugging to have a reproducible world generation.

**Comment by mklingen** [comment]
this is already implemented. The name of the world is the seed.

**Comment by Aikhjarto** [comment]
And how can I set the name of the world?
"New Game (Advanced)" does only allow setting the name of a company and the motto, not the name of the world.

**Comment by mklingen** [comment]
Go to the advanced world settings.

**Comment by Aikhjarto** [comment]
Sorry, for asking stupid questions, but I cannot find the advanced world setting.

**Comment by mklingen** [comment]
Not a stupid question. So you generate a world first. Then there is a button on the right side called "Advanced..."

**Comment by Aikhjarto** [comment]
Not seeing this. I assume it should be in the main menu.
![dwarfcorp_main_menu](https://user-images.githubusercontent.com/3519989/31316874-57aaf9a6-ac36-11e7-8430-7b74862ae37a.PNG)

**Comment by mklingen** [comment]
No. here:
![worldgen](https://user-images.githubusercontent.com/241184/31316887-6b15aed2-ac04-11e7-83ca-3af3db3e51dc.png)

**Comment by Aikhjarto** [comment]
I've never seen such a screen. How to get there?

**Comment by mklingen** [comment]
Main Menu > New game (Advanced) > Generate World

**Comment by Aikhjarto** [comment]
Thanks a lot. Found it!
And thanks for your always fast responses and bug-fixes.

**Comment by mklingen** [comment]
thank you so much for all these bug reports.
