### ISSUE TITLE
Simulation Speed Button Issue

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#351]
With the `X` and `Y` keys on the keyboard, the simulation speed can be adjusted quickly be pressing them rapidly.
On the other hand, the two UI buttons on the lower right corner for mouse usage,  can only be pressed slowly. When pressing them fast (more than once per second), only one hit is recognized.

**Comment by com1clyf3** [comment]
Sounds like #8 Closing.
