### ISSUE TITLE
Null reference in resourcelibrary CreateCosmeticChildren

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#352]
![error](https://user-images.githubusercontent.com/3519989/31316748-f7fb3586-ac33-11e7-9cc6-31f755b65f0e.png)
[DwarfCorp.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1366862/DwarfCorp.zip)

**Comment by mklingen** [comment]
Unfortunately old saves can't be loaded anymore so I can't reproduce. Will see if it comes up again.

**Comment by Aikhjarto** [comment]
Its not an old save. It created with self-compiled version from git-repo from 4 hours ago.

**Comment by mklingen** [comment]
Oh okay, will try it!

**Comment by mklingen** [comment]
Yeah I'm sorry, even in the past 4 hours I made breaking changes to the save system and this file can no longer be loaded.

**Comment by mklingen** [comment]
Fixed this issue.
