### ISSUE TITLE
Reproducible World

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#355]
`World-Generator->Advanced -> Okay`
According to #350, reusing the same name (and of course settings) should produce the same world.
Using `Advanced -> Okay` several times without changing anything, does generate different world.

**Comment by mklingen** [comment]
Okay this is definitely a bug.

**Comment by mklingen** [comment]
Fixed in master. In the next build the name of the world will be a reproducible seed.
