### ISSUE TITLE
Drop-down selection in options menu not working

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#357]
Version: current HEAD of git-repo, i.e. 17.10.08.

`Main Menu -> Options` has several drop-down menus (like `Resolution` or `GUI Scale`)
Non of them actually drop-down when clicked.

**Comment by mklingen** [comment]
How embarassing. will fix.

**Comment by mklingen** [comment]
Fixed by this, will be in a hotfix shortly https://github.com/CompletelyFairGames/dwarfcorp/commit/4e87e1ce2580ec7eee7ccb193e08fd096af20b73
