### ISSUE TITLE
Dwarves don't unreserve beds when woken up

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#358]
Wait until your dwarves are asleep, then issue an attack or chop order. The beds they were using will never be free to use again (tool for moving objects claims they're still in use).

**Comment by Aikhjarto** [comment]
This could be the way to reproduce #343

**Comment by mklingen** [comment]
Oh you're right. That is definitely causing this. Will ensure they unreserve. Also probably happens with chairs from time to time.

**Comment by mklingen** [comment]
fixed by https://github.com/CompletelyFairGames/dwarfcorp/commit/b7b479f48d57787a10223dc9cedddfd331f307bb will be in the patch today.
