### ISSUE TITLE
god-mode spawn menu tweaks

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#359]
-remove generic items like spawn "trinket" or "gem-encrusted trinket" or "meal", since 'rand' version exists
-maybe have "rand bone" or rand meat" instead of generic meat and bone?
~~-missing items, like wheat resource~~
-spawned wheat and cactus float above ground, and snow pine seems too low

**Comment by mklingen** [comment]
Sorry about that. Can you make these seperate issues so I can keep track of them better? We can close #211 as well.

**Comment by mklingen** [comment]
No item is missing in god menu btw, "wheat resource" is actually called "grain resource". Grain is produced from wheat.

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/39263598-ab0ace04-4890-11e8-8d70-cbcefd22c172.png)

Fixed in 4e970004

Closing.
