### ISSUE TITLE
VoxelHandle not serializable to/from string.

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#362]
![dwarfcorp_load_crash](https://user-images.githubusercontent.com/3519989/31319664-c6b60d32-ac67-11e7-932d-d7beb1197e40.png)
[DwarfCorp.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1367101/DwarfCorp.zip)

**Comment by Aikhjarto** [comment]
Version was mklingen's dev branch from just now.

One of the last actions was: A miner was interrupted by a beast and dropped a stone. Ingame the stone had a bright yellow rectangle and a stray bag-icon with a small yellow arrow (sorry, forget to make a screenshot). The stone was not gather-able.

**Comment by mklingen** [comment]
Can reproduce. This is a huge bug which will break saves any time the user has active dig orders. Will fix.

**Comment by mklingen** [comment]
https://stackoverflow.com/questions/24504245/not-ableto-serialize-dictionary-with-complex-key-using-json-net

**Comment by mklingen** [comment]
Fixed by recent patch.
