### ISSUE TITLE
[SUG] World Generation: placement of landing spot

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#363]
To make a perfectly reproducible game, not only the seed of the world generation + settings must be known, but also the landing spot (the yellow rectangle in the world generation).
I assume the number at the end of the savegame folder represents the location of the rectangle.
It would be nice if this number could be entered in the world-generation screen.

**Comment by mklingen** [comment]
You can just click where you want your colony to be... the number is just a random number between 1 and 1000. You're saying you want a start location that you can precisely enter?
