### ISSUE TITLE
Fungi on surface on newly generated world?

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#364]
Not sure, but these look like fungi.
If they are, they should not be located on the surface.
![dwarpcorp_fungi_on_surface](https://user-images.githubusercontent.com/3519989/31319876-5c6a1b9a-ac6b-11e7-9778-52ff5090b01c.PNG)

**Comment by mklingen** [comment]
Those are mushrooms. Yes mushrooms grow in forests, as they do in real life!

**Comment by Aikhjarto** [comment]
The tooltip says otherwise
![dwarfcorp_mushroom](https://user-images.githubusercontent.com/3519989/31320187-8e82350e-ac70-11e7-9c04-2b40c19853dc.PNG)

**Comment by mklingen** [comment]
Sure, you can only plant it underground for balance reasons, but they also grow naturally on the surface in forests.
