### ISSUE TITLE
Cooking task interrupted by dwarf sitting. Bad behavior ensues.

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#365]
Assigned a cookjob to a single craftsdwarf which was about to take a seat.
Dwarf is cooking while hovering over it's seat. Items fly from stockile to dwarf over a large distance.
The kitchen table gets the correct working animation despite the dwarf is located elsewhere.
![dwarfcrop_assing_cookjob_to_craftdwarf_while_sitting](https://user-images.githubusercontent.com/3519989/31320040-3366bafc-ac6e-11e7-94af-275d533cc91c.PNG)

**Comment by Aikhjarto** [comment]
It does not seem to appear when the dwarf is already sitting.
It appears when the cooking-order is given while the dwarf jumps into his seat.

My playstyle was to have the game on 3x speed and pause whenever i see a dwarf idleing. Thus, i caputred the dwarf during his animation.

**Comment by com1clyf3** [comment]
#433 closed it for now. Will investigate 3x speed and tasks further however. Likely bugs are hiding there.
