### ISSUE TITLE
Balloon landing on stockpile

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#366]
Just having a new game and built no balloonport so far.
However, trading parties arrive and a balloon suggessfully landed on my stockpile (trading was possible)
Not sure if this is a sideeffect of fixing #344
![dwarfcorp_balloon_landing_on_stockpile](https://user-images.githubusercontent.com/3519989/31320136-a2c3ca06-ac6f-11e7-9c84-53964e8287bd.PNG)

**Comment by mklingen** [comment]
does it warn you about a balloon port not existing by any chance?

**Comment by Aikhjarto** [comment]
I did not see a warning. However, this does not mean there was no warning.

**Comment by Blecki** [comment]
Isn't the initial stockpile actually a balloon port?

**Comment by BombBloke** [comment]
I thought it was. All Steam builds I've played thus far have had balloons landing there with no need to manually build a port.

**Comment by mklingen** [comment]
Yes but this person says they deleted the balloon port and instead built a stockpile there, unless I'm mistaken.

**Comment by Orangicus** [comment]
You can see by the absence of the initial flags that they did, in fact, delete the original stockpile/port in that spot, but stockpiles have been weird and I feel like it -should- be this way. If you have no port and you've got a surface stockpile, maybe it should work as a port for convenience since the two are pretty much the same thing, except that one is also capable of balloon traffic.

**Comment by Aikhjarto** [comment]
No, I did not build neither remove any stockpile/balloonport for the screenshot.
On the screenshot there is the initial stockpile.

**Comment by mklingen** [comment]
oh, in that case this is the intended behavior. A balloon port is a stockpile. The initial stockpile is a balloon port.

**Comment by Aikhjarto** [comment]
From the tutorial: `Balloon ports are necessary for trade.`
Thus, I was confused that trading is possible without a balloonport.

**Comment by mklingen** [comment]
The initial stockpile is a balloon port.
