### ISSUE TITLE
Allow player to build flags.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#367]

**Comment by lemonrev** [comment]
WHY? Do you want more of a dungeon keeper style game ? it might turn into that eventually but right now the selection of the dwarfs works well enough if you keep them selected.

**Comment by mklingen** [comment]
@lemonrev I don't understand your comment... maybe you intended to comment on a different issue?

**Comment by lemonrev** [comment]
The person asked to build a flag, I had thought he was talking about game play type where you put down a flag and your minons or fighters would gather so you just placed the flag closest to the enemy and you could hord rush the person your attacking.

**Comment by mklingen** [comment]
No, I'm talking about literally being able to build flags as decorations.

**Comment by mklingen** [comment]
Done.
