### ISSUE TITLE
strangeness with pausing

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#371]
- [x] clicking 'continue' from the settings dialog that pops up on pressing escape always unpauses the game, even if it was paused before pressing escape - game should remember original state when exiting dialog, and maybe change button text to 'back to game'.
- [x] related: with game not paused, press escape to bring up settings dialog, then escape again. dialog closes, but game does not unpause.
- [x] can use pause key to pause/unpause while 'escape' settings dialog is active - unpausing should close the dialog.
- [x] start a new game, pause, then check 'disable' and close the tutorial. when unpausing or opening the economy screen, the 'time' tutorial window will open.

**Comment by Blecki** [comment]
Tutorial bit is fixed.

**Comment by mklingen** [comment]
Fixed all of these issues on master. Will be in the next build.
