### ISSUE TITLE
indicate object facing with building previews

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#375]
since chair facing is not easy to tell when building, and it does have the minor visual effect of determining which direction dwarves eat food from, add something like an arrow on the ground to show orientation when rendering object preview 'blueprints'?

**Comment by Blecki** [comment]
Alternatively, should dwarves always turn toward tables when eating?

**Comment by mklingen** [comment]
This is done in my branch. 
![rotator](https://user-images.githubusercontent.com/241184/32700085-e5d3ec70-c78d-11e7-99b5-5d7c553bd625.png)
