### ISSUE TITLE
creature sprites do not rotate when game is paused

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#376]
rotating a camera around a dwarf will show his front, side, and back sprites, depending on the angle, but when the game is paused, the view never changes.

**Comment by mklingen** [comment]
It's because when the game is paused "update" doesn't get called. Should maybe move that code to "Render" instead.

**Comment by mklingen** [comment]
I took a shot at this today, but unfortunately the sprite drawing code has a deeply embedded assumption that pixel data in the sprite sheet will get initialized inside `Update`, so when the game is paused, that data isn't available. I am thinking of switching the way we pause over to just slowing down the game speed to a ridiculously tiny rate but keep updating as normal.

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/39271659-a1121418-48a7-11e8-9d0d-2191fa73fea3.png)

**Comment by mklingen** [comment]
Fixed in master.
