### ISSUE TITLE
Rendering blocks issues.

### ISSUE THREAD

**Issue by Haust891** [CompletelyFairGames/dwarfcorp#378]
I got a bug with the rendering of blocks i build. 
The blocks vanishes and after that i cant seem to save the game most of the times.
When i managed to save i loaded and the block where back.
Other times i saved and when i tried to load the save were corrupted (got no pic of the load error but will get one if it happens again). 

http://steamcommunity.com/sharedfiles/filedetails/?id=1163561236

Link to a picture of building with vanished blocks.
Ive only had the problem so far while building above the ground. Will do some further testing.

**Comment by mklingen** [comment]
duplicate of #298, which we thought we fixed but apparently not. The loading of saves failing definitely should not be happening. What error are you getting when that happens?

**Comment by Haust891** [comment]
i didnt printscreen the error, and now when i try to recreate the problem its not happening. 
But ill keep you posted if it pop up again!
