### ISSUE TITLE
Dwarves can throw items into stockpile from below.

### ISSUE THREAD

**Issue by Blecki** [CompletelyFairGames/dwarfcorp#390]
-Dig immediately below a stockpile.
-Dwarves throw resources into the ceiling.

**Comment by mklingen** [comment]
Hmm, good point. Dwarves consider "adjacent" in 3D to allow them to throw from *above*. But I guess they should never consider something below something else to be adjacent.

**Comment by mklingen** [comment]
This has been fixed by a recent change, though I'm not sure what other new problems it might have caused!
