### ISSUE TITLE
Progress bars get drawn multiple times per frame

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#398]
Just an issue with Drawer3D and Drawer2D in general -- these things should only get called from within `Render`, and not from within `Update`. That's kind of a problem because they're most useful as fire-and-forget calls in `Update`. Maybe I can pass in the line number implicitly or something to prevent them from getting multiple times in the same update cycle.

![issue](https://user-images.githubusercontent.com/241184/31585751-1a89ff36-b195-11e7-83ce-2fdf66976f88.png)

**Comment by Blecki** [comment]
I've been meaning to visit drawer2d. Perhaps now is the time.

**Comment by mklingen** [comment]
Fixed it on my branch by having it only do anything when called from `DwarfGame.Draw`, or in the very first `DwarfGame.Update` before the next `Draw`.
