### ISSUE TITLE
Craftdwarf places floor through the wall

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#402]
Dug a cave just one level below a flat ground. 
Order craftdwarf to build dirt floor.
Craftdwarf fetches dirt from stockpile, moves on flat ground above cave and starts throwing dirt through the ground.

**Comment by mklingen** [comment]
Actually the opposite of an earlier bug where they were throwing stuff through the ceiling. It's not really a bug so-to-speak. Dwarfs are supposed to be able to build and mine stuff up to 3 blocks away, but there's no check for occlusion. If that were not the case, building stuff would be much much harder. I guess I can also add a check for occlusion and see what happens.

**Comment by Aikhjarto** [comment]
+1 for the occlusion check

**Comment by Timvdleur** [comment]
Might be the same as with attacking through obstacles:
https://github.com/CompletelyFairGames/dwarfcorp/issues/420

**Comment by mklingen** [comment]
Again, not sure it's a bug, just something that doesn't line up with what you'd expect. Building is made intentionally loose like this to allow dwarfs to build structures even when blocks are covered by other blocks. If this was not the case a dwarf could get into a situation where the structure he's building is impossible to complete. To keep things simple, we made the compromise that dwarfs can teleport blocks up to 3 tiles away.

**Comment by com1clyf3** [comment]
Yeah. I'm okay with that. If there's one issue that might be worth it, it's number one. Since if you set a lot of tasks, resources are popping out of the ground for a long while. It's very noticeable and visually weird. Number two is a short experience and easier to dismiss. If number one isn't worth the effort, let's close it up though.

**Comment by mklingen** [comment]
I'm not sure what you're referring to with #1, is that when the dwarf is tossing the resource?

**Comment by com1clyf3** [comment]
Yes. The first image in my previous response. If you make a cave one layer below the surface, then build a floor there (though I think this happens for building anything), you will see the resource being used go through the surface and float above the terrain for a moment.  In the image, that dirt resource next to pause isn't on the ground. It's clipping out from a layer below.

This isn't noticeable with a small task, but if you order something like a large floor, then player will observe this happen over and over again.

**Comment by mklingen** [comment]
> Yes. The first image in my previous response. If you make a cave one layer below the surface, then build a floor there (though I think this happens for building anything), you will see the resource being used go through the surface and float above the terrain for a moment. In the image, that dirt resource next to pause isn't on the ground. It's clipping out from a layer below.

Oh. That's just because the animation of the dwarf throwing the dirt doesn't collide with stuff. That's intentional. Otherwise you'd see it disappear when the terrain is sliced. What would you expect to happen?

**Comment by com1clyf3** [comment]
I'd expect not to see resources pop up from above ground. It looks like the surface is just temporarily sprouting resources.

**Comment by mklingen** [comment]
That's the dwarf throwing the resource. It goes through a ballistic arc, which takes it above the terrain. This looks good when there's nothing above the resource but yes it looks weird underground when you haven't sliced to the layer that the dwarf is on. So it's just an unrealistic graphical defect, sure.

I might be able to hack a way to make the dwarf not toss a visible resource when the block above him is occupied.

**Comment by com1clyf3** [comment]
Yup. I get why it's happening. Like the original bug reporter, it's not game breaking, it's just a visual that doesn't really make a sense, and when happening a lot, becomes what could be considered a UX or design issue. Definitely not a priority bug, but yeah, try a fix when you find the time.

**Comment by com1clyf3** [comment]
Going to assume no and close.
