### ISSUE TITLE
Suggestion: Promote Info

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#405]
When the Info-Dwarf on the bottom right appears and says that a dwarf wants to be promoted, a click on the info-dwarf opens the economy screen with the first dwarf selected. In this screen you can scroll through the dwarfs to find the one who wants a promotion.
However, it would be nice if the dwarf who actually wants the promotion is preselected.

**Comment by com1clyf3** [comment]
Not a bad idea. Closing for regression, but will link to #621 to keep it part of the discussion.
