### ISSUE TITLE
ESC Menu not working in all toolbar states

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#406]
I'm not sure if this is a bug or a "feature"
Being in a submenu of the toolbar, like "Cook Food" or "Farm", pressing the ESC key does not bring up the usual menu with "Quit", "Save", e.t.c.

**Comment by mklingen** [comment]
This is just how the ESC button works. Pressing ESC brings you up one submenu until you get to the top toolbar. We found that when people were confused about what tool they were in, they would push ESC to try to cancel the tool.

**Comment by mklingen** [comment]
Reopening issue because I misunderstood you. ESC key is not exiting submenus properly right now.

**Comment by Blecki** [comment]
I reordered the hotkeys to put 0 last to match keyboard layout. ESC was hitting the wrong button!
