### ISSUE TITLE
Unreadable Numbers in Trade Menu

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#407]
![dwarfcorp_trade_unreadable_numbers](https://user-images.githubusercontent.com/3519989/31635342-a9773e66-b2c6-11e7-8d29-c7166c72b688.PNG)

**Comment by Searthh** [comment]
_Confirmed in DwarfCorp Version: 8f281af (XNA version) / OS: Windows 10 Home 1703 / 64 bit / 8 GB RAM / Interl i5 7200U @2.50 GHz 2.70 GHz_

![image](https://user-images.githubusercontent.com/32852691/31636910-aead491a-b2cc-11e7-8634-1d5e4e1449dd.png)

**Comment by mklingen** [comment]
Yeah this is an example of a font getting changed to have outlines when it shouldn't have.

**Comment by mklingen** [comment]
Fixed in my branch.
