### ISSUE TITLE
Items from traders can be traded multiple times

### ISSUE THREAD

**Issue by Searthh** [CompletelyFairGames/dwarfcorp#408]
_DwarfCorp Version: 8f281aff (XNA version) / OS: Windows 10 Home 1703 / 64 bit / 8 GB RAM / Interl i5 7200U @2.50 GHz 2.70 GHz_

When trading an item, so that it enters your inventory, it never leaves the inventory of the trader.
By clicking 'Trade' again, items that are in limited supply can be traded endlessly,
In the screenshot, a benign example of trading the 6 glass of the molemen twice, to end up with 12 glass.

![image](https://user-images.githubusercontent.com/32852691/31635252-6887dcc6-b2c6-11e7-97e3-cfbb69841cae.png)
![image](https://user-images.githubusercontent.com/32852691/31635265-7661da9a-b2c6-11e7-90ef-09a7a302916d.png)
![image](https://user-images.githubusercontent.com/32852691/31635308-8cde6270-b2c6-11e7-8533-875686a2becc.png)

**Comment by mklingen** [comment]
This definitely should not have happened....

**Comment by mklingen** [comment]
Fixed in my branch. Thanks as always for the extremely helpful and descriptive bug reports!

**Comment by Searthh** [comment]
Thank you! Awesome to see how quick you are with these fixes, and that you consider so many suggestions from the community.
