### ISSUE TITLE
Cursor missing in "Money to trade"

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#409]
Its quite random. While entering money to trade, I sometimes get a textcursor but most of the times i don't.

**Comment by mklingen** [comment]
I don't understand. Can you clarify?

**Comment by Blecki** [comment]
I think he means the | bar in between letters showing where you're typing. 

This is almost a duplicate of #256 - and the solution is the same. It's on my list.

**Comment by Aikhjarto** [comment]
@Blecki yes, by "textcursor" i meant the vertical bar between the numbers.

**Comment by com1clyf3** [comment]
Closed since dupe.
