### ISSUE TITLE
Palm trees 'pop in'

### ISSUE THREAD

**Issue by Blecki** [CompletelyFairGames/dwarfcorp#410]
Look at some palm trees. Move the camera. Notice palm trees far away popping in and out.

Mind boggling. Their bounding box is correct, no other trees affected.

**Comment by mklingen** [comment]
We only check for the center of the bbox when deciding to draw them right? If that's the case its not surprising at all. They have the largest bbox area after all.

**Comment by Blecki** [comment]
We aren't using the octtree for this, are we?

Ugh.

**Comment by com1clyf3** [comment]
@mklingen Close?

**Comment by mklingen** [comment]
Not a bug.
