### ISSUE TITLE
Performance high CPU use, new game Large colony (large base picked through map creation, might be related to #301 #377

### ISSUE THREAD

**Issue by Plasmaburndeath** [CompletelyFairGames/dwarfcorp#416]
Hi Devs, this issue might be related to #301 #377 bug reports, but I can duplicate this each time I try on a new game.  Basically start new advanced game, select a spot, increase colony size to large, and start game. As soon as I do this, either when I select my Dwarfs, or when telling them to mine, the game right away tanks performance and CPU usage spikes to 32+% memory use remains stable at about 332MB. 
FPS drop to 0 or 1, unless I pause game then they come up to 59-60 until un-pausing it. 
My recommendation would be to dump more of the game to GPU processing which should help on this, but I know you know your engine the best.   
Here are details of my system setup, as you can tell I can do pretty much anything needed to help figure this out with you if you need more feedback or help.   (Game already uninstalled, reinstalled, caches cleared, so on.)  

      Time of this report: 10/19/2017, 10:54:35
             Machine name: VISION
               Machine Id: {6F302653-4747-44CF-A5CA-0670AACE1D7E}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 15063) (15063.rs2_release.170317-1834)
                 Language: English (Regional Setting: English)
      System Manufacturer: MSI
             System Model: MS-7A68
                     BIOS: B.30
                Processor: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 CPUs), ~4.2GHz
                   Memory: 32768MB RAM
      Available OS Memory: 32724MB RAM
                Page File: 5820MB used, 26904MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: Using System DPI
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.15063.0000 64bit Unicode

Card name: NVIDIA GeForce GTX 1070
       Manufacturer: NVIDIA
          Chip type: GeForce GTX 1070
           DAC type: Integrated RAMDAC
        Device Type: Full Device
         Device Key: Enum\PCI\VEN_10DE&DEV_1B81&SUBSYS_33011462&REV_A1
      Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
Device Problem Code: No Problem
Driver Problem Code: Unknown
     Display Memory: 24443 MB
   Dedicated Memory: 8081 MB
      Shared Memory: 16362 MB
       Current Mode: 1920 x 1080 (32 bit) (60Hz)
       Monitor Name: Generic PnP Monitor
      Monitor Model: ASUS VN247
         Monitor Id: ACI24C3
        Native Mode: 1920 x 1080(p) (60.000Hz)
        Output Type: DVI

![252390_20171019104334_1](https://user-images.githubusercontent.com/32935601/31780418-48d0461a-b4bb-11e7-9c93-2bdafc3a8f48.png)

**Comment by mklingen** [comment]
Large maps are right at the edge of what the engine can handle right now. It's not suprising that the performance is bad, though we can and should work on it. Water on large maps is going to be especially taxing.

**Comment by Plasmaburndeath** [comment]
TY for replies- I am wondering Is it possible on your engine, to direct more of the calculations towards the GPU?   I know obviously the engine is still under development, but it seems like it wants to act as CPU hang or CPU leak type of behavior.  for only using a few hundred MB of active memory I find it strange that it wants to eat up 30+% of CPU use which of course you can see I have a i7-7700K so trying to figure out what is so demanding on CPU is first thoughts I had.  I have seen before where if a certain type of  thread is being sent to the CPU, and is not being handled well, that it turned out to be something GPU had better pipes for.   

Thank you again for your great game :-)  I have technical background and I have also done UAT testing before.   If you need any longer term monitoring on memory and cpu use logged I can do that, I can write scripts to grab that data every now and then.

**Comment by mklingen** [comment]
Maybe? It would be a lot of work. The stuff that takes the most time in our engine is physics and AI. Not necessarily stuff that's easy to implement on a GPU, especially without GPGPU (like CUDA) computation, which we have no plans of supporting. I think the lowest hanging fruit for doing something on the GPU might be the water physics.

**Comment by mklingen** [comment]
Btw I just ran some large maps and consistently saw 50-60 FPS. It's possible we've fixed some of the worst performance issues since you tried, or my computer might just be beefier.

**Comment by com1clyf3** [comment]
Closed for now. Performance obviously still an ongoing battle.
