### ISSUE TITLE
Creatures can attack through z levels.

### ISSUE THREAD

**Issue by Searthh** [CompletelyFairGames/dwarfcorp#420]
_DwarfCorp Version: 8f281af (XNA version) / OS: Windows 10 Home 1703 / 64 bit / 8 GB RAM / Interl i5 7200U @2.50 GHz 2.70 GHz_

Creatures can attack through ceilings/floors/a long vertical distance. Maybe vertical distance is not always taken into account in calculating distance?

It can be reproduced by building a two-story building, then filling one floor with rabbits and one with scorpions. The rabbits will eventually be killed by the scorpions. I tried it with a taller tower (at least 4 blocks between rabbits and scorpions) and it did not make a difference. I've seen a dwarf fight a bat in a cave underneath him as well.

![image](https://user-images.githubusercontent.com/32852691/31852586-783d508a-b67a-11e7-9a61-de878359bd78.png)

![image](https://user-images.githubusercontent.com/32852691/31852591-8e19421a-b67a-11e7-95bc-a5a71c994655.png)

![image](https://user-images.githubusercontent.com/32852691/31852597-9838b37a-b67a-11e7-927f-b702c9a74d3e.png)

**Comment by mklingen** [comment]
You're right, there's absolutely no consideration of occlusion when dealing with fighting. They can just attack anything within a radius (usually of 4).

**Comment by love2readandlearn** [comment]
My miner kept getting attacked by spiders that where 5 or 6 levels down and none of the dwarves would move. I tried to save, that didn't help so I tried to reload and the game crashed.

**Comment by mklingen** [comment]
This should be fixed in the next build (attacking through z levels).

**Comment by mklingen** [comment]
I have reopened this issue because it occured to me that this will only work for creatures getting attacked organically (that is, because they saw an enemy). It will not help in the case where the player explicitly tells a dwarf to attack a creature underground. For that we will need to occasionally do the occlusion test while the dwarf is attacking.

**Comment by com1clyf3** [comment]
Original bug no longer occurs. We still need to keep this open @mklingen ?

**Comment by mklingen** [comment]
I think this is fixed.
