### ISSUE TITLE
NPE on loading a save

### ISSUE THREAD

**Issue by chryselectrum** [CompletelyFairGames/dwarfcorp#427]
CreatureAI.cs

The method

        [OnDeserializing]
        public void OnDeserialize(StreamingContext ctx)
        {
            if (CurrentTask != null)
            {
                CurrentTask.Script = null;
            }         
            Sensor.OnEnemySensed += Sensor_OnEnemySensed;
        }

Should be something like

        [OnDeserializing]
        public void OnDeserialize(StreamingContext ctx)
        {
            if (CurrentTask != null)
            {
                CurrentTask.Script = null;
            }
            if (Sensor != null)
                Sensor.OnEnemySensed += Sensor_OnEnemySensed;
        }

**Comment by mklingen** [comment]
Wow, I just made this change and had not tested saving/loading yet. You're right that I need to fix this.

**Comment by mklingen** [comment]
Fixed in mater.
