### ISSUE TITLE
Auto farm plant tasks fail

### ISSUE THREAD

**Issue by Blecki** [CompletelyFairGames/dwarfcorp#431]
Dwarves decide to replant farms when bored, and create task, but it is never actually done.

To reproduce - farm something then harvest it. When tile gets a green hilite, the plant task has been created.

**Comment by mklingen** [comment]
@Blecki do we know if this has been solved?

**Comment by Blecki** [comment]
I haven't. On Oct 26, 2017 10:57 AM, Matthew Klingensmith <notifications@github.com> wrote:@Blecki do we know if this has been solved?

**Comment by mklingen** [comment]
Okay I fixed this in master. Problem was twofold: 1) was checking to see if employee had "Chop" instead of "Plant". 2) Was not actually assigning the task (was only creating it).
