### ISSUE TITLE
Trading after firing all dwarves causes money to glitch 

### ISSUE THREAD

**Issue by smackety** [CompletelyFairGames/dwarfcorp#436]
I fired everyone because i was making great money just trading Mana and Gems between civs.   The next time i sold some items, my money dropped by about $50,000 and stacks of coins appeared everywhere.   I tried to sell to the next trader and my money went to -$70,000 and the game lagged out due to even more stacks of money appearing everywhere.

**Comment by mklingen** [comment]
hehe, how can you run a dwarf corportaiton with no dwarves? I will put in a check to make you straight up lose the game if you have no more dwarves.

What's going on here is when money gets distributed by traders, it goes to your employee's wallets. As a fallback if it can't find an employee wallet to put the cash in, it instead creates a bunch of coin piles with $64 dollars in them.

**Comment by mklingen** [comment]
This has been fixed. Will push it later in the week.
