### ISSUE TITLE
Time runs at warpspeed.

### ISSUE THREAD

**Issue by CaptDeathCap** [CompletelyFairGames/dwarfcorp#444]
Game time is stuck at 3x, but real time is unaffected.
Issue first happened in full screen, but persists in windowed mode.

Issue captured using OBS, uploaded to wetranfer due to 91mb file size not being supported by github.

[Click to download .flv file](https://we.tl/Cen9qqDTYh)

**Comment by com1clyf3** [comment]
File link no longer works.

@CaptDeathCap  I know this was a while ago, but happen to still have the video? If not, recollect what you did that might of triggered it to happen?

Closing for regression, but will re-open if needed.
