### ISSUE TITLE
Depth testing should be turned on for build designations.

### ISSUE THREAD

**Issue by Searthh** [CompletelyFairGames/dwarfcorp#446]
DwarfCorp Version: 641b9d9b (XNA version) / OS: Windows 10 Home 1703 / 64 bit / 8 GB RAM / Interl i5 7200U @2.50 GHz 2.70 GHz

Markers from blocks to be placed are displayed with the wrong depth, so there are bizarre looking overlaps. The blocks are all blue tiles. I tried making a staircase out of them which was a challenge considering this graphical bug. In the image, you're looking at a flat floor (1 layer of blocks).

![image](https://user-images.githubusercontent.com/32852691/32272751-ca6a1338-beff-11e7-873e-816c116b29c7.png)

**Comment by mklingen** [comment]
Okay should be an easy fix. We just forgot to turn on depth testing.

**Comment by mklingen** [comment]
Fixed and will be in the next build.
