### ISSUE TITLE
Sustainability issues/ecology.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#454]
After playing for several hours, users report seeing problems caused by unsustainable processes in the world. For example

- [x] Birds continually populate but never die. This means they will take over the whole world.
- [x] Dropped resources/money, when not gathered, remain forever. Have them disappear after a day or two.
- [x] Snow always falls but never melts. This means the world will eventually be covered completely in snow.
- [x] Trees get chopped down but never grow. This means the world is destined to become treeless.
- [x] It is possible to completely drain all the water in the world in spite of being adjacent to an ocean.

**Comment by mklingen** [comment]
resources now get destroyed after 1 (realtime) hour.

**Comment by mklingen** [comment]
snow now melts.

**Comment by com1clyf3** [comment]
Trying to drain the sea. So far, no dice.

Trees don't grow back.

@mklingen Did the bird population ever get figured out?
