### ISSUE TITLE
[Bug] Dwarfs only carry one item (Fedora 27)

### ISSUE THREAD

**Issue by koenigjaeger** [CompletelyFairGames/dwarfcorp#473]
**Specs:**
Fedora 27 [kernel: 4.13.13-300.fc27.x86_64]
Ryzen 5 1600
R9 270x [X.Org AMD Pitcairn/ 3.0 Mesa 17.2.4]
Running under Wayland display server
Game Version: 17.11.19

After ~30mins of gameplay dwarfs seem to only pick up one item at a time. In the attached save after they finish cutting down the apple trees they go to pick up wood/apples and only pick up one and then return to the storage area. 
[Attention Reaches_314.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1486442/Attention.Reaches_314.zip)

**Comment by mklingen** [comment]
Doesn't seem right... will test.

**Comment by com1clyf3** [comment]
This is still occurring. Investigating repro.

**Comment by com1clyf3** [comment]
No longer occurs.
