### ISSUE TITLE
Camera can not move when pointing straight up/down.

### ISSUE THREAD

**Issue by Solsund** [CompletelyFairGames/dwarfcorp#48]
Camera movement seems to be based on rotational angle even when not in RotationalMode.  This causes the math to fail when we are pointing straight up or down.

Right/Left movement fails completely and Forward/Backward fails when not holding Shift.

**Comment by mklingen** [comment]
Caused by incorrect up and forward vector when camera pointing exactly downward. Will fix.

**Comment by mklingen** [comment]
Fixed by PR.
