### ISSUE TITLE
floating beds and stuck dwarves

### ISSUE THREAD

**Issue by JackChance** [CompletelyFairGames/dwarfcorp#480]
Beds appear to float off of the ground by about 1 bed height. I've also had dwarves get stuck in the ceiling upon awakening. Game crashed when I attempted to dig them out, possibly unrelated.

windows 7, 64 bit, BuildID 2337072

**Comment by Timvdleur** [comment]
Hi there, after the latest update I'm having the same issue with the beds.
I've recorded a clip if you want to see the bug in action:
[https://youtu.be/qtXaHdnXKjs](url)

**Comment by mklingen** [comment]
Thanks for reporting this. Will test today.

**Comment by mklingen** [comment]
This has been fixed.
