### ISSUE TITLE
[BUG?] Out of food bonanza

### ISSUE THREAD

**Issue by Timvdleur** [CompletelyFairGames/dwarfcorp#482]
The out of food error can repeat itself crazy fast.
In the second clip it seems as if it is caused by a pathfinding error.

Short clips:
https://www.youtube.com/watch?v=qtXaHdnXKjs
https://www.youtube.com/watch?v=rwCkhZOBsAY

**Comment by mklingen** [comment]
Hmm okay. I will rate limit this so that it doesn't happen so frequently. Maybe it should only warn you once per day or so.

**Comment by mklingen** [comment]
Fixed. This is caused by dwarfs attempting to eat food that has been marked for restocking. They now eat food even if its supposed to be restocked or used for planting.
