### ISSUE TITLE
[BUG?] Telekinetic Graveyard Plundering

### ISSUE THREAD

**Issue by Timvdleur** [CompletelyFairGames/dwarfcorp#483]
Stockpiles seem to be drawing some resources from the dead.

This clip is from 2017-11-25 so I guess its from the 17.11.19 update.
https://www.youtube.com/watch?v=8uxv-lN8nVw

**Comment by mklingen** [comment]
Wow, this is definitely wrong. Graveyard is actually a kind of stockpile. It should not contain any resources, but something apparently got messed up here. Will fix.

**Comment by mklingen** [comment]
I believe this is now fixed.

**Comment by Timvdleur** [comment]
Quick fixing, its a funny bug though. If I encounter it again, I'll reopen the issue.
