### ISSUE TITLE
Dwarves would rather climb a wall slowly than a ladder quickly.

### ISSUE THREAD

**Issue by Solsund** [CompletelyFairGames/dwarfcorp#49]
My starter base is a bit off the ground and has a three voxel high ladder on the one side.  My dwarves will happily climb up the wall right next to the ladder rather than climb the ladder itself.

**Comment by mklingen** [comment]
Costs for climbing ladders and walls probably need to be tuned. I think climbing a wall costs 30x the amount of walking, while climbing a ladder costs 20x. Maybe climbing a ladder should be 1x.

**Comment by mklingen** [comment]
Fixed in my branch.
