### ISSUE TITLE
Eliminate spritebatch.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#497]
On account of it being slow, causing crashes when used in threads, etc. #201  Places it is used:

- [ ] Dwarf runner
- [ ] Minimap
- [ ] World generator
- [ ] Drawer2D
- [ ] Compositeanimation

**Comment by mklingen** [comment]
Added a try/finally around all usages of spritebatch to ensure #201 shouldn't happen. Also asserted that all spritebatch calls are on the main thread. Still haven't tracked down the root cause of #201 but this may fix it.

**Comment by mklingen** [comment]
Confirmed #201 still happening...

**Comment by com1clyf3** [comment]
@mklingen This still an issue?

**Comment by mklingen** [comment]
Yes, although at this point I'm not sure we will ever fix it. so I'm closing.
