### ISSUE TITLE
[SUG] Define stockpile use

### ISSUE THREAD

**Issue by Timvdleur** [CompletelyFairGames/dwarfcorp#499]
The fix of https://github.com/CompletelyFairGames/dwarfcorp/issues/483 gave me an idea.

Perhaps we can designate what a stockpile can be used for. Offcourse this would only be an added layer of cemplexity if the stockpiles don't share their content through instant relocation.

**Comment by com1clyf3** [comment]
Hm. Might not be a bad idea once we get to the point of designing play beyond the first few hours. Closing for regression.
