### ISSUE TITLE
Mac OSX launch problems

### ISSUE THREAD

**Issue by asciifaceman** [CompletelyFairGames/dwarfcorp#5]
I am willing to be a macOS tester for you guys, I noticed the mac builds are problematic. Really would like to see them rock. I have experience in software development professionally and know how to write bug reports and gather data. 

Most recent cross-platform build won't even launch.

Specs:
macOS 10.12.1
2.7GHz i7
16GB DDR3
SSD HDD

**Comment by mklingen** [comment]
What happened when you tried to launch it? I tested it on a macbook air recently and although it was slow it did launch.

**Comment by mklingen** [comment]
Possibly issue with permissions.  I will test this again once I have access to a mac.

**Comment by asciifaceman** [comment]
Thanks for looking into it. 

The process starts and I can see it in the top bar, and then it exits without error. Does it log to any location outside of the app? It was extracted before running as well. 

I can test any suggestions you give.

**Comment by asciifaceman** [comment]
I actually re-downloaded and this time I am getting "The application “DwarfCorp” can’t be opened." :(

**Comment by mklingen** [comment]
I just ran it successfully on another mac. I'm thinking the problem might be gatekeeper. Do you have the [gatekeeper setting ](http://apple.stackexchange.com/questions/243687/allow-applications-downloaded-from-anywhere-in-macos-sierra)enabled to let you run unsigned apps?

**Comment by mklingen** [comment]
By the way, another way to see what might be going on is to open a terminal (Finder > Applications > Terminal), then navigate to the location where DwarfCorp has been extracted (by typing cd <enter the path to the DwarfCorp.app>), and running "DwarfCorp.bin.osx" inside the app bundle. That will print error messages if there are any.

**Comment by asciifaceman** [comment]
I have to test your suggestions on my home computer but since I am stuck at work I tested locally on this laptop.

OSX El Capitan (10.11.6 - 2.2Ghz I7 16GB DDR3) and it launched without issue (gatekeeper enabled to any developer - I believe this is also set on the home laptop I mentioned above but I will test tonight and report)

**Comment by asciifaceman** [comment]
If you want something really trippy, DwarfCorp launches from CLI:

```
kazimir:Downloads ccorbett$ ./DwarfCorp.app/Contents/MacOS/DwarfCorpFNA.bin.osx
AL lib: (WW) GetProcPath: Failed to readlink /proc/self/file: No such file or directory
AL lib: (WW) alc_initconfig: Failed to initialize backend "jack"
IGLDevice: OpenGLDevice
OpenGL Device: NVIDIA GeForce GT 650M OpenGL Engine
OpenGL Driver: 2.1 NVIDIA-10.12.68 355.10.05.05b16
OpenGL Vendor: NVIDIA Corporation
MojoShader Profile: glsl120
Settings file does not exist. Using default settings.
```

however  it does not from `DwardCorp.app` on my original home laptop (the one running Sierra)

**Comment by asciifaceman** [comment]
Also once I had opened it via command line, it looks like it did some graphics card configuration and now launches via DwarfCorp.app successfully in the UI rather than CLI

**Comment by mklingen** [comment]
Thank you so much for doing this. One question: where did you extract the `.app` package to? Was it the same every time?

**Comment by asciifaceman** [comment]
It was in `~/Downloads` every time and run from that same location.

**Comment by JaapWijnen** [comment]
I can only launch the app from terminal as well. And the game crashes when I hit apply after ticking full screen in the settings.

**Comment by mklingen** [comment]
@JaapWijnen can you do me a favor and check what the resolution combobox says? If its blank, that means somehow the game has been set to an incorrect resolution, and crashes on apply as per #132

**Comment by JaapWijnen** [comment]
I don't think it was part of the resolution. I just wanted it to go full screen. Also It crashed on my again trying to change any kind of options such as key binding.

**Comment by mklingen** [comment]
#132 will cause the options screen to crash regardless of what options were changed because the resolution combobox is empty. For some reason I haven't determined yet, this occurs on OSX systems.
