### ISSUE TITLE
[BUG] Trees not  spawning in a custom world 

### ISSUE THREAD

**Issue by Reyhz** [CompletelyFairGames/dwarfcorp#501]
When spawning in a custom world i noticed that trees do not spawn, they are here, but not physically.
You can have the trees back by saving & reloading the save. But i'm still posting this so you guys are aware.
![20171214205830_1](https://user-images.githubusercontent.com/34547396/34004738-22ba1860-e112-11e7-860a-97b681486cea.jpg)

**Comment by mklingen** [comment]
Is this all the time, or just once?

**Comment by com1clyf3** [comment]
@Reyhz  Still experiencing this bug?

Closing for regression, but will reopen if we get a response.
