### ISSUE TITLE
Musket dwarves have to be right next to an opponent to start to fire.

### ISSUE THREAD

**Issue by Solsund** [CompletelyFairGames/dwarfcorp#51]
I tried to shoot down a bird with a Musket Dwarf and despite the bird flying nearly right overhead he couldn't shoot.  So I cancelled the bird attack and went to attack a Deer instead.  He had to walk all the way up to the deer so he was nearly touching it then stopped and entered a firing state.

Once he hit the deer the deer started running much faster and the dwarf continued to fire at the deer even when he was on the other side of the map.  He did eventually stop firing on his own but I do not know if he killed the deer or hit some manner of auto cancellation.

**Comment by mklingen** [comment]
Hmm, looks like ranged units are behaving improperly when given an attack order (as opposed to when they attack on seeing an enemy)
