### ISSUE TITLE
[Enhancement] Pathfinding needs improvement going in/out of caves.

### ISSUE THREAD

**Issue by Immorthar** [CompletelyFairGames/dwarfcorp#511]
![20171224120712_1](https://user-images.githubusercontent.com/34803122/34323861-ad711288-e8a6-11e7-8c1e-31860355abce.jpg)
Noticed that dwarfs that were going to place block on few layers below just took right material blocks in thier inventories and running around that highland and climbing up and down over and over again. For some problem were solved by clearing thier task-list. But for one of them it didnt help'd and i just fired him.

**Comment by Immorthar** [comment]
In thier task-lists were placing blocks.

**Comment by mklingen** [comment]
This is a known issue. Basically the pathfinding is just failing because dwarfs going from above ground to underground is actually a difficult planning problem. We're going to have to improve pathfinding to make this happen less offten.

**Comment by Immorthar** [comment]
Got it.

**Comment by mklingen** [comment]
I have improved pathfinding. This will be in the next release. Some summary of changes:

1) Fixed path following off-by-one error that was causing reverse path planning to fail.
2) Select reverse paths based on open-space heuristic, speeding up planning into caves.
3) Improve speed of reverse path planning.
4) Make dwarfs distinguish between paths that don't exist, vs. paths that take a really long time to plan. This generally speeds up a lot of pernicious or adversarial cases (like trying to plan into a small room that is completely walled off).
5) Fix bug that caused dwarfs to always fail path planning if the plan takes longer than 1 second. They now wait 60 seconds before giving up. The result is that sometimes all the creatures in the game will wait for a plan to finish, but according to my tests this is rarely more than 5 seconds.
