### ISSUE TITLE
[BUG] ale getting drunk by a dwarf doesn't get destroyed properly.

### ISSUE THREAD

**Issue by Immorthar** [CompletelyFairGames/dwarfcorp#512]
![20171224121932_1](https://user-images.githubusercontent.com/34803122/34324086-b6ba0ba2-e8af-11e7-8e7a-507b9218d9c9.jpg)
There is ale at the middle of screen, and when i make order to pick it, in picking mode when i selecting area for picking-up it becomes highlighted by box but when i releasing button it again becames not highlighted and everyone ignoring that ale.

**Comment by mklingen** [comment]
Question: was that ale being drunk by a dwarf earlier? How did the ale get there?

**Comment by Immorthar** [comment]
Yes, that ale was drunk earlier

**Comment by mklingen** [comment]
Okay, this is a bug that I thought was fixed but is not. Thanks for reporting it. I will try to reproduce the issue.

**Comment by mklingen** [comment]
Having trouble reproducing...

**Comment by com1clyf3** [comment]
Sounds like this is fixed. Closed for regression.
