### ISSUE TITLE
Anything that goes above Height limit buffer becomes bugged or untargettable.

### ISSUE THREAD

**Issue by Undeadbanana** [CompletelyFairGames/dwarfcorp#517]
I already reported this bug in Discord but going to here also.

As the title says, anything that goes above 64 height becomes bugged and untargettable.

Trees that extend past the height limit can not be chopped, you need to dig under them.
Birds that spawn at a height where they fly over the height limit, will not change elevations. They never land and can never be shot down by ranged dwarves.

**Comment by mklingen** [comment]
Oh, you already created the issue, thanks! Okay so this is just because the max height is 64, some undefined stuff starts happening at that height. Will test some of these corner cases and try to fix them. Probably everything should just consider something higher than 64 to be air.

**Comment by mklingen** [comment]
This has been fixed by clamping target positions for dwarves. Will be in the next release.
