### ISSUE TITLE
[BUG] Missing Icons in Trade Window (Ubuntu 17.10)

### ISSUE THREAD

**Issue by Escaflow** [CompletelyFairGames/dwarfcorp#519]
Icons appear to be missing and are Replaced with red Exception marks.

Seems like not all Icons are affected, i saw mostly Processed Items or Items not on the Map.

If more information is required just say.

![screenshot from 2018-01-06 19-21-44](https://user-images.githubusercontent.com/25120195/34642701-eb4f6d68-f317-11e7-82bf-736d1210d973.png)

**Comment by mklingen** [comment]
Hmm, I'm glad that we added that feature to catch this bug. Will try reproducing.

**Comment by com1clyf3** [comment]
@Escaflow Still experiencing this bug?

Closing for regression and will re-open when needed.

**Comment by Escaflow** [comment]
Looks good on Ubuntu 18.04.
