### ISSUE TITLE
Building blocks often causes game to crash due to nullable not being set.

### ISSUE THREAD

**Issue by MasterRainwater** [CompletelyFairGames/dwarfcorp#534]
https://imgur.com/9wKYmxU via @imgur

**Comment by mklingen** [comment]
Thank you for reporting this. It's actually a a very common crash (happened to a few hundred people while I was on vacation). caused by https://github.com/CompletelyFairGames/dwarfcorp/commit/e4a468de3d5a2e72d2f6bebb6d5e64130054174a

Fixed by recent commit. Fix will be in the next build.
