### ISSUE TITLE
Crafting Queuing Stops at 2 items

### ISSUE THREAD

**Issue by Sckiwi2018** [CompletelyFairGames/dwarfcorp#537]
When trying to craft items or cook food the dwarf stops after two items - regardless of whether you queue up 5, 10, 100 items.
Seems to be a new issue under the 18.02.04 Patch.

**Comment by mklingen** [comment]
Good catch will try to reproduce.

**Comment by mklingen** [comment]
Yep, I can see why. It's this line . Will fix. https://github.com/CompletelyFairGames/dwarfcorp/blob/master/DwarfCorp/DwarfCorpXNA/Scripting/TaskManagement/Tasks/CraftResourceTask.cs#L86

**Comment by mklingen** [comment]
This is fixed and will be in the next build.
