### ISSUE TITLE
FNA and the supported development platforms

### ISSUE THREAD

**Issue by ShalokShalom** [CompletelyFairGames/dwarfcorp#539]
See here: https://github.com/FNA-XNA/FNA/issues/152
How do you see this?

**Comment by Blecki** [comment]
Not sure what this has to do with us... Guy commenting there is right. Fna is definitely not windows specific. Any new project should use monogame anyway.

**Comment by ShalokShalom** [comment]
Your README tells it is Windows exclusive and I already read one of your colleagues write the same in another issue report.

So I can use Linux to compile the Linux version?

Why Monogame instead of FNA?

**Comment by ShalokShalom** [comment]
Your readme tells it is Windows specific: https://github.com/CompletelyFairGames/dwarfcorp#cross-platform-development

**Comment by ShalokShalom** [comment]
Your colleague as well: https://github.com/CompletelyFairGames/dwarfcorp/issues/140

Why Monogame instead?

**Comment by Blecki** [comment]
As far as I know, that's correct - you can only BUILD on Windows. Fna runs everywhere, however.

**Comment by mklingen** [comment]
We require the use of an XNA content project (DwarfCorpContent). As far as I know, content projects are only supported on Windows, unless something has changed with FNA. I bet that if you got the xnbs compiled on windows, you'd be able to compile the FNA version of DwarfCorp on Linux or Mac, but I have not tried.

**Comment by mklingen** [comment]
See this issue for why we can't compile content projects on Linux or Mac:

https://github.com/FNA-XNA/FNA/issues/126

**Comment by mklingen** [comment]
Updated readme to make this clearer.

**Comment by ShalokShalom** [comment]
How easy is it to change this content pipeline?
I guess there are other obvious benefits as well?
http://flibitijibibo.com/xnacontent.html
Thanks for changing :)

**Comment by Blecki** [comment]
Actually, a port to monogame - which must happen if I ever want to make my dream of a switch port a reality - would replace it.

**Comment by ShalokShalom** [comment]
Where are the benefits of Monogame in your opinion?

**Comment by Blecki** [comment]
Wouldn't need to use xna and fna. Content builds more places. Generally more maintained library. And it runs on switch.

**Comment by ShalokShalom** [comment]
Do you see any downsides on Monogame?

**Comment by Blecki** [comment]
Yeah I'd have to port it.

**Comment by mklingen** [comment]
Ethan is right that the content pipeline is bad, but we don't have the resources at the moment to dedicate to a rewrite of that pipeline. Also a Monogame port would probably be great ... if we could dedicate the time to do it.

**Comment by Blecki** [comment]
Most of the content pipeline is currently not needed anyway.

a) The engine will load png and jpg images just fine.

b) Almost everything else exists as json or plain text files.

The gap is, I believe, sound - I'm not aware of anything in place to load them if they aren't built to an xnb.

**Comment by ShalokShalom** [comment]
Well, in order to make it buildable from macOS and Linux?

**Comment by Blecki** [comment]
Load sounds directly? I dunno what else.

**Comment by ShalokShalom** [comment]
Ethan sais also that a proper developer can write something new and sane within a week.

**Comment by Blecki** [comment]
K.

**Comment by mklingen** [comment]
Biggest headache would be writing a new importer for the shaders. Primary reason I'm using FNA in the first place is that I don't trust Mojoshader.

**Comment by mklingen** [comment]
If we wanted to, we could restructure the project following something like this: https://github.com/AndrewRussellNet/FNA-Template then it would be mostly possible to build on Linux and Mac and would just require the user to install direct X SDK over Wine.

**Comment by ShalokShalom** [comment]
I guess a full rewrite to Monogame is critical, since much more work as a simple replacement of content projects? You might give this a read: https://github.com/FNA-XNA/FNA/issues/154

**Comment by Blecki** [comment]
Switch support in fna pretty much removed my desire to port to monogame.

When I tried a port a year ago, however, the monogame version blew the fna version away performance wise. Much less of an issue these days,  but still.

**Comment by mklingen** [comment]
It's something we should come back to in the future. At the moment cross platform development support is not a huge priority for me. Nor is supporting builds on any platform other than Linux, Mac and Windows PCs.

**Comment by ShalokShalom** [comment]
Well, I guess that includes there are already enough developers on board?

**Comment by mklingen** [comment]
If you or anyone else would like to contribute to the project we'd be happy to take pull requests. We might even pay you.

**Comment by ShalokShalom** [comment]
You are quite aware the the overwhelmingly amount of developers sitting on macOS and Linux based Devices?

**Comment by mklingen** [comment]
Yes obviously I'm aware many developers prefer a Linux or Mac development environment.  If you're passionate about developing on Linux, the project is open source and you're free to try to get it compiling yourself. If you share your findings I'd be glad to merge a pull request that makes this possible. 

Like I said it's something I may eventually want to do, but other priorities (like "*the game is playable and has features*") are currently higher.

**Comment by ShalokShalom** [comment]
The game is playable and has features is probably easier to reach with more developers
