### ISSUE TITLE
Make crash reporting and crash popup windows work on Linux and Mac

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#551]
Right now, when the game crashes it pops open a window telling the user what happened, and sends a crash report to Sentry. Since native windows.forms and our version of Sentry are currently only compiled for Windows, crash reporting does not work on Linux or Mac.

For sentry, we should just deploy a Mono version of the crash reporting system along with our Linux and Mac builds. For the pop-up window, we ought to find a cross platform windowing solution.

**Comment by com1clyf3** [comment]
Any update on this?

**Comment by com1clyf3** [comment]
How tough is it to implement?

If we can implement it early enough, it's probably our best shot of getting useful data on non-windows platforms before we ship.

**Comment by mklingen** [comment]
Crash reporting now works on Linux and mac.
