### ISSUE TITLE
Inform users of remaining supply space in GUI. Also bug with calculating storage of new balloon ports?

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#554]
> 23:18 - multiple balloon ports and supply areas either stopped or never did count as storage, I only found out when traders came, how do I check my spare supply space without the trade screen?

Possibly we should pop up a warning when storage space reaches maximum, and also display to the user how much storage space they have.

**Comment by mklingen** [comment]
I added a label for storage space and made it (and the money label) flash red when they get within a bad value. Still haven't been able to reproduce this "multiple balloon ports and supply areas not counting as storage" thing, and I'm not sure how that would be possible.

**Comment by com1clyf3** [comment]
Sounds like this is more or less resolved. Closed!
