### ISSUE TITLE
Fix project structure

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#56]
1. FNA solution is currently broken and unmaintained. 
2. DwarfCorpXNA, DwarfCorpFNAand DwarfCorpCore are different projects. DwarfCorpXNA/FNA only link to DwarfCorpCore. This is silly. DwarfCorpCore should be deleted entirely. DwarfCorpXNA and DwarfCorpFNA should live in the same directories as one another and share the same code.

**Comment by Blecki** [comment]
This is mostly done. Leaving it up to you to finish up fixing the FNA project as I've never used FNA.

In theory a monogame port could live along side these as well.

**Comment by mklingen** [comment]
Now this just needs the FNA project to correctly reference the right files, and needs an FNA build of gemgui.

**Comment by Blecki** [comment]
An FNA build of Gemgui exists. Unfortunately I have never worked with FNA so I have no idea how to test it.
