### ISSUE TITLE
Crashing on picking up coconut, serious unplayable lag.

### ISSUE THREAD

**Issue by eurabilis** [CompletelyFairGames/dwarfcorp#566]
Hi. I posted this on steam too. The problem I am having is my post below to steam.

Hi guys. I am using the one I compiled myself off git. I am using master branch. 18.03.18 In my save, as soon as I chop down a tree and I then go to pick up the coconuts it crashes to desktop. How can I debug this for you, what should I send you, and what is your email? Also I have a pretty beefy computer and even with only a few dwarves, after I get a small field going, mine out a little hideaway and start to enjoy the game my framerate drops considerably and it is near instantly unplayable. It really sucks because this is a great game and once I get to the part where I can enjoy it I plan on buying it. Let me know thanks. Intel i7-5930k @ 4.5 ghz (liquid cooled) 16 gb DDR4 on (its an asus X99-a motherboard, and an nvidia GTX 750 ti videocard. I tried playing with the graphics settings too.

**Comment by Blecki** [comment]
Is it all trees or specific to coconuts?

**Comment by mklingen** [comment]
If you compiled it yourself can you run it in debug mode and tell us where it crashed? Also, you can run a performance session in visual studio, which would be extremely helpful in tracking down the poor performance.

**Comment by eurabilis** [comment]
Hi guys well I just tried to pick up a mushroom and it crashed too so yeah all things. I will look up how to run it in debug mode and see what information I can get you. Blecki I am "eurabilis" remember you helped me before, I am not much of a programmer, just good with following instructions and computers in general so I compiled it myself. Anyway Ill see what I can get you guys. Thanks.

**Comment by eurabilis** [comment]
Ok bare with me. I am new to all of this including VS. I selected the startup project, and on the bar up top I made sure everything was good and clicked debug. It ran the game for me and I was in business. The problem I am having, is once in the game and I got it to crash, its a hard crash, i can ctrl alt delete but the windows even if i click the windows button and see my taskbar apps running, the screen wont show those things they don't pop up. They are unresponsive. The only way to get back to my computer is to sign out and back in but obviously that closes all programs. Did it log somewhere?

**Comment by eurabilis** [comment]
I will move onto the next thing. Performance profiler, do I want The first option, GPU usage, or the second, Performance wizard? Performance wizard asks, 1 CPU sampling (recommended) 2 instrumentation 3 .net memory allocation or 4 resource contention data. Let me know which, and where it logs and I will get you that information. Thanks guys.

**Comment by mklingen** [comment]
> Hi guys well I just tried to pick up a mushroom and it crashed too so yeah all things. I will look up how to run it in debug mode and see what information I can get you. 

Ok, sounds like we seriously broke something. Will take a look tonight.

To run the game in debug mode change the build mode from "Relese" to "Debug" (as in this image http://fordiac.sourceforge.net/ehelp/html/installation/img/VSreleaseDebug.png), and then hit "Run". Also you must be running the game in windowed mode.

> I will move onto the next thing. Performance profiler, do I want The first option, GPU usage, or the second, Performance wizard? Performance wizard asks, 1 CPU sampling (recommended) 2 instrumentation 3 .net memory allocation or 4 resource contention data. Let me know which, and where it logs and I will get you that information. Thanks guys.

Performance wizard CPU samling. Run the game as normal and get it into a state where performance is very bad (note that while performance profiling is on, the game will run slower than usual). That will generate a file called something like "DwarfCorp12345.vsp". If we could have access to that file it will be very helpful.

**Comment by mklingen** [comment]
okay #567 is almost certainly the cause of this issue (this was an automatic crash report that was generated by your computer and sent to us when you ran the game).

**Comment by eurabilis** [comment]
Ok i found another way to do it. It says it sent it to you but here it is https://imgur.com/a/P9QIo

**Comment by eurabilis** [comment]
cool! glad I could help. What else can I do?

**Comment by eurabilis** [comment]
Alright I will get a performance run going. Thank you

**Comment by eurabilis** [comment]
[debug.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1826379/debug.zip)

Here you go I hope this helps. I played, then it happened as I chopped down a bunch of trees and there were things ont he ground.

**Comment by mklingen** [comment]
Hi @eurabilis thank you so much for your help. While trying to debug the crash (#567), I've noticed something odd. The code that is in the crash does not exist with what's in our `master` code branch. Also, you are the only user to have triggered a report for this crash.  

Can you do me a favor and tell me what branch you currently have checked out from github?

**Comment by mklingen** [comment]
Your performance data will be very useful. There's nothing really obvious in there, but it gives us a few ideas for how to improve things.

**Comment by Blecki** [comment]
I'm completely unable to reproduce the pickup bug.
