### ISSUE TITLE
Null reference while dequeing voxel kill task.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#568]
https://sentry.io/cfg/dwarfcorp/issues/497663885/

```
NullReferenceException: Object reference not set to an instance of an object.
  File "C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Scripting\TaskManagement\Tasks\KillVoxelTask.cs", line 128, in OnDequeued
    Void OnDequeued(DwarfCorp.Faction)
  File "C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Scripting\TaskManagement\TaskManager.cs", line 131, in Update
    Void Update(System.Collections.Generic.List`1[DwarfCorp.CreatureAI])
  File "C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Scripting\Player\GameMaster.cs", line 471, in Update
    Void Update(DwarfCorp.DwarfGame, DwarfCorp.DwarfTime)
  File "C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\World\WorldManager.cs", line 462, in Update
    Void Update(DwarfCorp.DwarfTime)
  File "C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\PlayState.cs", line 252, in Update
    Void Update(DwarfCorp.DwarfTime)
...
(2 additional frame(s) were not displayed)

Object reference not set to an instance of an object.
```

**Comment by com1clyf3** [comment]
Got this crash while spamming cancel for tasks. Dwarves were not moving at the time (other than the infinite crafter). Seemed to want to defend, though there were no defend tasks ordered. Will create separate bug for AI behavior.


Log: [201803211152349622_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/1834051/201803211152349622_Crashlog.txt
Save: [Furnitureland_237_Autosave - Copy.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1834052/Furnitureland_237_Autosave.-.Copy.zip)
)

**Comment by com1clyf3** [comment]
Got crash while paused and trying to unselect large block of dug tasks.

Log:  [201803211212512380_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/1834136/201803211212512380_Crashlog.txt)

Save: [Furnitureland_237_Autosave.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1834139/Furnitureland_237_Autosave.zip)

Version: 9089159

**Comment by mklingen** [comment]
Happens when a kill voxel task is cancelled. Should be straightforward to reproduce/fix.

**Comment by mklingen** [comment]
Fixed. Was caused by adding a reference to `Faction` inside task manager, which was not properly saved/loaded from a file. Will close once this makes it into a release.
