### ISSUE TITLE
Text: "Combat" tutorial text refers to the economy UI in the wrong location

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#569]
![combattutorial ui description - economy button](https://user-images.githubusercontent.com/6562812/37616078-31c90dda-2b85-11e8-9a67-d29c7137251b.jpg)

Combat tutorial incorrectly refers to the economy button as being placed in the top right, when it is in the bottom right. See pic.

**Comment by com1clyf3** [comment]
Version: 13a3b20d
Win10

**Comment by mklingen** [comment]
Fixed all the tutorial text.
