### ISSUE TITLE
AI / Tutorial: Single right click dwarf pathing doesn't work

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#572]
The tutorial details the player must left click the dwarf and then right-click the destination. However this does not work. The dwarf will only move if the right click is double clicked or otherwise spammed.

**Comment by com1clyf3** [comment]
Version: 13a3b20d

**Comment by mklingen** [comment]
unable to reproduce. Possible that it's been fixed already. will get you a newer build shortly.

**Comment by com1clyf3** [comment]
Fixed in Version: 90891593
