### ISSUE TITLE
Settings: Terrain Draw Distance on low does not spawn out surrounding sprites

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#573]
![image](https://user-images.githubusercontent.com/6562812/37621543-9d5c8a58-2b95-11e8-8a25-bf7b1e5b0365.png)
See pic.

Go to settings, graphics, then turn Terrain Draw Distance way down. Observe that the surrounding trees and other sprites are rendered, despite no terrain beneath them.

**Comment by com1clyf3** [comment]
Version: 13a3b20d

**Comment by mklingen** [comment]
@Blecki sounds like this is something you could try

**Comment by mklingen** [comment]
@com1clyf3 can you confirm this still happens? Did you make sure to move the camera after applying the settings?

**Comment by com1clyf3** [comment]
This works now. Closing.
