### ISSUE TITLE
Map: home button does not center camera on home

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#575]
Angle camera to top-down.
Move camera some distance from home.
Press home button on mp UI.
Observe the area found by camera is not the populated area. Usually it is an unpopulated area next to home.

Version: 90891593

**Comment by mklingen** [comment]
okay, problem was that the home position wasn't getting saved in a save file. I have made it recompute this every time. I have also fixed the slicing so that if you're underground the home button works.
