### ISSUE TITLE
Trade: Add ability to clear trade

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#577]
The player can only clear a proposed trade by clicking individual items they've submitted over and over. The alternative to this is canceling out of the trade menu and then re-opening the tab menu. These current solutions are either repetitive, non-intuitive, or take too much time.

Add an ability in trade menu to clear your trade without exiting trade menu.

Version: 90891593

**Comment by mklingen** [comment]
This has been added to the next release.
