### ISSUE TITLE
Trade: Add ability to make multiple trades without exiting trade menu

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#578]
Since trade partners dislike some items over others, it is sometimes easiest to make multiple trades around one resource versus one large trade with multiple resources. For this reason, player may want to make multiple trades without leaving the trade menu. Currently each successful trade forces player back to conversation menu, adding an extra unneeded step for players who plan several successive trades.

Easy fix is disabling logic pushing player to conversation menu after each successful/unsuccessful trade(presuming it isn't a trade ending event) . Switch the cancel button to a "leave" or "exit trade" button.

Version: 90891593

**Comment by com1clyf3** [comment]
Plan to implement this  @mklingen ?

**Comment by mklingen** [comment]
sometime, maybe.

**Comment by mklingen** [comment]
This has been implemented!
