### ISSUE TITLE
Trade: Add ability to change trade numbers through middle mouse wheel / arrow keys

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#579]
Though I don't know if this is a long term design fix, for now we need to give easier control to players to change the numbers in the trade menu.

The simplest way I can imagine is by enabling the mouse wheel to make the number go up or down with the corresponding wheel direction, and similar behavior with the arrowkeys.

Otherwise the players spend quite a long time clicking in order to get to the right numbers.

**Comment by MasterRainwater** [comment]
shift left click for 5 count, ctrl left click for all

**Comment by mklingen** [comment]
its now possible to use the arrow keys to control the money editor.

**Comment by com1clyf3** [comment]
This redesign now works happily for offering or paying money.

However, it was also supposed to be implemented into the resource trader. Player should be able to click resource, then arrow up or down the amount they want offer/to offer.

ce82ce95

**Comment by mklingen** [comment]
> However, it was also supposed to be implemented into the resource trader.

I didn't know that's what you meant. That's a bit harder to do because resources don't have focus in the gui. How is pushing arrow keys any easier or harder than clicking?

**Comment by com1clyf3** [comment]
Right now, in order to sell a high number of resources, the player must click the resource repeatedly. This takes a good while, especially if you're selling 30/50/100/ or whatever high number of anything. Holding the arrow key means less repetitive action and that we can speed up the player reaching these higher ranges. Arrow keys also give a quicker feedback to the player, which means it heightens the possibility they'll actually "play" with trade. The more difficult something is, the more the player will treat it as a necessary logistic, even if they technically are rewarded with imaginary monies.

**Comment by mklingen** [comment]
You can move +5, +10 or +100 items using CTRL click, shift click and alt click. I will make it so that holding down click on the resource increases its value.

**Comment by mklingen** [comment]
In master you can now additionally hold down the mouse to make items move from one column to the other. Added bonus would be the ability to right click to move the items in the opposite direction but this is not implemented yet.

**Comment by com1clyf3** [comment]
Presuming you're still planning to implement right. Keeping open for regression.

**Comment by com1clyf3** [comment]
Going to close this for regression. I presume any UI updates will come from our current design push.
