### ISSUE TITLE
AI: Crafter stuck in infinite loop with Stock, Gather, and Hunger

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#580]
Vid: https://drive.google.com/open?id=1gVE26oW-Ab_LunHHpuNw4KNrAWq56trt
Save: [Furnitureland_237_Autosave - Copy.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1833941/Furnitureland_237_Autosave.-.Copy.zip)

As seen in vid, go down mine shaft to observe Crafter stuck in infinite loop. Seems unable to end stock task for mushroom.

Version: 90891593

**Comment by mklingen** [comment]
This has been fixed in my latest commit. Will close this once I get it into a release.
