### ISSUE TITLE
Lava is Z-fighting

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#582]
Repro 3/3:
Start a game (advanced). 
Start colony near an area with a volcano.
Move camera to view lava. 
Observe lava z-fighting. 

Vid: https://drive.google.com/open?id=154Fu-Qnb_C70n5mAPDk0WSx0Tt-W6Dgq

Version: 90891593

**Comment by mklingen** [comment]
Turns out this is happening to both water and lava. Fixed in master.
