### ISSUE TITLE
Lag when guard is enabled

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#583]
Repro 10/10:
Start any game.
Press F10.
Select the guard feature.
Observe FPS and overall performance go down. 

On my PC (low-mid performance machine): It went from 25 FPS to 1-2 FPS.

Version: 90891593

**Comment by mklingen** [comment]
Currently cannot reproduce. I suppose my machine is too fast. I get 10 ms update times with or without guarding, 60 FPS the whole time. Deserves a more detailed analysis, maybe I can provide you with a performance profiler.

**Comment by com1clyf3** [comment]
Sure. What would you suggest?

**Comment by mklingen** [comment]
once we're able to get you compiling the game in Visual Studio, you can use the performance profiler there. Also, by pressing F10 and getting a screenshot of the difference between not-guarding and guarding you can give us some valuable info on what might be slowing things down.

**Comment by com1clyf3** [comment]
Hey. So i've given Codetracker a try, cus why not? Here's data for pretty much a game start. The bump is right after I choose an area to guard, although there are currently no baddies heading to the area.

Here's where to get Codetracker: http://www.getcodetrack.com/index.html

And here's the actual data to read: [db0ebde683bc4575bb6f5df1a7c089ca.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1857348/db0ebde683bc4575bb6f5df1a7c089ca.zip)

**Comment by mklingen** [comment]
very interesting, I will take a look.

**Comment by mklingen** [comment]
Can you do a favor for me and when this happens (or before), go to "Marks" on the bottom left and turn off "Guard"? I want to understand if its just the rendering of boxes that's slowing you down or the dwarf AI.

**Comment by mklingen** [comment]
I believe this is due to drawing, not AI. I have a fix in `master` which should make this faster.

**Comment by com1clyf3** [comment]
Cool. I'll try it out today. If it doesn't seem to have worked, I'll try your Marks test.

**Comment by com1clyf3** [comment]
Good news! It looks like the fix has cut the performance hit in at least half, if not more. There's no noticeable lag when guard select and/or deselect is performed on pause. It's noticeable, but not terrible, when performed unpaused, and the lag is much shorter than in the past. The lag happens mainly at the start of the command (when using the selector, generating preview art, etc) and then vanishes. Before it continued throughout the time Guard was in use.

**Went and tried out the marks test.** Disabling marks looks like it's gotten rid of pretty much all noticeable lag. So looks like whatever issues are left are still hiding in rendering like you expected.

**A fix likely created this new bug** 
This bug only happens on uneven terrain.:

![image](https://user-images.githubusercontent.com/6562812/39143259-5e282b4a-46fb-11e8-9758-8287b32a3f84.png)

Here's some profiling:
[DwarfCorp180423 - Guard_CallerCalleeSummary.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1939517/DwarfCorp180423.-.Guard_CallerCalleeSummary.zip)

cf2d71db

**Comment by com1clyf3** [comment]
Good news is that selecting a space that's as large as a balloon port is now completely smooth.

Choosing larger issues still causes lag, though momentary, including jumping down to 0 for a second or two. But then goes back to normal. 

It's a good enough for now performance increase, given we plan to redesign fighting anyway. So I'm going to close this for now.
