### ISSUE TITLE
Redesign of skip to day feature

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#584]
Currently skipping to day is a pop-up which blocks the player screens and prevents them from playing. Some players will use the night time as a natural planning period, and will likely not want to be bothered during this time. Either way, we don't want to obstruct play. We should add a button as part of the UI, enabled during the night period (could look like a little sun with a glowing effect), next to the pause and fast forward buttons

Instead of a pop-up that disables play, a notification from the event dwarf (green visor guy) will allow player to keep playing while being informed of the skip forward feature. They should be able to click this notification to enable skip forward. The notification should stay up for at least a minute. Then come on again once more when night is half over. After this the player will be close enough where it would be just as easy to fast forward to day themselves, and ff notification will be unneeded.

Version: 90891593

**Comment by mklingen** [comment]
I agree. Trading should also be redesigned in a similar way, with traders sitting around at the trade port until you click a button that says "trade" or something similar.

**Comment by com1clyf3** [comment]
Cool. Just created issues for trade and war in this situation. Quick design fixes for now. #601 & #602

**Comment by mklingen** [comment]
Done.
