### ISSUE TITLE
Build: No way to cancel / destroy a planned object

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#585]
Pick an object to build.
Place it.
Decide to not want it anymore.
Pause or quickly choose "destroy" and click planned object.
Observe this feature does not work as expected.

This is important for misclicks and players with low resources. Destroy should work as well as the right click and select area in red feature in order to cancel build task before it's been built.

Version: 90891593

**Comment by mklingen** [comment]
Currently build orders can be cancelled by right clicking with the build tool active.

**Comment by com1clyf3** [comment]
They can? I'm not getting that behavior from right click.

**Comment by mklingen** [comment]
Hmm, could be broken. Will check. In general anything created by a tool can also be cancelled by right clicking with that same tool active.

**Comment by MasterRainwater** [comment]
its happening to me too, it cause my builders to do the standing bug again.

**Comment by mklingen** [comment]
Okay, cancelling build orders was broken by the last build. I have fixed it. Will be in the next release.
