### ISSUE TITLE
Stockpiles not being build

### ISSUE THREAD

**Issue by Timvdleur** [CompletelyFairGames/dwarfcorp#588]
Hi there,

It appears that stockpiles aren't being build anymore. Not even when all other tasks have been completed. I've tested this in 2 different newly generated worlds.
One of which I've uploaded to youtube, so you can see what the issue is.
https://youtu.be/9MLM21t9VzQ

Good luck fixing.

**Comment by mklingen** [comment]
*facepalm* sorry, a typo I added just before release broke this. Will push a hotfix right now.

**Comment by mklingen** [comment]
Fixed.
