### ISSUE TITLE
Trade: Unable to offer trade number using decimal points

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#593]
1. Trade with an envoy.
2. Type in a sell price with a decimal point (ie 19.90)
3. Propose trade.
4. Observe proposals using decimal point values do not work.

Version: 478be122

**Comment by mklingen** [comment]
can you clarify what you mean by "does not work?"

**Comment by com1clyf3** [comment]
Nothing will happen after pressing "propose trade". It will just remain on the trade ledger menu like you've done nothing.

**Comment by mklingen** [comment]
Interesting, okay. I will try it out.

**Comment by mklingen** [comment]
Oh. This is caused by the text fields not limiting typing to integers like it should. It actually expects a whole number. Will fix.

**Comment by mklingen** [comment]
Fixed in master. Awaiting release.
