### ISSUE TITLE
Plant: Communicate or toss seed limit for planting

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#594]
While planting something in tilled soil, currently the number of farm tiles will limit itself. There is nothing communicating to the player what decides this.

Is there any pro to limiting player's ability to farm? If not, I say we get rid of seed limitations for planting.

If there's a reason for it, I would suggest a few things related to UI:
1) The planting selector should change from green to a different color, probably red or yellow, when it has reached its limits.
2) Somewhere near the mouse a representation of how many seeds are left should appear. Either a percentage, a fraction (ie 5/50 seeds), or maybe something like a radial: http://www.boostinspiration.com/wp-content/uploads/2014/12/radial-ui-designs-02.jpg
3) Lastly, the resource being used should highlight itself in the resource display at the top of the screen.

Version 478be122

**Comment by mklingen** [comment]
You're right. We should not limit the planting based on number of seeds. We can and probably should implement both (2) and (3) anyway for all kinds of stuff, including building walls/floors.

**Comment by com1clyf3** [comment]
Yup. I'll probably work on that in a few weeks for larger redesign things, but the issue in using this is readily apparent, so thought it buggable,

**Comment by Blecki** [comment]
I wasn't aware there was a limit. I'll be redesigning how farms are handled
anyway, I don't see any reason to limit it.

As for feedback - with the new task design, there's no need to prevent the
player from queuing up plant tasks if they are out of seeds. They'll get
done when seeds become available.

**Comment by Blecki** [comment]
Confirmed there's nothing built into farming that stops the player from farming as much as they want. Were you talking about the UI for selecting what to plant?

**Comment by mklingen** [comment]
@Blecki  this line https://github.com/CompletelyFairGames/dwarfcorp/blob/master/DwarfCorp/DwarfCorpXNA/Scripting/Player/Tools/PlantTool.cs#L54

**Comment by com1clyf3** [comment]
Seed limit returned in aea37e74

**Comment by com1clyf3** [comment]
Fixed on 126d7ff8. Closing.

**Comment by com1clyf3** [comment]
I'm wrong.

![image](https://user-images.githubusercontent.com/6562812/39779657-e20627ae-52d7-11e8-84b3-404247982eaa.png)

The planting is limited again. The player can select as many tiles as they want despite seed resource, however dwarves will only plant however many seeds they have. After which, they'll no longer move or perform any tasks assigned to them.

Is the resource using by design? I thought we agreed they had unlimited seed resource once they had some of the resource.

Save:
[Flower Islands_41_131702827113674318.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1985450/Flower.Islands_41_131702827113674318.zip)


World:
[Flower Islands.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1985449/Flower.Islands.zip)


126d7ff8

**Comment by mklingen** [comment]
> The player can select as many tiles as they want despite seed resource, however dwarves will only plant however many seeds they have.

Ok, that's correct behavior.

> After which, they'll no longer move or perform any tasks assigned to them.

That, however is a bug.

> Is the resource using by design? I thought we agreed they had unlimited seed resource once they had some of the resource

Absolutely. When had we agreed to that?

**Comment by com1clyf3** [comment]
I think it might've got translated out of "unlimited planting".

**Comment by Blecki** [comment]
Oh. I never understood that to mean they didn't cost resources. Obviously,
doing so would break the game's economy on a fundamental level.

I interpreted it to mean that we shouldn't stop the player queuing up plant
tasks if they are out of seeds, and that's what I implemented.

**Comment by mklingen** [comment]
However, this issue should remain open as there is a bug that causes dwarves not to move when they have been assigned planting tasks and don't have seeds.

**Comment by mklingen** [comment]
Fixed dwarves standing around while not having enough seeds.
