### ISSUE TITLE
Planting dwarves will freeze if ordered to wrangle when paused

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#596]
1. Till some soil.
2. Plant some stuff.
3. Find an innocent animal.
4. Pause game.
5. Select animal to wrangle.
6. Unpause game.
7. Observe planting dwarves are no longer moving. See save.

Possibly related behavior has been observed with tasks made while paused in previous builds.

Save: [Shameia_49_131666628412253084.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1853996/Shameia_49_131666628412253084.zip)

Version: 478be122

**Comment by mklingen** [comment]
Does this only occur when paused, or do dwarves freeze when told to wrangle even if the game is not paused?

**Comment by com1clyf3** [comment]
Appears to only happen when paused.

**Comment by mklingen** [comment]
Can't reproduce. I think @Blecki fixed this by refactoring planting.
