### ISSUE TITLE
Cancelling builds while in progress does not refund resources

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#598]
Tell a dwarf to build a piece of furniture, then as they're working on it, right-click the ghost image to cancel.

**Comment by Blecki** [comment]
Claiming this for myself.

**Comment by Blecki** [comment]
Complete in blecki-dev. Note this does not apply to voxel build orders because the dwarf hangs onto the resources until the very end in this case.
