### ISSUE TITLE
Unpausing does not correctly restore previous game speed.

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#599]
Speed game up to 3x, pause with keyboard shortcut, then unpause - game resumes at 1x speed.

Now speed the game up to 3x speed, press escape to bring up pause/options dialog, click 'continue' - game resumes at 3x speed. Lower speed to 1x speed, pause/unpause with keyboard shortcut - game resumes at 3x speed.

**Comment by mklingen** [comment]
Fixed in master.
