### ISSUE TITLE
Trade: Redesign of event feedback and announcer

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#601]
As mentioned in #584 

Currently trade envoys are announced by our green-visored friend. The notice lasts a pretty short amount of time. Then, unless player happens to be on the correct side of the screen, player misses visually seeing the trade envoy around, so when the trade envoy pop up appears, it can feel rather random and interrupt play.

Redesign is as follows:
1) Keep notice of trade envoy from green-visored guy on the screen longer. Not sure how long it is now, but let's say at least a minute if it's not already there.
2) When envoy arrives, do not pop up trade menu.
3) Instead:
    i) A second notice will appear announcing that the envoy has arrived to your balloon port and is ready to trade. This should stick around for a minute, and clicking it should bring the player to the trade menu,
    ii) If player does not click the notice, they should be able to go to the port and see the trade envoy waiting for them. Hovering mouse over them should make the trade ready notice pop up again. Clicking on the envoy or the notice should enable trade to begin.

4) This redesign begs on balance issue: If player doesn't select to trade within a day's time, how long should the envoy stay at the balloon port? I'm not sure how the system handles multiple trade envoys, but my guess is that the rule is one per balloon port? If so, I say we allow a trade envoy to stick around indefinitely for now, and return to the question of balance once design direction for trading has been a little more thought out.

Version 478be122

**Comment by com1clyf3** [comment]
Related to #602

**Comment by mklingen** [comment]
In progress.

**Comment by mklingen** [comment]
Done.
