### ISSUE TITLE
War: Redesign of event announcer

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#602]
Currently when a war party arrives, the player is given only a brief amount of time to learn so, and it is easy to miss.

Immediate fix for now is keeping the notice on the screen longer, at least a minute. Later we'll need to polish this further, but for now this will do.

Version: 478be122

**Comment by com1clyf3** [comment]
Related to #601

**Comment by mklingen** [comment]
Done
