### ISSUE TITLE
Null reference while spawning colony in previous world

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#604]
Log: [201803281522010043_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/1857419/201803281522010043_Crashlog.txt)

Reproduceable bug:

1. Start new game advanced
2. Load previous world:  [Shameia.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1857432/Shameia.zip)
3. I selected spot near some lava, but not on the lava.
4. Selected Start Game
5. Loading screen
6. Crashed to crash report.

Might be able to do it with any previous world. Doesn't have anything to do with lava, just how it happened the first time.

**Comment by com1clyf3** [comment]
Version: 478be122

**Comment by mklingen** [comment]
Very interesting, this is actually the same bug as #526 , which is currently the most common crash, but I've been unable to reproduce it until now.

**Comment by com1clyf3** [comment]
I'll close this one, and just comment on the original then.
