### ISSUE TITLE
Dig: Dwarves don't cancel digging bedrock

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#605]
If bedrock is selected with dig, dwarves will dig at it forever, instead of giving up and choosing a new task

Version 478be122

**Comment by mklingen** [comment]
Nice. @Blecki do you want to cover this? It would just involve putting a check in KillVoxelTask which makes mining bedrock illegal.

**Comment by Blecki** [comment]
Got it.

**Comment by Blecki** [comment]
It is now impossible to order dwarves to mine invincible voxels.
