### ISSUE TITLE
Dig: Dwarves try to dig underwater

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#606]
Dwarves shouldn't be able to dig underwater blocks, however they try and willingly drown themselves to death.

Also apparently ocean floor blocks should be undiggable.

Version 478be122

**Comment by mklingen** [comment]
We can tackle this either by making the dwarves refuse to go to blocks that are underwater, or by disallowing mining from blocks that are underwater. Not sure which is the right choice.

**Comment by mklingen** [comment]
I have fixed this in master by making dwarf AI consider blocks that don't have a free cell nearby with half a block of water or less "completely surrounded", and they do not even attempt to path plan to them or take mining tasks.
