### ISSUE TITLE
World Generation: Same seed differs pretty wildly between medium and low world size

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#607]
Might just be point of view, but feels like there are two different worlds being used for regeneration based on size. Medium to very high appears to be one world map. Low to very low appears to be a second world map. See pics. Note that, if it's part of the same map, its orientation (based on the ocean) appears to be flipped.

I don't think this specific seed matters for repro, but it's included in repro below just in case.

Medium: 
![image](https://user-images.githubusercontent.com/6562812/38054632-867c4546-32a5-11e8-8431-0c241ccf6e2b.png)

Low: 
![image](https://user-images.githubusercontent.com/6562812/38054657-96e1e94a-32a5-11e8-960f-1f71ef26e173.png)

Repro:

1)Start advanced game
2) Generate world (ie Sea of Guitar)
3) In advanced settings, switch world size to low
4) Switch between all world size settings and observe the difference between worlds at medium and above and worlds at low and below

Version 478be122

**Comment by mklingen** [comment]
Yep, both the seed and the settings have to be exactly the same to get the same world. Not a bug.

**Comment by com1clyf3** [comment]
Okay. But all maps from medium to very high are very clearly from the same land mass if you try it out in the generator. They all have the same shape. 

When you switch to low (and very low), this shape goes away entirely and the map orientation changes.

If the settings need to be exactly right, then why can I get similar worlds on world sizes from very high to medium?

**Comment by mklingen** [comment]
So  I think its a matter of interpreting what's meant by "seed". In the programming sense a "seed" is just a number that the random number generator starts from. There are a lot of steps in the map generation process which iterate through each cell and compute a new random value. So if the map is larger, there are more random numbers generated than before, and so the random stuff that gets generated is going to be different.

To get what you want would require us to switch to a different random generation process for some of the attributes of the map. There exist random processes that vary smoothly with scale (like Perlin noise). For height, temperature, etc. this is already done. For rain, erosion, faults, etc. we just use white noise which will differ depending on scale. We could switch to a Perlin noise model for those processes and maybe keep the map the same as you vary its size.

**Comment by com1clyf3** [comment]
Might be worth it. Do you think it would take long to implement?

**Comment by mklingen** [comment]
A bit of time, but I'd put it at a low priority right now.
