### ISSUE TITLE
Dwarves walk on water

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#608]
Dwarves walk/stand on water.  I think this has to do wit generating a colony in a map where everything is water. Maybe it's just playing the wrong anim?

On second thought, I guess this begs a design question, should player be able to spawn in a map with only water? Pretty much game breaking unless we add in some kind of contingency code that throws in some specially generated ground blocks or something. Unless we're willing to work towards this possibly convoluted solution, we should probably not allow this for now.

1. Load save. / Spawn colony in middle of ocean.
2. Select dwarves.
3. Command them to move somewhere out in the ocean. 
4. Observe Dwarves walking on water like it aint even cool

Save: [King Rilome's County_795_131667450672405678.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1857792/King.Rilome.s.County_795_131667450672405678.zip)

Version 478be122

**Comment by mklingen** [comment]
What? This should definitely not be happening!? They should be swimming in the water.

**Comment by com1clyf3** [comment]
Yup. The design question is asking whether player should be able to spawn in a map where there is nothing but water, which is basically game breaking.

**Comment by com1clyf3** [comment]
I agree.

**Comment by mklingen** [comment]
I can't reproduce. However I did notice dwarves swim a little higher than usual and maybe that looks like walking? I made them swim a little lower in the water to make it clearer that they're swimming.

**Comment by mklingen** [comment]
lol oh! That's not water! That's *ice*. You've spawned on an ice cap!
