### ISSUE TITLE
Art: Shadow/light on water voxels seen near end of land's shore

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#609]
After the shallow shore enters the ocean, the water has re-occurring walls of light/shadow effects on large blocks of water. Save shows it well enough, but it's probably noticeable with any colony founded on a shore that's close to an ocean's start.

1. Load save.
2. Zoom out camera.
3. Navigate to map edges and observe these light/shadow artifacts in the ocean.

Save: [King Roddav's City_562_131667462871033593.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1857848/King.Roddav.s.City_562_131667462871033593.zip)

Pic: ![shelf](https://user-images.githubusercontent.com/6562812/38057545-d0911140-32ad-11e8-91fc-a6265aa138a8.png)

Version 478be122

**Comment by mklingen** [comment]
Fixed in master.
