### ISSUE TITLE
Objects: Doors open on the hinged / wrong side

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#612]
Doors open from their hinges instead of from the handle sides. Both sides affected for wooden doors, and iron doors. Likely affecting all doors.

1. Build a door
2. Select a task behind the door
3. Observe door opens incorrectly from its hinged side, instead of the handle's side

Left hinge: 
[Cliffs_3249_692_131668272048646026.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1861770/Cliffs_3249_692_131668272048646026.zip)

Right hinge: 
[Cliffs_3249_692_131668278047721310.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1861803/Cliffs_3249_692_131668278047721310.zip)

Version 478be122

**Comment by mklingen** [comment]
Fixed in master.
