### ISSUE TITLE
Trade: After first trade, announcer will always say player earned one dwarfbux

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#615]
Despite the actual amount earned during player's first trade, the announcer will always announce one amount earned after ending a trade event. For some reason the amount is always one dwarfbux. Note: This announcement only occurs for first trade event.

1. Enter first trade event.
2. Earn more than one dwarfbux through trade.
3. Observe announcement states player only earned a single dwarfbux.

Pic: ![image](https://user-images.githubusercontent.com/6562812/38121928-29ef12da-33a0-11e8-9107-30593dd9c620.png)

Version 478be122

**Comment by com1clyf3** [comment]
Actually: Noticing that after my first trade envoy, I'm not getting the earned message at all. Is that a bug or by design?

**Comment by com1clyf3** [comment]
Regressing last few things. @mklingen This ever get investigated?

**Comment by mklingen** [comment]
No. Is this a bug?

**Comment by mklingen** [comment]
Oh, that's not a bug. The announcement is an achievement for trading. On the first trade, you get $1 as an achievement.

**Comment by mklingen** [comment]
I think so, @Blecki ?

**Comment by Blecki** [comment]
Yes it's an achievement. It'll appear in the completed goal list.

**Comment by com1clyf3** [comment]
We should at least get rid of the announcement for now. It currently reads like you made a trade for X amount of dwarfbux (almost always more than 1), but the game has only given you one dwarfbux for some reason.
