### ISSUE TITLE
Objects: Can't build ladder adjacent to another ladder

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#616]
Player unable to build ladder adjacent to another ladder.

1. Build ladder in a square space
2. Build / plan to build a ladder in an adjacent place
3. Observe that the player can't build ladders adjacent to one another

Pic: ![image](https://user-images.githubusercontent.com/6562812/38122460-1cce320e-33a3-11e8-86d1-7d9230c9cff8.png)

Version 478be122

**Comment by mklingen** [comment]
This is the expected behavior. The ladder occupies the entire square.

**Comment by com1clyf3** [comment]
That makes sense in voxel logic, but in the visual, for a player, there's clearly enough space for a ladder there, and there isn't an clear reason why it couldn't be built there.

Maybe we could art a little tiny arm or bolt or something for adjacent cubes to communicate the ladder occupies more than a single side of the space?

**Comment by mklingen** [comment]
hmm interesting point. I will think about this.

**Comment by com1clyf3** [comment]
I definitely think we should try for the technical fix first. More building power player has, the better.

But if we can't crack it and want to take the art route, here are two simple fixes that feel pretty natural:
1. Extended wall brackets will make the  ladder take up more of the voxel space.. Like this: https://steelmastersnyc.com/wp-content/uploads/2013/05/77RoofAccessLadder.jpg

2. Or, I think this would be harder to art, we could add hand rails, like these: http://www.industrialmaintenanceplatforms.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/u/_/u_design_supported_20in_cantilever_ladder_5_step.jpg

**Comment by Blecki** [comment]
Technical fix is actually pretty simple. Just change the ladder's bounding box so that they can fit next to each other.

**Comment by com1clyf3** [comment]
Cool. Let's do that then!

**Comment by Blecki** [comment]
Done on blecki-dev.
