### ISSUE TITLE
Dwarf behavior when pathfinding fails is still bad.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#617]
See save. Two dwarves are unable to path up a hole to get paid. 

One only wants to get paid, and just can't climb up for some reason. The ladders are newly built and possibly are messing with its pathing? There was also a manna mined that they were wanting to pick up, and it's possibly in an unpathable position, though I canceled the pickup and bug persisted

The other is having priority problems between payment, hunger, and sleep. It'll die of starvation. It also cannot path up to get paid.

Could be related to #259 & #24 

Pic: ![image](https://user-images.githubusercontent.com/6562812/38123011-c8fde6c0-33a6-11e8-9062-971f93b6e138.png)

Save: [King Dag's Island_850_131668529937210769.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1862568/King.Dag.s.Island_850_131668529937210769.zip)

Version 478be122

STEAM:
https://steamcommunity.com/app/252390/discussions/0/1499000547490926002/

**Comment by com1clyf3** [comment]
I've found another stuck between sleep and pay: 
![image](https://user-images.githubusercontent.com/6562812/38123886-d6ba1874-33ab-11e8-8cef-32624befe08b.png)

This one looks like it's mainly suffering from finding the correct path. Looks like it's trying to go up to the the treasury, but instead of going to the open mineshaft, it's climbing a  few levels of cave that happen to be surface level, though not accessible.

Save:[King Dag's Island_850_131668553847265411.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1862625/King.Dag.s.Island_850_131668553847265411.zip)

**Comment by com1clyf3** [comment]
Actually, discovering many of these now. They seem to wander to the end of natural caves and then want to escape from the end of the cave instead of returning the way they came from.

**Comment by com1clyf3** [comment]
More:
According to debug, some of these are correctly pathing to paid, but can't make it. Might be stuck due to nearby above head space? A lot of these seem to think climbing above where their task is will do the trick.

Pic: 
![image](https://user-images.githubusercontent.com/6562812/38125737-98a52db8-33b9-11e8-82b5-c5954ebac7da.png)

Save:
[King Dag's Island_850_131668612184050530.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1862751/King.Dag.s.Island_850_131668612184050530.zip)


Gonna stop reporting these for now, since there's more than enough info in this issue now.

**Comment by mklingen** [comment]
This is the expected behavior. They're trying to pathfind their way out of the cave and failing. The red line that's being drawn is their target. When they're in this mode, the pathfiding is simply failing and the dwarves are lost.

**Comment by com1clyf3** [comment]
Yup. Figured that out by the end, though I figured getting paid is relevant too. Their pathing was healthy up until their pay task, as far as I can tell.

**Comment by mklingen** [comment]
Okay, we've been discussing this on the slack. Path planning going from underground to above ground is still a difficult thing for dwarfs to do, and when they fail their behavior is not clear to the player. We will have to have another round of algorithm development on this front.

**Comment by com1clyf3** [comment]
Regressing pt. 2: 

This is still an issue. Here's a fun save, if you want somewhere to start:

Save: 
[Sea of Cushion_25_131702223654525778.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1982109/Sea.of.Cushion_25_131702223654525778.zip)

World:
[Sea of Cushion.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1982110/Sea.of.Cushion.zip)

126d7ff8

**Comment by mklingen** [comment]
@com1clyf3 thanks for the save, turns out that's not a path planning issue but a bug with planting task assignment when there are insufficient seeds. fix for #594 fixes this save as well.

**Comment by com1clyf3** [comment]
We've definitely  improved this enough to close.
