### ISSUE TITLE
Pickup: Items have fallen into hole in the bedrock

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#618]
Not sure how it happened

Items rest in a hole in the bedrock. Hole leads out of world, though nothing is falling through.

See #617 for save.

Pic: ![image](https://user-images.githubusercontent.com/6562812/38123644-34b40cfc-33aa-11e8-894f-58e76c79df50.png)

Version 478be122

**Comment by mklingen** [comment]
It shouldn't be possible for there to be a hole in bedrock. My guess is that we're spawning ore in the bedrock (so that seems to be the real bug). Will fix.

**Comment by mklingen** [comment]
Fixed in master.
