### ISSUE TITLE
Objects: No preview art for lamps

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#619]
When player hovers cursor to select where to build lamp, there's no preview art.

1. Select build > objects > lamp
2. Hover cursor above an area you want to build lamp
3. Observe that the preview art is missing until an build task is selected

IF R is clicked, the preview art will flicker into view momentarily.

Version 478be122

**Comment by mklingen** [comment]
Fixed in master.
