### ISSUE TITLE
Floating sleeping dwarf

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#623]
Dwarf fell asleep and began slowly floating up to the sky. I think it might've fallen asleep on a table. Perhaps it's a collision thing?

Pic: ![image](https://user-images.githubusercontent.com/6562812/38272547-89fc9714-3757-11e8-9063-84eef997c1f9.png)

Save: [Town Islands_370_131672589796690426.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1873132/Town.Islands_370_131672589796690426.zip)

Version d2deec04

**Comment by com1clyf3** [comment]
Happened again: 
![image](https://user-images.githubusercontent.com/6562812/39154439-202bd23a-471c-11e8-84c5-8e0706b47568.png)

All of these dwarves were down a hole, digging away, then fell asleep down there. Soon afterwards they started floating up.

Save: 
[Glittertrackeria_638_131689927459290222.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1940116/Glittertrackeria_638_131689927459290222.zip)

World: 
[Glittertrackeria.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1940118/Glittertrackeria.zip)

cf2d71db

**Comment by mklingen** [comment]
Fixed in master. Sleeping dwarves were incorrectly disabling gravity. This was to make it appear like they were sleeping on the bed.  Made it so that only dwarves on beds do this as they get constrained to the bed's surface.
