### ISSUE TITLE
Zone: Animal Pen Dissapeared

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#624]
I ordered four square animal pens to be built. Once the final fourth was built the third (where the bare square is) vanished. Soon after the ground began freezing over.

Pic: 
![image](https://user-images.githubusercontent.com/6562812/38272883-8ec30eee-3758-11e8-8fdf-abed852e3a16.png)

Save: [Town Islands_370_131672595560876881.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1873159/Town.Islands_370_131672595560876881.zip)

Version d2deec04

**Comment by mklingen** [comment]
unfortunately none of these saves work. They're in a pretty bizarre state. I think they must not have been saved with version d2deec0. Also, in the future its necessary to have the world "Town Islands" as well as the save file. This is located in the `Worlds` directory at the same level as `Saves`.

**Comment by com1clyf3** [comment]
Investigated this further, and tried all expected repros. Looks like it fixed itself at some point. My guess is when we fixed the fence bounding.

9e581f9d
