### ISSUE TITLE
AI: Planting dwarves stopped moving and have no task

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#625]
Two dwarves have stopped moving. When scrolled over using debug, it's seen that they're stuck  in a loop between planting tasks and another task.  When checking the employee menu, it reads that they have no task at all.

Canceling the nearby planting task fixes the bug.

Pic: ![image](https://user-images.githubusercontent.com/6562812/38274554-1ff876ac-375d-11e8-8979-11e98e3a9634.png)

Save: [Town Islands_370_131672614063752640.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1873266/Town.Islands_370_131672614063752640.zip)

Version d2deec04

**Comment by mklingen** [comment]
Note, this save is currently unusuable. I also don't think the git tag is right.

**Comment by com1clyf3** [comment]
Closing for regression.
