### ISSUE TITLE
Zones: Can't build object next to animal pen

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#626]
Can't build object next to animal pen. Looks like a bounding issue. Also looks like animal pen fences are not being put on the voxel edges, but somewhere in the middle. Might be the reason the dirt and the fence don't align on one of these pens.

Pic: ![image](https://user-images.githubusercontent.com/6562812/38276361-be94678a-3762-11e8-84a1-b76c7728a6d1.png)

Debug: 
![image](https://user-images.githubusercontent.com/6562812/38276430-f9bad7fe-3762-11e8-9a50-f1bea67fbff5.png)

Version d2deec04

**Comment by mklingen** [comment]
bounding boxes for the fences are too large.

**Comment by Blecki** [comment]
Shrunk fence bounding boxes. Some objects still can't be built, however, as their bounding boxes are also too large.
