### ISSUE TITLE
Minecart Rails Disappeared

### ISSUE THREAD

**Issue by Sckiwi2018** [CompletelyFairGames/dwarfcorp#629]
After saving the mine cart rails have disappeared. Save file attached. Though you can't see the rails anymore the save game picture shows where the rails were built prior to them disappearing.
[Macabreland.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1882051/Macabreland.zip)

**Comment by Blecki** [comment]
Fixed on blecki-dev, should be in master this weekend.
