### ISSUE TITLE
Load save game, quit, create new game; save game is loaded instead.

### ISSUE THREAD

**Issue by Blecki** [CompletelyFairGames/dwarfcorp#63]

**Comment by Solsund** [comment]
WorldManager.ExistingFile

I just had this happen to me a moment ago and this is where you want to look.  Loading a saved game sets this string and it's how the loading system knows to load vs create.  If it's not getting cleared it would certainly cause this issue.

**Comment by Blecki** [comment]
I think I fixed this, but I can't test as loading a save game only produces JSON errors for me right now.

**Comment by Solsund** [comment]
Seems it is fixed.  I was able to create ocean worlds after loading other types just fine.
