### ISSUE TITLE
Game froze and crashed during combat.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#631]
> Game started at 04/09/2018 : 14:53
> Failed to load texture C:\Users\kingofarabi1\AppData\Roaming\DwarfCorp\Worlds\King Dag's Island\screenshot.png: System.InvalidOperationException: An unexpected error has occurred.
>    at Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Stream stream, Int32 width, Int32 height, XnaImageOperation operation)
>    at DwarfCorp.AssetManager.LoadUnbuiltTextureFromAbsolutePath(String file) in C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\AssetManagement\AssetManager.cs:line 208Failed to load texture C:\Users\kingofarabi1\AppData\Roaming\DwarfCorp\Worlds\King Dag's Island\screenshot.png: System.InvalidOperationException: An unexpected error has occurred.
>    at Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Stream stream, Int32 width, Int32 height, XnaImageOperation operation)
>    at DwarfCorp.AssetManager.LoadUnbuiltTextureFromAbsolutePath(String file) in C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\AssetManagement\AssetManager.cs:line 208Overworld C:\Users\kingofarabi1\AppData\Roaming\DwarfCorp\Worlds\Cisaloia\world.png already exists. Just assuming it is correct.
> Overworld C:\Users\kingofarabi1\AppData\Roaming\DwarfCorp\Worlds\Cisaloia\world.png already exists. Just assuming it is correct.
> 

While guarding home balloon pad from quite a lot of enemy NPCs, I paused to hire about six dwarves to  fight them off. I unpaused the game at 3x speed. The game froze and then crashed soon afterwards.

No proper crash log was produced, but the above text was found in log.txt

World: 
[Cisaloia.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1891484/Cisaloia.zip)

Most recent save (about three minutes or so before crash): 
[Cisaloia_647_131677747637599934.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1891488/Cisaloia_647_131677747637599934.zip)

Version 37fcb4d2

**Comment by mklingen** [comment]
Crash is unrelated to the stack trace. The stack trace you see is from the loading screen apparently failing to load a screenshot. In that case it doesn't crash, just prints to the console.

**Comment by com1clyf3** [comment]
Oh. So, I guess I'll disregard that in the future then.

**Comment by mklingen** [comment]
Hmm, I can't reproduce the crash from your save file. Does it happen every time when you load this save?

**Comment by com1clyf3** [comment]
Don't think so. Want me to hunt a repro?

**Comment by mklingen** [comment]
I think that would be valuable in this case, thanks.

**Comment by com1clyf3** [comment]
Unclear bug. Closing for regression.
