### ISSUE TITLE
Trade: Dwarves want to kill trade envoy

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#632]
Pic: ![image](https://user-images.githubusercontent.com/6562812/38519191-ff7dc94a-3c0c-11e8-9a09-f5873b20cfa8.png)

A trade envoy is announced. When they arrive, Dwarves instantly selected them for fighting. Fight ensued. Meanwhile announcement for trade envoy stayed up. When selected, trade menu and conversation with envoy were opened and possible.

Save: 
[Cisaloia_647_131677771979099159.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1891542/Cisaloia_647_131677771979099159.zip)

World: 
[Cisaloia.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1891545/Cisaloia.zip)

Version 37fcb4d2

**Comment by com1clyf3** [comment]
Save is from after I ended trade, btw.

**Comment by mklingen** [comment]
How was this trade envoy triggered? Naturally or from the god menu?

**Comment by com1clyf3** [comment]
Naturally. Happened right before an attack party was spawned too. Possibly it's just hard to tell who's the attacker and who's the envoy. I suppose this is part of the reason we need the planned redesign for attacks.

**Comment by com1clyf3** [comment]
Actually this is a better save to observe it from. Right before the trade envoy arrives:
[Cisaloia_647_131677747637599934.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1891627/Cisaloia_647_131677747637599934.zip)

**Comment by mklingen** [comment]
Does this always occur with the undead?

**Comment by com1clyf3** [comment]
It does in this save. I can investigate if it's always with the undead or with all envoys if you like, though getting it to happen naturally is going to take some time.

**Comment by mklingen** [comment]
okay thank you. I think I have seen this before, and its related to the skeletons that get generated by the necromancer belonging to the wrong faction (by default skeletons are enemies of dwarves).

**Comment by mklingen** [comment]
I think I understand the problem. If it comes up again and it's *not* with the undead then that would be worth reporting.

**Comment by mklingen** [comment]
Fixed in master.
