### ISSUE TITLE
Design: Add platform brush.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#636]
When player is building with blocks, they can easily build single layers vertically using the ALT key. They can easily build solid large blocks of something by using the normal selector. What they can't do is easily build a large horizontal layer. This gets in the way of one of the first instincts a player will have when building, to put a roof on their structure. Currently roofing something includes a lot of camera back and forth, deleting misplaced blocks, and other figeting with the controls.

A few possible quick fixes:
1) Make a single layer brush that paints horizontally by default.
2) Add a hotkey command for it, like ALT. Maybe CTRL + wheel or CTRL + moving camera around.

Either of these sound good?

**Comment by com1clyf3** [comment]
Tested your method and definitely works. Seems the difficulty in discovering this came from a few little things:

1. Building on uneven surfaces. For instance, building something into sloping terrrain, if one of the pillars is shorter or higher than the other, the roof brush will turn into a block to compensate for the height difference. This becomes more likely the more nonsquare/complex polygon your building is.

2. The roof brush only works when selector hovers over another pillar. You'd think it would be intuitive, but with the preview showing you so many other options inbetween, it effectively obfuscates the viusal communication of that logic.

Technically this is also obstructing players from constructing hanging platforms. At least easily.

Not sure we need a big fix for this yet, as building is currently a tertiary mechanic, but I'd propose at least mentioning something in the Tutorial text for now.  Something like **** To build a roof, select a point and connect it to a point at the same height.

**Comment by mklingen** [comment]
Interesting okay. So the way the brush selection works right now is that it selects everything within a bounding box made by the start and endpoints of the selection in 3D. Building on pillars just happens to work because the pillars happen to be the same height.

You may have noticed there are three brushes on the bottom, "block", "shell" and "stairs". If you want I can add another brush, maybe called "platform" which builds a 2D surface with pillars.

**Comment by com1clyf3** [comment]
Yup. Noticed the brushes. We should eventually figure out a way to build them into the fancy universal selector.

Platform brush sounds like a good start. Let's do that.

**Comment by com1clyf3** [comment]
Regressing. I'm going to call this out of scope for release and close.
