### ISSUE TITLE
Camera locks after clicking on war party announcement

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#638]
After clicking an announcement about a war party arriving, the camera panned to the war party near the edge of the map. Trying to move camera afterwards reveals player is unable to budge the camera more than bit in any direction. When player zooms down to terrain, camera is then able to move.

My guess is that the camera bounding got caught in the edge map or skybox bounding somehow.

Save:
[Cisaloia_647_131678819097082523.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1896895/Cisaloia_647_131678819097082523.zip)

World:
[Cisaloia.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1896896/Cisaloia.zip)

Version ce82ce95

**Comment by mklingen** [comment]
Interesting. I think there is a bad interaction here between the "zoom to target" functionality and the constraint at the edge of the world.

**Comment by com1clyf3** [comment]
Similar bug came through Discord, but isn't solved by current work around. Might be a different bug, so I I've gotten necessary data to check it out. Haven't tried it out yet, but here it is for future investigation:

[Manifest Marsh.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1911637/Manifest.Marsh.zip)

**Comment by mklingen** [comment]
fixed in mater.

**Comment by com1clyf3** [comment]
This still occurs on 126d7ff8

**Comment by mklingen** [comment]
no way. Please provide an example.

**Comment by com1clyf3** [comment]
Caught another.

[Crimeia_849_131733882443099435.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2099408/Crimeia_849_131733882443099435.zip)
[Crimeia.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2099410/Crimeia.zip)

3eea47e7

**Comment by com1clyf3** [comment]
@mklingen Regressing. Still needs to be fixed.

**Comment by com1clyf3** [comment]
@mklingen Regressing. Still needs to be fixed?

**Comment by mklingen** [comment]
Yeah I've seen it from time to time. However, you can get out of that situation pretty trivially just by pressing shift. I can implement a hack to make it less likely to be a problem.

**Comment by com1clyf3** [comment]
I say why not? Players have reported the issue before, and it's been connected to more impactful bugs in the past.

**Comment by mklingen** [comment]
Okay. I'm going to look at fixing this today.

**Comment by mklingen** [comment]
Fixed it.

* Turned border of the world into a soft constraint, so that it gently pushes you back into the world. This gives slightly more leeway to the autozoomer.

* Made the autozoomer give up completely after 3 seconds.
