### ISSUE TITLE
Frustum culling slow

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#64]
My recent analysis of the game performance reveals we are spending 22% of every frame simply finding the entities that are within the camera frustum (FrustumCullLocatableComponents). This causes huge performance hits in dense environments like jungles. It is by far the single largest function call in the game. This should be made faster.

**Comment by Blecki** [comment]
I was able to speed this up a little - It was converting a hash set to a list, and then back into a hash set - but the underlying problem is that it appears to be checking every object against the frustrum instead of using a spacial structure, such as an octtree.

**Comment by mklingen** [comment]
Check again, it is using a spatial hash map.
