### ISSUE TITLE
Audio: Two different sounds are playing when player fires dwarf

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#641]
A new sound has found its way into the game. It often plays when dwarves die. Eitherway, it didn't present any buggable behavior until this.

1. Fire dwarf.
2. Listen to a coin jingle audio play simultaneously with this doink sound (reminds me of a windows error sound).

ce82ce95

**Comment by mklingen** [comment]
Not a bug. That's just the new much less annoying "negative generic" sound.

**Comment by mklingen** [comment]
Hmm, after firing a dwarf I was not able to reproduce. It only produces the cash register sound. Yes it happens when dwarves die, but not when they are fired.

**Comment by com1clyf3** [comment]
Hm. Weird. Must be something more unique then. I'll go hunting.
