### ISSUE TITLE
Crash on new game generation for MacOS

### ISSUE THREAD

**Issue by SirRowdy** [CompletelyFairGames/dwarfcorp#643]
Computer Specs:
2017 Macbook Pro (15 inch)
3.1 GHz Intel Core i7
16 GB 2133 MHz RAM
Radeon Pro 560 4GB RAM

When you try and load a new game, it crashes and displays the following...
<img width="1680" alt="screen shot 2018-04-13 at 8 56 42 am" src="https://user-images.githubusercontent.com/38353300/38736452-15dbb8c4-3efa-11e8-8ead-a0c4bfb34b77.png">

**Comment by mklingen** [comment]
I'm sorry, this is a change that was related to mod support which was apparently implemented totally wrong for Mac/Linux. Will fix.

**Comment by mklingen** [comment]
This has been fixed in our repository and will be in the next release (likely tomorrow night)
