### ISSUE TITLE
Creatures chase each other in water indefinitely

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#644]
Spawn some creatures which naturally hate each other (such as snakes and goblins) in a pool of water. Watch them chase each other for hours, since neither can attack in water.

**Comment by mklingen** [comment]
This was caused by fixing #606, which was fixed in a too-general way. This caused all planning within water to fail. Also it is caused by the fact that some creatures (like scorpions) just can't swim.

Fixed in master.
