### ISSUE TITLE
Dwarf remains aren't being buried in graveyard

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#645]
Think graveyards have been broken in one way or another for a while, but here's current issue:

1.  Dwarf dies.
2.  Order task to pickup dwarf bones.
3. The bones are put in the stockpile.
4. The dwarves don't bury the bones.

My suggestion is  that gathering bones should trigger then burying the bones in the graveyard, and not stopping at the stockpile (though I'm presuming this messes with the pickup task logic). Perhaps we could just automate burial and make it a single task, if so.

Don't need the below save for a repro, just copy the above steps, but save is at point after many bones have been collected.

Save: 
[Names's Wake_304_131683789602377504.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1916830/Names.s.Wake_304_131683789602377504.zip)

World: 
[Names's Wake.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1916832/Names.s.Wake.zip)

9da550cb

**Comment by mklingen** [comment]
Fixed in master.

**Comment by com1clyf3** [comment]
Issue occurs in 3eea47e7

**Comment by com1clyf3** [comment]
Although the behavior is a bit strange currently, dwarves end up buried one way or another. Closing for regression,

**Comment by com1clyf3** [comment]
Pretty sure  this was a bug we found while fixing this, so putting it here:

Dwarves are not collecting auto-corpses if a graveyard is not yet built.

0c9a7de8

**Comment by mklingen** [comment]
> Dwarves are not auto-collecting corpses if a graveyard is not yet built.

That's completely intentional to prevent dwarves from carrying around corpses in their backpacks.

**Comment by com1clyf3** [comment]
Why do we not want that again? Wouldn't it be better to auto-collect, throw in storage, and start illness spreading amongst the resources until they bury the dead?

Ignore that, unless it's easy.  But I do mean the why not just autocollect and store part? Otherwise don't they run the risk of corpse and gold despawning over time?

**Comment by mklingen** [comment]
I just thought it was weird to have dwarfs carry corpses in their backpacks. It's also weird to have them put corpses in storage. Dwarfs try to treat the bodies of their fallen comrades with respect, and if that means they can't bury the dead, they leave them on the ground until it's possible to do so.
