### ISSUE TITLE
Holding pgup/pgdn doesn't trigger quick slicing

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#646]
1. Hold down the PgUp/PgDn key.
2. Observe that no slicing happens, instead of the expected accelerated slicing.

9da550cb

**Comment by mklingen** [comment]
Unfortunately I had to remove this feature due to the new polling model introduced to fix #8

**Comment by com1clyf3** [comment]
Damn. It really ups the useability of slicing.

Any thoughts on how we could get it back or is it a lost cause?

**Comment by mklingen** [comment]
I can re-implement it. Shouldn't be that hard.

**Comment by mklingen** [comment]
Added back in `master`.
