### ISSUE TITLE
Design / GUI: Selector outline should turn red when selecting a build beyond player resources

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#648]
If building a zone, for instance an animal pen, if the player selects an area larger than the required resources, a small info text will alert them they don't have the required resources. 

However this can be easy to miss, and not as quick to read as a visual cue, so I propose making the area outline (which currently stays white) turn red (or maybe orange or yellow, so not to be confused with the deselect feature).

9e581f9d

**Comment by Blecki** [comment]
On the other hand, players should be allowed to queue up things they can't
afford yet.

**Comment by com1clyf3** [comment]
I agree. Perhaps yellow fits that better as generally understood as cautionary/in-progress. But, yeah, I agree, I don't think we should stop them from planning, just communicate the status of the planned task.

**Comment by mklingen** [comment]
okay, we can lay down the zone and put an icon on it saying it doesn't have the resources yet.

**Comment by mklingen** [comment]
Zones can now be built with insufficient resources. If you don't have enough there will be an annoying little label attached to the room telling you to gather the resources.
