### ISSUE TITLE
NoSuitableGraphicsDeviceException: Could not find a Direct3D device that supports the XNA Framework HiDef profile.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#653]
https://sentry.io/cfg/dwarfcorp/issues/358555540/

```
NoSuitableGraphicsDeviceException: Could not find a Direct3D device that supports the XNA Framework HiDef profile.

Verify that a suitable graphics device is installed.

Make sure the desktop is not locked, and that no other application is running in full screen mode.

Avoid running under Remote Desktop or as a Windows service.

Check the display properties to make sure hardware acceleration is set to Full.
  File "c:\Users\matth_000\Documents\github\dwarfcorp\DwarfCorp\DwarfCorpXNA\DwarfGame.cs", line 127, in .ctor
    Void .ctor()

Could not find a Direct3D device that supports the XNA Framework HiDef profile.

Verify that a suitable graphics device is installed.

Make sure the desktop is not locked, and that no other application is running in full screen mode.

Avoid running under Remote Desktop or as a Windows service.

Check the display properties to make sure hardware acceleration is set to Full.
```

**Comment by mklingen** [comment]
Lots of users apparently have this bug now. I think its from a recent windows 10 upgrade. What fixed it for me was reinstalling graphics drivers. Also, another user seemed to have success from reinstalling XNA #652 .

**Comment by Blecki** [comment]
These same users. Are they clicking 'no' on the deprofiler popup? The same one that tells them it may crash if they select no?

**Comment by mklingen** [comment]
@Blecki I do not know. However this is a new problem. Even I had this problem when windows 10 upgraded. Users definitely have capable graphics cards. The issue is the video drivers and/or XNA changed with the last windows 10 update.

**Comment by com1clyf3** [comment]
Regressing. Is our general plan to fix this the switch to FNA or?

**Comment by com1clyf3** [comment]
Regressing. ^

**Comment by Blecki** [comment]
The deprofiler should mean this only occurs in two cases - the card really
is unsuitable, in which case fna won't help, or if the user clicks no on
the deprofiler prompt, which just means they need to click yes.

**Comment by com1clyf3** [comment]
Hm. Alright. I'm going to close for now then. Sounds like it was mainly brought about due to the Win10 update anyhow.
