### ISSUE TITLE
A few issues with magic system I've noticed

### ISSUE THREAD

**Issue by Sydonia** [CompletelyFairGames/dwarfcorp#655]
Finally got far enough to delve into the magic system. It shows promise but here are a few things I've noticed.

- There seems to be a resource used to cast spells called Mana but there doesn't seem to be a way to see how much you have until you go to cast a spell. Not a huge issue, but perhaps something on the HUD could be added in future.

-  Every time a spell is researched the game slows to a crawl. Not sure what is going on behind the scenes but seems to need optimizing. Also the HUD does not update when a spell is researched.

- Only one wizard can research a spell at a time. Not sure if this is intended but if it is you should change the alert that tells you more have been assigned to that task when that isn't what is happening. This does allow for multiple spells to be researched at once as every wizard you have will work on a different spell if you click on multiple spells to research.

- When researching a spell the progress is in the thousands (ex. 9485% researched)

Not huge issues or bugs just a heads up.

**Comment by mklingen** [comment]
Haven't looked at or touched the magic system in any way for several months. Thanks for your input, will check it out.

**Comment by mklingen** [comment]
I'm a bit confused, because some of these issues aren't relevant in the current build (18.04.x) which version of the game are you running?

> There seems to be a resource used to cast spells called Mana but there doesn't seem to be a way to see how much you have until you go to cast a spell. Not a huge issue, but perhaps something on the HUD could be added in future.

There definitely used to be a mana bar. I don't remember why we removed it. I will add one back in.

> Every time a spell is researched the game slows to a crawl. Not sure what is going on behind the scenes but seems to need optimizing. Also the HUD does not update when a spell is researched.

?? Unable to reproduce. I agree that there should be something on the HUD to indicate how much a spell has been researched.

> Only one wizard can research a spell at a time. Not sure if this is intended but if it is you should change the alert that tells you more have been assigned to that task when that isn't what is happening. This does allow for multiple spells to be researched at once as every wizard you have will work on a different spell if you click on multiple spells to research.

There is no alert that currently comes up when wizards research spells, and wizards can definitely assist each other with spells at the moment.

> When researching a spell the progress is in the thousands (ex. 9485% researched)

??? There is nothing indicating spell research progress anywhere on the HUD. Are you running an old version of the game?

**Comment by mklingen** [comment]
Some updates in master: dwarves can now share spell research (before only one dwarf could do this). UI warns player when they don't have magic research stations, mana bar now exists in GUI. Reduced mana recharge rate to 1/10th of what it was before.

**Comment by Sydonia** [comment]
Here are some screenshots. Running build 2693591 on steam. I assume that's 18.04.16 your most recent as I verified the files using steam. Added notes in screenshots themselves. I used paint for some as it was just quicker so quality might be lessened.

2 wizards assigned notification.

![2wizards](https://user-images.githubusercontent.com/34918879/39400526-d06f10bc-4aff-11e8-94a0-10b333a66547.gif)

If they are supposed to help each other they don't. You CAN queue up spells and they will research one then another. 2 wizards will research different spells but NOT the same spell. Sorry about the number of images but it was needed in this case.

![notsharing1](https://user-images.githubusercontent.com/34918879/39400821-c3008aea-4b05-11e8-8098-7e682b8aaffa.gif)
![notsharing2](https://user-images.githubusercontent.com/34918879/39400822-c30facaa-4b05-11e8-893f-10552dc3eaab.gif)
![notsharing3](https://user-images.githubusercontent.com/34918879/39400823-c32208f0-4b05-11e8-952e-8a8ce3279ed7.gif)
![notsharing4](https://user-images.githubusercontent.com/34918879/39400824-c3302840-4b05-11e8-8e68-e6cfc0c6b07b.gif)
![notsharing5](https://user-images.githubusercontent.com/34918879/39400825-c350604c-4b05-11e8-81f7-b78b4a32b253.gif)
![notsharing6](https://user-images.githubusercontent.com/34918879/39400826-c35ed05a-4b05-11e8-98cd-e08bdd2b299c.gif)

Odd Research Numbers

![research1](https://user-images.githubusercontent.com/34918879/39400527-d07caeb6-4aff-11e8-861d-b4dc5d6cf9ba.gif)
![research2](https://user-images.githubusercontent.com/34918879/39400528-d08b1d16-4aff-11e8-938b-bfba7d937851.gif)

Spells not updating

![spellnotupdating1](https://user-images.githubusercontent.com/34918879/39400608-9173629e-4b01-11e8-856a-c3c509c23230.gif)
![spellnotupdating2](https://user-images.githubusercontent.com/34918879/39400609-918073d0-4b01-11e8-97b3-bd8cb5910415.gif)
![spellnotupdating3](https://user-images.githubusercontent.com/34918879/39400610-918f6854-4b01-11e8-8c87-80eb3e95613c.gif)
![spellnotupdating4](https://user-images.githubusercontent.com/34918879/39400611-919db080-4b01-11e8-9ea8-f7b60fc19aa9.gif)

If you have any other questions or concerns feel free to ask.

**Comment by mklingen** [comment]
Oh, so sorry I had forgotten about all those little bits of GUI. Thank you very much for this detailed report. That will help a lot.

**Comment by mklingen** [comment]
Okay, fixed updating of GUI. This will make it into tonight's release.
