### ISSUE TITLE
Art / Anim: Turrets don't face the direction they're shooting

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#658]
Pic:
![image](https://user-images.githubusercontent.com/6562812/39148256-d18644a6-4709-11e8-86e0-fd3cd21edada.png)

Arrow animations come out of the side of the bow of the turret, instead of the expected  center of the bow.

cf2d71db

**Comment by mklingen** [comment]
*sigh* I've had to fix this like 10 times already. Why do our sprite orientations keep changing?

**Comment by mklingen** [comment]
Fixed in mater.
