### ISSUE TITLE
Build: Moving stove causes bounding to sink and become unplaceable

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#659]
![image](https://user-images.githubusercontent.com/6562812/39150820-83813812-4711-11e8-98c6-43dd4f6dc3ac.png)

1. Build stove.
2. Move stove.
3. Observe stove preview art (and bounding) sink down into terrain and prevent player from placing stove.

cf2d71db

**Comment by mklingen** [comment]
Stove offset seems broken.

**Comment by mklingen** [comment]
fixed in master.
