### ISSUE TITLE
Zones: Limit balloon platforms max to one

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#661]
![image](https://user-images.githubusercontent.com/6562812/39204278-623ce21e-47c5-11e8-91a9-47d0fc1e5ff3.png)

Limit balloon ports to one. 

cf2d71d

**Comment by com1clyf3** [comment]
To add to this:  Do not allow player to destroy all zones with stockpiles. When all zones are destroyed, player may put down stockpile, which dwarf will not put resources back onto.

It's only after putting down a  balloon port that dwarves will return to stockpiling.

**Comment by mklingen** [comment]
> To add to this: Do not allow player to destroy all zones with stockpiles functions. 

Sorry, that's just not realistic. Gremlins for example will destroy zones, as will placing TNT.

> It's only after putting down a balloon port that dwarves will return to stockpiling.

What!? Will try to reproduce this because that's definitely not supposed to be happening.

**Comment by mklingen** [comment]
> To add to this: Do not allow player to destroy all zones with stockpiles functions. 

Sorry, that's just not realistic. Gremlins for example will destroy zones, as will placing TNT.

> It's only after putting down a balloon port that dwarves will return to stockpiling.

What!? Will try to reproduce this because that's definitely not supposed to be happening.

**Comment by com1clyf3** [comment]
Ah okay. Had forgotten about TNT. Let me know if you need help with the repro.

**Comment by mklingen** [comment]
added in master.
