### ISSUE TITLE
Settings: 1280x600 res causes text overflow on gameplay menu

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#662]
![image](https://user-images.githubusercontent.com/6562812/39206422-6120dd9e-47cb-11e8-8b91-6b9ab8f63981.png)

1. Go to Graphics settings
2. Change resolution to 1280x600
3. Go to Gameplay tab and observe text overflowing out of the UI

cf2d71db

**Comment by Blecki** [comment]
Fixed on blecki-dev.
