### ISSUE TITLE
Settings: 800x600 res creates text overflow on gameplay menu

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#663]
![image](https://user-images.githubusercontent.com/6562812/39207012-de16e39c-47cc-11e8-95cf-1e5642917aa1.png)

1. Set graphics resolution to 800x600
2. Go to Gameplay tab
3. Observe text overflow 

cf2d71db

**Comment by Blecki** [comment]
Fixed on blecki-dev
