### ISSUE TITLE
Settings: 1280x720 res causes save location overflow on gameplay menu

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#664]
![image](https://user-images.githubusercontent.com/6562812/39207490-17fe8b4a-47ce-11e8-84f4-a03493bbf3d4.png)

1. Set resolution to 1280x720
2. Go to Gameplay menu
3. Obverse the save location text input box is flowing out of the menu UI

cf2d71db

**Comment by Blecki** [comment]
Fixed on blecki-dev
