### ISSUE TITLE
Zones: Zoned stockpile removes corner block when zoned on top of other planned zone

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#665]
![image](https://user-images.githubusercontent.com/6562812/39209350-a1ecebb2-47d3-11e8-89d8-80d1aaa18b68.png)

1. Select and place any zone, other than Stockpile
2. Then place stockpile zone next to (only ever works on one out of the four sides, as seen in pic)
3. Observe that the selected area is missing a selected block

cf2d71db

**Comment by mklingen** [comment]
fixed in master.  problem is a literal corner case where if the first block in a zone touches another zone of a different type, a new zone is created but the first block is not added.
