### ISSUE TITLE
Zones: Destroying stockpile does not drop resources

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#667]
When player destroys a stockpile, there are no resources dropped to pickup.

1. Build stockpile.
2. Fill stockpile with some resources.
3. Destroy stockpile
4. Observe that the stockpile zone is destroyed and does not drop the resources.

40d844c8

**Comment by mklingen** [comment]
Up to as recently as last night this was working. You know it drops "piles" of resources and not all the individual ones right?

**Comment by com1clyf3** [comment]
Pretty sure, but I can retest it if you want.

What should the piles look like? It's possible they just blended in with a few surrounding resources and weren't noticeable.

**Comment by mklingen** [comment]
They look like a single instance of the resource, but when you mouse over them it will say "pile of 27 wood" or similar.

**Comment by com1clyf3** [comment]
Checked it out. You're right. It's working fine.
