### ISSUE TITLE
Redesign: Make moving and destroying objects and zones one feature

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#668]
It seems a little broken at the moment anyhow? I select "destroy", then scroll over a stockpile and nothing happens. Only if I go to zones, then stockpile, then right click over it that it destroys the zone.

We could eliminate a lot of clicks and confusion by doing a few things:
1. Making the tool bar feature represent both move and destroy. Left click for move. Right click for destroy. *I think double right click might be better, since this design will make it easier to accidentally destroy objects.

2. Make it so this feature auto detects all possible objects/zones/anything applicable in the build feature, instead of forcing player to go through three or four clocks to find the right pattern to destroy something.

Relevant to #627

**Comment by mklingen** [comment]
> It seems a little broken at the moment anyhow?

No, "destroy" only destroys objects.

> Making the tool bar feature represent both move and destroy. Left click for move. Right click for destroy. *I think double right click might be better, since this design will make it easier to accidentally destroy objects.

That's how this was before, but lots of people found it confusing, so I made an explicit move and destroy tool.

> Make it so this feature auto detects all possible objects/zones/anything applicable in the build feature, instead of forcing player to go through three or four clocks to find the right pattern to destroy something.

I agree. Problem is that at the moment tools can only select objets *or* zones, and not objects *and* zones.

**Comment by mklingen** [comment]
I should also note that #222 would help with this issue. The selector tool should be able to select objects/zones as well as dwarfs to get their properties.

**Comment by com1clyf3** [comment]
Happened with #627. Closing.
