### ISSUE TITLE
Crash: Purple screen of death appears after clicking out of game - System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#669]
I know it's probably from recent performance fixes, but figure it's best to be aware of it. I don't think we should release without fixing this. It's been occurring basically every play session that's longer than ten minutes, about nine out of ten times.

Going to hunt a bit to see if there's any more specifics for the repro, but so far it's only this:
1. Start playing game in windowed mode.
2. Get about five to ten minutes into a game.
3. Click out of the window and do something else on PC
4. Go back into game.
5. Observe purple screen of death
6. If player waits, a Window's error message will appear asking if you want to close the program or debug.

No crash log is produced.

40d844c8

**Comment by com1clyf3** [comment]
Managed to get a crash log:
[201804261241571046_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/1952149/201804261241571046_Crashlog.txt)

Looks like a render issue:

> System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'RenderTarget2D'.

**Comment by mklingen** [comment]
Ah ok, I understand what's going on. The minimap isn't getting reset properly when the graphics device is lost. Will fix.

**Comment by mklingen** [comment]
Sentry issue: [DWARFCORP-FR](https://sentry.io/cfg/dwarfcorp/issues/537361531/)

**Comment by mklingen** [comment]
Sentry issue: [DWARFCORP-FQ](https://sentry.io/cfg/dwarfcorp/issues/536867178/)

**Comment by mklingen** [comment]
The good thing is that crash reporting is still working, and it caught two issues while you were getting these crashes. That should help me fix it.

**Comment by mklingen** [comment]
Put some fixes in master for this, can you check it out at your leisure?

**Comment by com1clyf3** [comment]
No longer occurs on aea37e74

I am getting an interesting window opening pattern though.  9 out of 10 times I get this screen pop when I open the game: https://drive.google.com/open?id=1cvI4a_u2oYinj6zG1RxTB3HzWt1zWY0r

**Comment by mklingen** [comment]
can you clarify what you mean?

**Comment by com1clyf3** [comment]
In the video you should see me open the window. When the window is opened, the visual is blank, and then a second or two later, the entire game pops in. This happens everytime.

 Now that i'm testing it a little further, if you click in and out of it, you can observe that each time you do this the location on the map changes. So I suppose that's the real bug: https://drive.google.com/open?id=18XEas6OCrKoqsP-qKeDRo80aXALVP50v

**Comment by com1clyf3** [comment]
Think I figured it out. If player leads mouse to the bottom of the window and then clicks out of the game, then when they re-enter the game, the game won't register it as a click on the map. When the player leads their mouse left, right or up of the window, and then clicks back into the game, the game thinks that's a click onto the map, causing the map to move.

**Comment by com1clyf3** [comment]
Closing. I'll make this its own bug.

**Comment by mklingen** [comment]
> In the video you should see me open the window. When the window is opened, the visual is blank, and then a second or two later, the entire game pops in. This happens everytime.

Yep, that's how the renderer works. It stops drawing when the game is minimized and has to start drawing again, so you get a frame or two of nothing.
