### ISSUE TITLE
Crash: Crash and purple screen when changing res settings - System.ObjectDisposedException: This object has already been disposed.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#671]
Crash to desktop or purple screen of death occurs while changing res settings in game. This does not occur while changing res settings at start menu.

Crashlog: 
[201804261335307994_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/1952362/201804261335307994_Crashlog.txt)

Might be related to #669 

> System.ObjectDisposedException: This object has already been disposed.
> Object name: 'SoundEffectInstance'.

40d844c8

**Comment by mklingen** [comment]
Put a fix for this in master, but I don't know if it fixes it for you!

**Comment by com1clyf3** [comment]
No longer occurs in aea37e74
