### ISSUE TITLE
Design: Autoselect best graphics settings 

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#672]
![image](https://user-images.githubusercontent.com/6562812/39326827-27f21976-4964-11e8-84fb-46b97855795b.png)

40d844c8

Related to #651

**Comment by mklingen** [comment]
I took a look at this last night. Unfortunately from within XNA it's kind of hard to get relevant information about the GPU. I think the best I can do is find the GPU name, look up in a big table of GPUs and then have a hardcoded map to default settings for these, which will be a pain to do.

**Comment by com1clyf3** [comment]
Would it be better to hold off on this til we've made the switch to FNA or not going to help the situation?

**Comment by mklingen** [comment]
It's possible we might have more leeway with FNA as it is open source. I don't have experience in how games do this in general. It might require some platform specific code (i.e different code for windows, linux and mac) that we make ourselves.

**Comment by com1clyf3** [comment]
Yeah. Helped with the user side of these. Never the design.  Found a source that says we shouldn't be bothering looking for the GPU at all, and instead just use other benchmarks to determine perf: https://stackoverflow.com/questions/21397999/auto-detect-gpu

> See if the minimum version of your favorite compute API (OpenCL or whatever) is supported, and if the required extensions are present, compile some kernels, and see if that produces errors. Run the kernels and benchmark them. Ask the API how much local/global memory you have available, what warp sizes it supports, and so on.

**Comment by mklingen** [comment]
Oh interesting. That's a funny brute force solution. First time the game starts up, we run a benchmark to see what kind of FPS it would get with our game. Then we create the graphics settings from that.

**Comment by com1clyf3** [comment]
Regressing. I think we should still implement this.

**Comment by com1clyf3** [comment]
Regressing. @mklingen Wishlist, cut, or feature?

**Comment by mklingen** [comment]
cut for now.
