### ISSUE TITLE
AI: Dwarves fell asleep underwater

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#673]
![image](https://user-images.githubusercontent.com/6562812/39327780-135f8d74-4967-11e8-99d7-3a47269948e3.png)

Dwarves fell asleep mining blocks in shallow water. They then slowly drowned.

Repro:
1. Mine some blocks in shallow water near bed time. No beds yet built.
2. Observe the dwarves fall asleep in the water.

40d844c8

**Comment by mklingen** [comment]
oh boy you're right. I think I will make it so that if no beds are available, dwarves will go to the balloon port to sleep. They should also obviously refuse to sleep while in water.

**Comment by mklingen** [comment]
Okay, I have made this change in `master`: when it's time for bed the dwarf will do the following:

(1) try to reserve a bed to sleep in. If this fails then (2) try to find a room (balloon port, etc.) to sleep in. If this fails then (3) if you're in water, wake up and go back to step (1) else (4) sleep on the ground.
