### ISSUE TITLE
GUI: Windowed mode registers click back into game as player input, making the map move

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#676]
As discovered in #669 

![image](https://user-images.githubusercontent.com/6562812/39440268-60869ad4-4c78-11e8-9605-db9d3c8cee41.png)

Vid: https://drive.google.com/file/d/18XEas6OCrKoqsP-qKeDRo80aXALVP50v/view

 
aea37e74

**Comment by mklingen** [comment]
hard to make this work in general. @Blecki any ideas? Maybe we can detect if the game is inactive and put a cool down period of like 1s when we start accepting input again

**Comment by mklingen** [comment]
fixed in master.

**Comment by com1clyf3** [comment]
This still occurs in 14d73805

**Comment by mklingen** [comment]
Hmm, still trying to reproduce and can't anymore. Probably has something to do with the exact order of when you click, minimize, or press camera control keys. In any case it's way more rare now.

**Comment by com1clyf3** [comment]
Closing.
