### ISSUE TITLE
Save / load: Selected tiles carry over to a new game after quitting a previous game

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#678]
![image](https://user-images.githubusercontent.com/6562812/39449948-901582fa-4c97-11e8-8576-aa94cfd7dd0c.png)

These are selected tiles from the game I quit before opening this new game. Happens with at least plant, dig, and guard. They don't need to be touching each other or the balloon port.

1. Start a new game.
2. Select some tiles to dig, plant, and guard.
3. Quit that game, but don't exit app.
4. Start new game.
5. Observe that the selected tiles from your original game are in your new game's terrain. (If you don't see them, search through the slices.)

aea37e74

**Comment by Blecki** [comment]
Fixed on blecki-dev.

**Comment by mklingen** [comment]
oops, this is a bug that is currently in the wild on Steam.
