### ISSUE TITLE
Build: Strawman has incorrect offset making unable to be moved

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#679]
![image](https://user-images.githubusercontent.com/6562812/39450822-9cdf5882-4c9a-11e8-9df9-6be255ea7000.png)

1. Build /spawn strawman.
2. Move strawman.
3. Observe strawman preview art is offset into ground and unable to be placed.

aea37e74

**Comment by mklingen** [comment]
fixed in master.
