### ISSUE TITLE
Build: Targets spawned from God mode don't behave naturally.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#680]
![image](https://user-images.githubusercontent.com/6562812/39451298-307382a2-4c9c-11e8-9c7d-3f1cb299140b.png)

Targets are not occurring when a strawman is built. According to the target I spawned, target's offset is also incorrect, which can be observed in the screenshot.

aea37e74

**Comment by mklingen** [comment]
Fixed in master.

**Comment by com1clyf3** [comment]
Targets built normally have normal offset, but targets built from god menu are still half in the earth.

![image](https://user-images.githubusercontent.com/6562812/40737186-0b9236ca-640e-11e8-9635-c7221046c95c.png)

2cc387dd

**Comment by mklingen** [comment]
how about when they're built normally?

**Comment by com1clyf3** [comment]
They behave normally.

**Comment by com1clyf3** [comment]
Fixed. Closing.
