### ISSUE TITLE
Balance: necromancers are too powerful.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#687]
![image](https://user-images.githubusercontent.com/6562812/39460702-98cfc93c-4cd3-11e8-9bd2-257f23b991e1.png)

Not sure if it's any more specific than this, but so far it seems that if you're in a new game and the first war party to attack you is undead, the game will spawn two war parties. The difficulty setting is normal.

Two war parties with a starting colony almost always kills your entire colony.

Save: 
[Horn Realm_785_131696214148275591.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1962965/Horn.Realm_785_131696214148275591.zip)

World: 
[Horn Realm.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1962966/Horn.Realm.zip)

ac0e675c

**Comment by mklingen** [comment]
Spawns two war parties? Or it spawns two necromancers? War parties vary in size randomly. The difficulty setting does not have an effect on war parties.

**Comment by com1clyf3** [comment]
It's the amount of two normal sized parties for the first war party of the game. The effect is two necromancers and twice or more the amount of undead. There is only one announcement, but the party is twice the size.

I've never seen the game change the size of a war party so drastically. If this is part of some new design, I'd suggest pushing it to a harder difficulty. So far it has always wiped out the entirety of a new colony.

**Comment by com1clyf3** [comment]
Ah! Yeah.  Less HP and slower should do the trick then, yeah.

**Comment by mklingen** [comment]
I have made skeletons much weaker and slower.
