### ISSUE TITLE
New gui issues

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#69]
Playstate:
- [x] Hotkeys for time forward and backward not working. Pause hotkey not working. Minimap hotkey not working.
- [x] Time panel has both forward, backward and pause buttons visible now with no highlights to show which is being used.
- [x] screen briefly purple when starting game (likely this means whatever render target you're writing to the screen hasn't been initialized to yet before the first draw call)
- [x] Wood background panel on tray getting stretched instead of wrapped.
- [x] Main text now black instead of white with black stroke, making it unreadable. 
- [x] Pushing the "Options" button on the top right causes an `InvalidOperationException` in Widget.cs
- [x] Tool buttons not highlighting when depressed
- [x] Mouse is drawn over old mouse. Perhaps new mouse should be hidden until GUI fully replaced.
- [x] No more tooltips on PlayState widgets. 
- [x] Cooking button now gone (has wrong icon, and pushing it doesn't reveal cooking menu)
- [x] Number keys no longer correspond to appropriate tools in the tool bar on the bottom right (should be row-major order)

In general:
- [x] No more mouse over events. (highlighting)
- [x] Mouse scale is now 1x instead of 2x
- [x] Sliders not responding to drag events.
- [x] Widget backgrounds are stretched instead of wrapped (should be a simple fix in the shader).

**Comment by Blecki** [comment]
Last item in list: Not a simple fix; the GUI is using a texture atlas compiled at program startup. This is what allows it to cache the entire GUI into a single vertex buffer and draw it in a single call. Eliminating the stretching is possible, it just requires generating more geometry. I'll save it for after I tweak the layout inside the button panels. I also want to see what they look like with a plain background first; they may look nicer that way.

**Comment by Blecki** [comment]
For the screen briefly being purple: Yeah, likely. I'm rendering to the minimap before the screen. Previously this was rendered as part of the old gui's prerender call. It seems to affect it up until the first update call. After that, it renders fine. The underlying problem may be that render is called before the first update.

**Comment by Blecki** [comment]
Cooking button: Where was it previously? I thought I had managed to get all the right icons, but some showed up duplicated (such as the swords).

**Comment by mklingen** [comment]
Cooking was right next to the build/farm menus. It's a completely seperate menu from building.

**Comment by mklingen** [comment]
when I said it was possible to accomplish in the shader what I meant is that you can pass the bounds in the atlas to each vertex, then wrap when you get outside the bounds in the fragment shader.

**Comment by mklingen** [comment]
Most of these issues are close to being fixed. Just need to address the purple screen issue and add tool tips back to most things.

**Comment by mklingen** [comment]
Okay, fixed the purple screen. I'm going to do an audit of tooltips and put them in wherever they're missing.
