### ISSUE TITLE
Object disposed exception while rendering voxel icons.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#699]
Log:
[201805081449535328_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/1985259/201805081449535328_Crashlog.txt)

Crash occurred. No repro found so far. Happened something like this:
1. Start new game advanced
2. Advanced settings - World size: very low, Natives: Very high.
3. Placed my colony in the bottom right corner near the concentration of natives.
4. Start game.
5. Crash.

126d7ff8

**Comment by mklingen** [comment]
Related to #692 , again I think the solution will be to switch to FNA.

**Comment by mklingen** [comment]
I have patched master with a change that will make it re-load any texture that was disposed. I was unable to reproduce this crash, but my patch may fix it. Again, I think this cannot happen in FNA.
