### ISSUE TITLE
Monogame port

### ISSUE THREAD

**Issue by Blecki** [CompletelyFairGames/dwarfcorp#7]
I got the project to compile and run under monogame and I am listing the issues I encountered here just in case someone else wants to try a port.

- All shaders need to be upgraded to SM 4.0. For all of them, a simple change from _2_0 to _4_0 was enough and allowed them to compile.
- Setting up the new content project is tedious.
- One new compile error on a call to SetVertexBuffers. Wrap first argument in a VB binding.
- Delete the existing reference to JSON and install the current version through nuget.
- Add a 'color' deserializer to the special JSON deserializers. I based it off the vector3 deserializer, with anther element. It was quite easy.

**Comment by Blecki** [comment]
- Sphere model used by the sky is an outdated format not supported by monogame. Replace model or remove sky from world. Removing sky seems to also remove daylight, resulting in solid black world.

**Comment by mklingen** [comment]
I find it unlikely that removing the sky caused daylight not to be rendered. Sky and daylight are totally separate. If the world is solid black that is likely an issue with the texture shader. From my last attempt at porting to monogame I remember there being an issue with default values for uniforms in the shader (which MGFX hates). Anywhere there is a "xWhatever = foo;" in the "TexturedShaders.fx" file should be replaced with a dynamic call to set "xWhatever" in the game's initialization code.

Other culprits could be the dynamic shadow shader (which would cause everything to be black if it were failing).

**Comment by Blecki** [comment]
With a bit of experimentation I was able to determine that it is the glow shader. Toggling this in settings toggles the completely black world. With the glow shader on, you get only the gui.

I was also able to determine that there is far less of a performance problem when paused than when running.

**Comment by mklingen** [comment]
Might be worth copying the glow shader from the monogame samples: https://github.com/CartBlanche/MonoGame-Samples/blob/master/BloomSample/BloomComponent.cs

The one in Dwarfcorp is an unmodified copy of the one from the XNA samples, and if there's a working sample already for Monogame perhaps it might solve the issues with the original XNA shader, though I haven't looked to see what changes were made to the shader for Monogame.

**Comment by mklingen** [comment]
This Monogame sample also contains replicas of the Bloom shaders from XNA, but as far as I can tell they are identical to the shaders in DwarfCorp. It's possible that what's really going on is not a problem with the shader itself but rather the render targets getting set up for the bloom shader. 

https://github.com/MonoGame/MonoGame.Samples/tree/f73be380653676256dccad1ef67eb01fad548f92/NeonShooter/Content/Shaders

**Comment by samdeane** [comment]
> I got the project to compile and run under monogame and I am listing the issues I encountered here just in case someone else wants to try a port.

Is this a potential route to getting the project to _build_ on the Mac (eg via Xamarin or Visual Studio Community)? Even if the content can only be built on Windows, if there was a way to build/debug/apply-the-occasional-hotfix on the Mac, that would potentially be of interest.

(I know the read me says that it's Windows-only for development right now, but git blame says that statement was made whole _weeks_ ago ;) - and a guy can dream...)

**Comment by mklingen** [comment]
We're gearing up for release in mid-september right now on a [FNA/XNA ](https://github.com/FNA-XNA/FNA) platform. In FNA, builds must happen on Windows and then binaries get distributed to Linux/Mac. Someday we would like to port the project fully to MonoGame, which would allow development on platforms other than windows, but its not super easy.

**Comment by Blecki** [comment]
I'm still game to make the port. All of the issues above still apply.

I downplayed setting up the content project but it really was a pain in the ass.

**Comment by samdeane** [comment]
> Someday we would like to port the project fully to MonoGame, which would allow development on platforms other than windows, but its not super easy.

No problem -  I understand that getting a release out must take priority.

> I'm still game to make the port. All of the issues above still apply.

Is your work in a branch or a fork anywhere? I'm wary about making silly promises about spare time that I don't have, but in theory I'd be interested in helping, if it meant that I could get the thing building on a Mac 😁. It's not that it's impossible for me to get a Windows environment set up (there's VMWare, and I do boot into Windows to play Elite...), but I'm a Mac developer by day and it's a lot easier to stick with the environment I know...

**Comment by mklingen** [comment]
@Blecki forkwith monogame is quite old. I'd just start from scratch with a port, starting with[ this tutorial](https://developer.xamarin.com/guides/cross-platform/game_development/monogame/introduction/part1/) and manually inserting all the source files and assets, correcting the issues that might arise (there are a ton).

**Comment by samdeane** [comment]
> I'd just start from scratch with a port, starting with this tutorial and manually inserting all the source files and assets, correcting the issues that might arise (there are a ton).

Ok, thanks. That ain't gonna happen any time soon here 😁, but if I ever do start, I'll put it somewhere and let everyone know where.
