### ISSUE TITLE
Pickup: Killed dwarves don't leave tidied resources

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#701]
When a dwarf is killed, they drop their resources into an immense pile. The pile is not bundled at all, and the player will likely have to click over and over to collect the fallen materials, especially if they were carrying a ton of resources in their backpack.

We should make it so that killed dwarves leave behind their resources in easy to collect bundles, similar to what happens when destroying a stockpile.

126d7ff8

**Comment by mklingen** [comment]
Okay, sounds like a good idea. This is especially important for trade goods left by a dead creature from an envoy.

**Comment by mklingen** [comment]
All entities now drop piles (including trees, etc.). Piles now have a better visual indicating they are piles (with up to 3 sprites).
