### ISSUE TITLE
Pickup: Dwarves do not collect resources gained from digging under trees and other entities

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#702]
If a dig task is ordered under a tree or other resource entity, it will instantly be chopped and the resource will fall. The dwarves do not recognize this and do not collect the resource. We should make it so that they autocollect these resources.

126d7ff8

**Comment by mklingen** [comment]
That's correct. Currently auto-collection is handled by determining whether a dwarf has destroyed a block or an entity, but in this case the entity was destroyed as a side effect of destroying the block. This is by no means an easy thing to fix. One thing I have been thinking about is simply disallowing dwarves from mining under trees altogether.

**Comment by com1clyf3** [comment]
> >One thing I have been thinking about is simply disallowing dwarves from mining under trees altogether.

Let's do that for now. I don't see any reason to break a sweat over a fringe feature when we've got bigger things to do for now. We can always come back to it if we find the time.

**Comment by mklingen** [comment]
disallowed mining under trees and such in master.
