### ISSUE TITLE
Building farm is not working properly anymore

### ISSUE THREAD

**Issue by zentaki** [CompletelyFairGames/dwarfcorp#704]
So i plan to make a 4x4 size farm for grains.

Than the grid is draw on the ground and they start working on it but stops just plant about 6 then they stop also when this happens it creates a lot of invisible glitches around the area that won't let me even draw new grids for planting where it was able to before, with the bug on i can only try to plant little bit more further away from the bugged area and guess what? bug repeats itself in this new area and create even more bugged areas.

Messages like "there is something in the way" is thrown. 

Saved game:
[King Tama's Empire_195_Autosave.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1991440/King.Tama.s.Empire_195_Autosave.zip)

**Comment by com1clyf3** [comment]
https://steamcommunity.com/app/252390/discussions/1/1694921076570509486/?tscn=1525951800

**Comment by Blecki** [comment]
Can you turn bounding boxes on in the debug menu, please? Press g, find it under debug switches. 

A screenshot of this while attempting to plant will confirm what I think this is.

**Comment by zentaki** [comment]
i pressed G, there is a tab  on the left  with many option which i can see one of the top is been cutoff, it is actually an option because the even if i can't read it the mouse can touch it and open a sub menu there with some of them been "animal pen".
Just so you know that even this is not properly working :(
And the option you just told me to go to can't be found.
![untitled](https://user-images.githubusercontent.com/39157274/39897617-75dc5b80-5489-11e8-90fb-1e4a52947071.jpg)

**Comment by Blecki** [comment]
Oh wow, you're running at a super low resolution.

**Comment by zentaki** [comment]
weird
![untitled2](https://user-images.githubusercontent.com/39157274/39899237-25d93c04-5491-11e8-8cb1-392beaf8ba9a.jpg)

**Comment by Blecki** [comment]
Gui scale?

**Comment by zentaki** [comment]
i c, well game does not have proper scaling then. Scale should refit in the screen which does not for bigger scale which again makes scale option useless. any way.

![untitled3](https://user-images.githubusercontent.com/39157274/39900142-2b3f5f02-5496-11e8-88b9-5151ac672b5c.jpg)


![untitled4](https://user-images.githubusercontent.com/39157274/39900182-6d557e4e-5496-11e8-8ae2-976d49c41a0a.jpg)
So yes those dam bounding boxes.

**Comment by Blecki** [comment]
That's the enemy sensor. Is this the current steam version?

**Comment by mklingen** [comment]
Hello @zentaki thank you for your bug report. I managed to load the save you provided and confirmed that the issue exists in the save file and is caused by a bug in our collision system. @Blecki is working on a fix right now.
