### ISSUE TITLE
Quit = frozen game

### ISSUE THREAD

**Issue by zentaki** [CompletelyFairGames/dwarfcorp#705]
Quit function is not working properly here.
Game just freezes no response at all. 
Had to call task manager to finish the process manually.

Work around: just use alt+F4 now and restart the game because its much faster.

**Comment by mklingen** [comment]
Hello, thanks for reporting. I can't seem to reproduce this issue, either in full screen or windowed mode. Does this happen for you every time? Does it happen in windowed mode as well as full screen?

**Comment by zentaki** [comment]
Not sure if this issue was solved but today after the update the game just quitted normally as it should.
So i'll keep an eye to the problem if it will persist or not, unless you guys had got to the problem and solved it.

**Comment by com1clyf3** [comment]
@mklingen This a coincidence or did we fix this?

**Comment by mklingen** [comment]
Not knowing the root cause, I can't say for sure. Possibly it happens only under certain circumstances that we haven't been able to reproduce fully yet.

**Comment by zentaki** [comment]
This issue seems not to occur anymore.
