### ISSUE TITLE
Switching to FNA

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#715]
Issue to plan and track progress on phasing out XNA.

**Comment by mklingen** [comment]
Note, project structure needs to be cleaned up so that CS files don't have to be included from the XNA project. this causes all kinds of problems for example when there are merge conflicts.

**Comment by mklingen** [comment]
also FNA has to be checked out to the right revision.

**Comment by com1clyf3** [comment]
Regressing. We're currently planning to implement this around the polish/release phases.

**Comment by mklingen** [comment]
It's easy. The builds already exist and work. The only thing that isn't easy is getting an FNA development environment *for you to test*. And since XNA works just fine I don't see a reason to switch.

**Comment by com1clyf3** [comment]
Ah. Alright. Let's close then.
