### ISSUE TITLE
World Generation: Text overflow in faction info panel

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#716]
![image](https://user-images.githubusercontent.com/6562812/40028687-55e406a2-57ae-11e8-90fd-8572057af9be.png)

In highly populated areas, the text will overflow the faction info panel.

061f6d5c

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/40324589-fc43064e-5d06-11e8-8c48-d76603d8e942.png)

We should put some kind of gray or transparent layer behind these words. The darkest color fonts are unreadable when in front of the abyss.

**Comment by mklingen** [comment]
ok, will brighten them up a bit.
