### ISSUE TITLE
Art: Build preview and sprite art not rendering after re-entering game

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#717]
![image](https://user-images.githubusercontent.com/6562812/40029352-3436ca22-57b2-11e8-9f77-d08aaa47c15b.png)

All build preview and sprite art is not appearing. 

Think it might be connected to a long freeze that occurred after selecting a large amount of dig designations, CTRALTDLT'd and opened task manager to get past freeze, which probably triggered the XNA issues we've been seeing recently like #692 #695 and #677 .

Or this:
![image](https://user-images.githubusercontent.com/6562812/40029710-feb4d6a8-57b3-11e8-87b4-d5ac71198ef4.png)

Here's a save in case it turns out to be more mysterious:
Save:
[Ltarlia_795_DEBUG.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2003028/Ltarlia_795_DEBUG.zip)

World:
[Ltarlia.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2003031/Ltarlia.zip)

5fee6751

**Comment by Blecki** [comment]
Did you switch to another window and back?

**Comment by com1clyf3** [comment]
After further investigation, pretty sure this is still just the exit game then re-enter the game issue with XNA.

**Comment by com1clyf3** [comment]
Neeeevermind. Figured out, This is just straight up still #692.
