### ISSUE TITLE
Design: Add rails tutorial

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#726]

**Comment by com1clyf3** [comment]
Regressing. Still needed.

**Comment by Blecki** [comment]
It's there.

**Comment by com1clyf3** [comment]
You right. The naming conventions for the rail types themselves is still pretty confusing though. You should either tidy up the names or give some explanation in the tutorial blurb.

@Blecki

**Comment by mklingen** [comment]
This is done.
