### ISSUE TITLE
Pathing: Mining Dwarfs Get Stuck 1x1x1 Holes & Trenches 1 Block Wide, 1 Block Deep

### ISSUE THREAD

**Issue by japerson34** [CompletelyFairGames/dwarfcorp#727]
When mining surrounding blocks, I notice the mining dwarfs sometimes get stuck in 1x1x1 holes and in trenches 1 block wide, 1 block deep. I'll have to manually move the dwarfs so that they will approach the blocks they were working on from another angle.

**Comment by com1clyf3** [comment]
@japerson34  If I've read this issue correctly, so far I'm unable to reproduce your issue. All dwarves that do get stuck, only get stuck for a few seconds which, well, is normal. Then they find their way back to HQ. It's possible I'm not reading your bug right though. Could you provide some screencaps and/or a video of the dwarves becoming stuck?

#617

**Comment by japerson34** [comment]
Well, I got another one stuck and just waited till 2nd miner cleared everything around him thinking that would free him up. It did not. Don't know if this SS helps. Just wanted to let you know I was still trying to replicate the issue.

![clipboard05](https://user-images.githubusercontent.com/30176327/40276688-95a12f02-5bde-11e8-84f8-99a76943c696.jpg)

**Comment by japerson34** [comment]
Just got stuck again and this is typically the situation they get stuck in. Once a miner starts getting stuck, it will start getting stuck a lot while the 2nd miner experiences no problems.

![clipboard06](https://user-images.githubusercontent.com/30176327/40276755-4fcd9e32-5be0-11e8-8818-531e6af4a51a.jpg)

**Comment by japerson34** [comment]
Same dwarf now unable to find HQ for food. 30 second avi video made but too big to zip and send.

**Comment by japerson34** [comment]
Eventually all dwarfs, even newly hired ones, end up running in circles eventually dying from foes or starvation.

**Comment by mklingen** [comment]
Thanks for the save, will check it out.

**Comment by mklingen** [comment]
> Eventually all dwarfs, even newly hired ones, end up running in circles eventually dying from foes or starvation.

That would mean they're all simultaneously trying to plan to tasks that are impossible to reach. Start cancelling tasks and eventually they will stop.
