### ISSUE TITLE
Firing dead dwarf results in crash

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#738]
![image](https://user-images.githubusercontent.com/6562812/40317850-b74cc932-5cf0-11e8-97a2-ba8eadb72127.png)

https://steamcommunity.com/app/252390/discussions/1/1488861734112858744/

No repro found yet.

Steam release 18.05.16

**Comment by com1clyf3** [comment]
Nah. As far as I can tell, the player is describing a dwarf that dies, but is still listed in the economy or emp menu. Then firing them. Then crash.

**Comment by mklingen** [comment]
Yeah, that's exactly what I was suggesting.

**Comment by com1clyf3** [comment]
My bad. Read too fast. Anyways... Tried this out and found the repro. Happens when the dwarf dies and their emp profile is already up.

1. Pause game.
2. Pull up the emp profile of your victim.
3. Kill dwarf.
4. Fire dwarf.
5. Observe crash.

89606ad5

**Comment by mklingen** [comment]
Okay will fix.

**Comment by mklingen** [comment]
Fixed.
