### ISSUE TITLE
Design: Add new cave view feature

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#739]
![image](https://user-images.githubusercontent.com/6562812/40323908-d798e752-5d04-11e8-9e9f-4d1d4ced1aa8.png)
![image](https://user-images.githubusercontent.com/6562812/40323915-de4b658e-5d04-11e8-9289-9e6ebc61c9cf.png)
![image](https://user-images.githubusercontent.com/6562812/40323944-fae6f690-5d04-11e8-9873-686ff83654fa.png)
![image](https://user-images.githubusercontent.com/6562812/40323946-ff424dfc-5d04-11e8-8219-68a932a6e8b0.png)

**Comment by mklingen** [comment]
I noticed that @Blecki added a new feature to the cheat menu which allows you to hide the topmost faces of chunks. This gets us pretty close to the view you're describing. It also makes me realize that implementing this view wouldn't be a challenge graphically, but it would require serious effort to get the mouse/camera playing nicely with it. For example selecting blocks in this view would work differently than it currently does -- the ray would have to pass through tunnels and select only visible blocks on the other side.

**Comment by Blecki** [comment]
That's where the god menu feature came from. It was a quick hack to see how far from this feature we really are.

**Comment by com1clyf3** [comment]
Trying it out. Definitely some issues. 

- We'd have to change slicing to render cave above the camera view. Right now it cuts away cave above the camera's slice. Pretty sure these faces were cut as a performance fix, but we could limit how they're rendered, say ten slices that slowly turn transparent and then nothing, to suggest a limited player view.
- In order for the above to make sense, the player will also probably need the side faces/walls in the forefront transparent or gone for more than one layer (like we already do, but more reliably and in a larger range), Otherwise they'll have a difficult time viewing the cave from the side.  For overhead, we'd probably need to do something similar.
- With the selector issue, would it be possible to snap the selector inside the nearest cave or  a slice in the middle of a cave within a range it's in, say ten slices? This would ensure the player always starts with an oriented camera and selector.

My original conception of this was a limited view you could adjust, and not rendering the whole cave map all at once.  This would limit the performance expense and complexity of the camera and selection issues as well. We'd have to figure out the right number of layers, but for an example, there's a minimap with a model of the entire map and cave system. There's a slider that's ten slices large, and the player can move it up or down, and that would be the selection area. They could still see things below and above them, they would just fade into transparency and eventually darkness to suggest a limited player view. However, players could still examine their cave structures and such through the minimap (Which, theoretically we could make moveable, like a 3D model). Not sure if this is tougher to implement or not?

**Comment by com1clyf3** [comment]
Regressing. We ever going to implement this or  nah?

**Comment by com1clyf3** [comment]
Wishlisted.
