### ISSUE TITLE
Settings: Generating world with advanced settings causes crash - System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#740]
1. Start new game advanced
2. Generate world
3. Open advanced settings (for the repro, you actually don't need to change anything)
4. Close advanced settings.
5. Observe crash.

[201805211423172923_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2023699/201805211423172923_Crashlog.txt)

Might be connected to #587 fix. I saw some entities spawn off map a few times, right before crash.

89606ad5

**Comment by mklingen** [comment]
Hmm ok will take a look.

**Comment by mklingen** [comment]
Fixed this on my commute, haven't pushed yet.
