### ISSUE TITLE
Settings: Small res in full-screen causes pauses and issues

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#750]
1. Load game. Full screen 1024x768.
2. Switch res to 800x600. Observe large white block render on screen for a few seconds.
![image](https://user-images.githubusercontent.com/6562812/40678508-ba05e9a6-634e-11e8-96e7-e3ad3126dd7f.png)
3. Switch res back to 1024x768 to see it again.
4. Press start to minimize fullscreen. Then click toolbar icon to get back into game.  Observe this:
![image](https://user-images.githubusercontent.com/6562812/40678599-f0f58cb4-634e-11e8-96c7-8b997805c85d.png)

Guessing it's related to our viewport issue?

5c6a30a6

**Comment by mklingen** [comment]
Unlikely. I have no idea what this is. Is this something transient or is the game unplayable after you change resolution?

**Comment by com1clyf3** [comment]
Transient. Sometimes it will last a little longer than normal and sometimes it will show a cut off version of the player's computer screen in the fullscreen window, then render game.

I found a comment on the Discord related viewport stuff in January describing a window that appears in the screen corner after messing with fullscreen stuff. Thought it might be connected.

**Comment by com1clyf3** [comment]
Regressing. This still occurs.

**Comment by mklingen** [comment]
I think this is not a big deal.
