### ISSUE TITLE
UI: Small res cuts off confirmation buttons, trapping player in menu

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#751]
![image](https://user-images.githubusercontent.com/6562812/40679505-5419c51a-6351-11e8-98d3-c3dcf90896c7.png)

In 1024x768, the options menu renders with its confirmation buttons behind the Microsoft toolbar. This makes it impossible to exit the options menu and forces the player to quit the game. The only fix to this is to then edit settings in the game files themselves.

Easiest design fix is probably enabling an Esc key cancel from this menu, however it still doesn't allow player to change res to something functional. Maybe we could add the confirm/cancel button to the top of the graphics menu as well as the bottom.

5c6a30a6

**Comment by com1clyf3** [comment]
Yup.

**Comment by mklingen** [comment]
Hey so we fixed this long ago by adding in the "confirm that these settings are ok" window. You confirmed that they were OK even though the window was off the screen. I see that as user error and not something that we're going to fix.

**Comment by com1clyf3** [comment]
Fair enough.

**Comment by mklingen** [comment]
Okay, fixed by adding ESC to this menu, which then pulls up a "would you like to apply changes?" dialog

**Comment by com1clyf3** [comment]
Sweet!
