### ISSUE TITLE
Design: Enable players to re-assign priority tasks easily

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#752]
![image](https://user-images.githubusercontent.com/6562812/40680403-029b1d12-6354-11e8-9a23-f72262c76b6a.png)

Right now I can assign a very large dig task, and dwarves behave as if it's one large task. If I then assign a very small dig task,  dwarves will not get to it for a good while because of the task order. Generally the reason to do these small tasks is just to get one or two specific resources that are needed for a current craft task or something. 

For me it tends to be my non-main digging site, so places on the surface, but occasionally places underground as well where a resource deposit is. Maybe the easiest design would be if we can give higher priority based off of the size of the dig area, say 1 to 30 voxels.

**Comment by Blecki** [comment]
There's only one size of dig task. Do this and users will just wonder why their big task didn't get priority.

**Comment by com1clyf3** [comment]
The idea would be that if there's a very small dig task the player doesn't have to wait for possibly more than an hour to dig a small area. Maybe we could just do 1 to 10 voxels and assign one dwarf to these side digs.

**Comment by mklingen** [comment]
A "dig task" is just a single voxel. There's no notion whatsoever of them being connected. Dwarves just greedily go to the nearest dig task, so if you want a dwarf to start digging in another location, you'd select him, and right click near where he's supposed to be digging.

**Comment by com1clyf3** [comment]
Oh! Okay. Then that's just a matter of teaching that correctly. I'll note it in the GDD.

Closing.

**Comment by com1clyf3** [comment]
So. Testing this out. The location priority is only true when the tasks are made at the exact same time. However, if I make a far away task first, then a very close task moments later, the dwarves will prioritize the further task. If I select those dwarves and command them to the closer task, they'll go to the spot, not perform the task, and then return to executing the further task. 

In order to enable the player to use the location based task execution effectively, is there a way to get the task manager to disregard the order in which the tasks were originally designated or is that game breaking?

**Comment by mklingen** [comment]
The reason right clicking doesn't work in this case is because the task has already been assigned to the dwarf.

**Comment by com1clyf3** [comment]
Right. But could we enable players to re-assign task by location by sending dwarves to those locations?

**Comment by mklingen** [comment]
Perhaps right clicking should cancel the current task and reassign it to another dwarf.

**Comment by com1clyf3** [comment]
Hmmm. Yeah. I think that should work. Should be pretty smooth once we visualize the whole universal selector thing, so the action would be something like select dwarf(ves), hover over task area, selector shws image of nearby tasks, then player right clicks to assign.

**Comment by com1clyf3** [comment]
I've just learned Rimworld works on a pretty similar design, and it works really well. Their design is technically, click on colonist, right click on relevant entity. Options display. Select option to set relevant task as priority.

**Comment by merticois** [comment]
To this end, I would suggest/argue that you should be able to assign default priorities for tasks of a type so you don't need to switch each task individually.

Example: I found a area containing gold and would like to assign a mining task as high priority. I would like to be able to open a task priority menu and bump mining tasks up to high and then do my mining selections.

**Comment by com1clyf3** [comment]
Closing for regression.

**Comment by com1clyf3** [comment]
#627 This should still be done. Most players have no clue where our priority menu is.

**Comment by mklingen** [comment]
We have a priority menu?

**Comment by mklingen** [comment]
Okay, I have added two new features to the context menu. You can now tell dwarves which tasks they're not allowed to do using the context menu. You can also set the priority of entity tasks (though not voxel tasks like digging yet)

![task_priorities](https://user-images.githubusercontent.com/241184/44960696-d03f3000-aed1-11e8-9939-b19ff6b7b228.png)

**Comment by com1clyf3** [comment]
Priority menu I was referencing was the "Allowed Tasks" menu. Now that it's hooked to the universal selector, it's much more friendly.

Just add dig and other mainstream tasks to it, and it should be done and polished as far as I'm concerned.

**Comment by mklingen** [comment]
Okay the problem with "dig" is that it's a voxel task, which at the moment can't be selected by the universal selector. @Blecki was thinking about ways to make that possible, but it's tricky.
