### ISSUE TITLE
Build: Can't place dig and plant tasks next to zones

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#756]
1. Place down a zone or find an already built zone
2. Place a dig or plant task next to the zone
3. Observe the task tile art appear momentarily and then vanish

2cc387dd

**Comment by mklingen** [comment]
Fixed in master.

Core issue is that voxel listeners for fixtures were too large. The fences on the outside of the zone were extending futher out than they should have.
