### ISSUE TITLE
Build: Moving objects turns them permanently blue

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#757]
![image](https://user-images.githubusercontent.com/6562812/40736581-68040d18-640c-11e8-9e50-a1c59953c709.png)

1. Build a turret, a chair, or any kind of table
2. Move these objects
3. Observe that they stay highlighted blue after moving them. *Turret is also exhibiting issues with its shadow.

2cc387dd

**Comment by Blecki** [comment]
I broke the move tool apparently.

**Comment by Blecki** [comment]
Fixed in master.
