### ISSUE TITLE
Design: Auto-replenishing tasks

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#760]
The player can order ten meals to be prepared. If they want another ten, they'll have to go in and re-order that task. For things like meals (but also bread, drinks, trinkets, etc), this becomes repetitive in the not fun way, so we should add a "stock" feature. Feature should ask how many the player would want of something, say 20, and the task should be assigned. If the number of meals dips under 50 at any point, new tasks should be auto-assigned to cook back to the predetermined stock number. This way food is a mechanic that players can progress (once they reach a certain wealth, they can afford to enable stocking without worrying about depleting resources too quickly), and only micro-manage the mechanic if they so wish.

**Comment by mklingen** [comment]
Would need UI to manage/assign such tasks.

**Comment by com1clyf3** [comment]
I believe Towns (I'll have to find an image...) has an entire menu dedicated to this feature, which looks alright. Towns has a lot more automation to it than our design though, so I think we could get away with adding individual options to turn on in each feature UI. Eventually we could add a more graceful solution to UI, but i'd wait until we get to redesigning it in July or so, after we've settled on design stuff.

Right now I could imagine, at its simplest, a check mark labeled "Keep in stock" and below what we already have, choosing amount, and made from what.

**Comment by com1clyf3** [comment]
https://towns.gamepedia.com/Production_Menu

**Comment by com1clyf3** [comment]
Nevermind. We implemented our own auto thing. Closing.
