### ISSUE TITLE
Snow spreading in animal pen

### ISSUE THREAD

**Issue by shoomish** [CompletelyFairGames/dwarfcorp#761]
After a snow storm, snow patches in my animal pen (chickens) wouldn’t melt when the rest of the snow melts, and actually spread on the ground to be roughly the same size as the animal pen itself (13x13). it’s been over 11 in-game days and it’s still there, even without any snow storms in the mean time, and the rest of the map is clear of any snow.

(also this is my first issue submission, lmk if i should format it differently, really want to contribute however i can to this game because i love it. thx)
![dc animal pen](https://user-images.githubusercontent.com/39912401/40946497-d37e33fc-682b-11e8-9dbc-5c98850dbcdd.png)

**Comment by mklingen** [comment]
Thanks, can you show a screenshot please?

**Comment by Blecki** [comment]
Probably just wrong settings in grasstypes.json

**Comment by shoomish** [comment]
screenshot added

**Comment by mklingen** [comment]
@Blecki was this ever fixed?

**Comment by com1clyf3** [comment]
Regressing. @Blecki ^

**Comment by Blecki** [comment]
Fixed. Snow no longer spreads like grass and now melts.
