### ISSUE TITLE
Design / AI: Crafter should be able to receive resource from other dwarves

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#763]
![image](https://user-images.githubusercontent.com/6562812/40996319-8e9a21c0-68cf-11e8-9857-0019235bdb36.png)

(Crafter sitting on their ass, when there are available paths for its needed resources.)

When a crafter runs out of the needed resource for the task, it will go and do something unrelated (like sit and wait). However the resource may already be in hand of another colonist and/or a task may already be assigned to collect the needed resource. The crafter should be able to look for any task related to resource needed, and then either

1) Collect it from the other colonist's backpack 
2) OR go dig/chop it and pick it up themselves.

**Comment by mklingen** [comment]
(1) is easier than (2). Would just have to generalize the notion of stockpiles to include stuff in other dwarves backpacks. Might lead to some awkward situations as dwarves follow around other dwarves trying to get their resources.

**Comment by com1clyf3** [comment]
Hm. Yeah. What if we treated it like a new task for the gathering dwarves, and they are ordered to make a temp stockpile of just the needed resources. Then when filled, the dwarf would go collect it, and the stockpile would be automatically destroyed.

**Comment by mklingen** [comment]
ah that's an interesting idea. They could just leave it on the ground and the other dwarf could go gather it.

**Comment by com1clyf3** [comment]
Yup. Seems simple enough. Only issue I see is player canceling a task auto generated from a craft task. It would then need to re-order that task.

**Comment by com1clyf3** [comment]
Regressing. Given that our dwarves would rather gamble and or get bored, want to cut this? @mklingen  

I still like the idea, and visually it'd be interesting as well.

**Comment by mklingen** [comment]
I tried it months ago and found it too difficult to implement.
