### ISSUE TITLE
Design / AI:  Kobold should be more of a threat

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#764]
Even though they are transparent, all the player needs to due is pause the game and select the Kobold with a hunt task. Player should not be able to hunt the supposedly secret and hidden Kobold until the Kobold is within five or so voxels of their port. Player should also not be able to select the Kobold announcement and have their camera pan over to the Kobold.

Kobold's should also have higher health or higher attack, to give them a higher chance of successfully pathing to the balloonport and detonating their powder keg.

**Comment by mklingen** [comment]
> detonating their powder keg.

Gremlins do this, not kobolds?

**Comment by mklingen** [comment]
As for your other concerns, sure. Will put in a check to make sure the player can't "hunt" cloaked creatures. I don't think panning over to the kobold is a problem, as it helps with situational awareness. It's the dwarves that don't know where the kobold is, not the player.

**Comment by com1clyf3** [comment]
> Gremlins do this, not kobolds?
Must've gotten them confused.

No. Panning isn't a bug,  but it is bad design. If the idea is something is a threat because it's hard to see,  we shouldn't then make it easy to see. The dwarves are an avatar representing the player. Ideally we want the player to be sad, afraid, happy, and so on for them, and we can do that by enabling role playing in the design.

**Comment by mklingen** [comment]
OK fair enough, just thought it might be confusing to suddenly have an invisible creature appear in your base!

**Comment by com1clyf3** [comment]
It could be, but given that DF-like is partially about a dash of chaos, we're prolly fine. Worst comes to worse, we just change it back.

**Comment by com1clyf3** [comment]
Closing for regression.
