### ISSUE TITLE
UI: Minimap stopped rendering

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#766]
![image](https://user-images.githubusercontent.com/6562812/41000743-f0a07fba-68dc-11e8-837c-1b6cf1c55ecb.png)

This may have happened before, but I noticed after the following:
1. #739 Occurred after clicking on an elf war party announcement.
2. Clicked the home button on the map, panned to port.
3. Map stopped rendering correctly.

[Dwarfclaimed Empire_87_131727040890647189.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2073873/Dwarfclaimed.Empire_87_131727040890647189.zip)

[Dwarfclaimed Empire.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2073875/Dwarfclaimed.Empire.zip)

3eea47e7

**Comment by mklingen** [comment]
try minimizing and unminimizing the game. Also slicing the terrain will probably bring it back..

**Comment by com1clyf3** [comment]
It didn't.

**Comment by mklingen** [comment]
Hmm ok. Will try to reproduce.

**Comment by com1clyf3** [comment]
Regressing. This get fixed? @mklingen

**Comment by mklingen** [comment]
I have no idea how to reproduce, so this is a wontfix.
