### ISSUE TITLE
God menu: spawn menu is overlapping text

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#767]
![image](https://user-images.githubusercontent.com/6562812/41001734-cdf46776-68df-11e8-8a62-ee7e60b26d50.png)

3eea47e7

**Comment by com1clyf3** [comment]
Found a repro:
1. Load save below:
[Dwarfclaimed Empire_87_131727040890647189.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2073947/Dwarfclaimed.Empire_87_131727040890647189.zip)
[Dwarfclaimed Empire.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2073948/Dwarfclaimed.Empire.zip)

2. Open spawn menu.
3. Quit game, and start a new game.
3. Open spawn menu.

**Comment by mklingen** [comment]
Yeah, I know. The debug menu isn't intended for users.

Honestly we should just not put any "generated" resources in the spawn menu.

**Comment by com1clyf3** [comment]
Closing for regression.
