### ISSUE TITLE
Crash: Spawn Crafts feature "Unable to create entity of type Punching Bag"

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#772]
1. Enter game.
2. Select Spawn Crafts in God Menu. Observe crash.

[201806201519251177_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2120756/201806201519251177_Crashlog.txt)

96962047

**Comment by mklingen** [comment]
This is fixed in my branch. Will wait for a merge of my branch into master for fix.

**Comment by mklingen** [comment]
Fixed now in master as I merged `item_refactor` in.
