### ISSUE TITLE
Redesign: Empty backpack frequency and function

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#779]
Somewhere along the way, the original function of this feature got lost. Discussed the issues and we decided to:

1) Make dwarves empty backpacks into stockpiles (versus drop resources on ground).

2) Change the frequency of how long it takes for dwarves to empty into stockpiles. The current limit is too high. Let's try something like 30-50. We could also try something connected to time, like an automatic resource dump halfway through the work day.

06c9d3dd

**Comment by mklingen** [comment]
This is done in master.
