### ISSUE TITLE
Design: Introduce a retreat option for certain monster events

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#786]
When dwarves encounter an OP monster (snake, demon, etc) out in the terrain, they all run in, one after another, and die. This seems like a totally natural and fair outcome if the player allows the monster to reach their balloonport.  However, in the former, the player is more a victim of the systems. So, we should give the players a bit more wiggle room by detecting if the monster is more than X voxels away from the balloonport, player can deselect the attack option on the monster, which will call all dwarves away and back to the balloonport to heal. This allows the player to choose when to attack these monsters, versus getting randomly wiped out by them somewhere off screen. 

This falls in line with out current saving throw mentality on spontaneous chaos like gremlins and kobolds.

62c295a9

**Comment by mklingen** [comment]
1) dwarves already retreat from powerful enemies. They have a dice roll called "fight or flight" that's dependent on their constitution stat. If the dwarf is particularly brave he'll fight the creature. If not he'll run away. Maybe that needs to be balanced.
2) you can already deselect attack designations (although they may immediately get re-created if a dwarf is nearby and wants to defend himself.
3) I need clearer language about how you want this feature to be displayed. Is this a seperate tool? Is this a context menu command?

**Comment by com1clyf3** [comment]
1. I'd definitely work on the balance. The only time I've seen a dwarf fly from a monster is right before it dies.

2. Yeah. I think it's still getting recreated.

3.This is a context based feature, yeah.

We'll need a logic that measures how far away enemy is from balloonport. If enemy is close, say, within range of ten voxels, I think the average behavior is fine and earned (they let a monster get to their HQ, so now it's on them to get rid of it).

If the monster is more than ten voxels away, then the dwarves should enter the flight response and not auto-assign the attack designation. The player can always override this and apply the attack designation instead.

**Comment by mklingen** [comment]
I don't think this feature is desirable. If anything dwarves run away from monsters far too often. I think the only extra logic I may add in the future is creatures giving up the chase after a while (currently they will chase a fleeing creature until it dies).
