### ISSUE TITLE
Performance: optimize frustum culling.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#787]
Frustum culling is still one of the slowest parts of the game. We've optimized frustum culling for instances, but non-instanced stuff needs to get culled properly as well. Let's figure out a way to do this correctly.

**Comment by mklingen** [comment]
A user has submitted a pull request which does this. Still waiting to merge that in I guess.

**Comment by Blecki** [comment]
Did that get merged? If so lets close.

**Comment by mklingen** [comment]
It's been merged!
