### ISSUE TITLE
Save/Load: Water loses texture after reloading save

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#790]
![image](https://user-images.githubusercontent.com/6562812/42463744-fc922ae6-8374-11e8-8fa3-9fb0ffd1c50b.png)

Bug reported on Steam: https://steamcommunity.com/app/252390

Haven't hunted for a repro yet. Will try to contact player for details.

**Comment by mklingen** [comment]
This has been fixed shortly after the last release.
