### ISSUE TITLE
Crash: Large dig tasks

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#794]
Trying to repro the large dig crash that I got yesterday, but I'm getting all kinds of mixed results. Good news is not every large task designation =crash. Doing so while the game is paused created a 10-30sec freeze, most of the time, which often resolves eventually. 

Making a large task when unpaused is almost always a freeze and sometimes a crash. These freezes can sometimes be resolved by pausing.

These tasks can go over 50% CPU and momentarily overheat the laptop.

I'm going to drop some crash data here to start with.

1. Designation made while game paused. Freeze happened. Clicked out of game and back into it. Unpaused game. Crashed.

![image](https://user-images.githubusercontent.com/6562812/42536513-4ac731a2-8460-11e8-9981-066d4696934f.png)

Callstack (@Blecki requested) 
``DwarfCorp.exe!DwarfCorp.CreatureMovement.GetNeighborhood(DwarfCorp.VoxelHandle Voxel) Line 254	C#
 	DwarfCorp.exe!DwarfCorp.CreatureMovement.<GetMoveActions>d__34.MoveNext() Line 297	C#
 	System.Core.dll!System.Linq.Enumerable.WhereEnumerableIterator<DwarfCorp.MoveAction>.MoveNext()	Unknown
 	DwarfCorp.exe!DwarfCorp.CreatureMovement.<GetInverseMoveActions>d__38.MoveNext() Line 687	C#
 	DwarfCorp.exe!DwarfCorp.AStarPlanner.InversePath(DwarfCorp.CreatureMovement mover, DwarfCorp.VoxelHandle startVoxel, DwarfCorp.GoalRegion goal, DwarfCorp.ChunkManager chunks, int maxExpansions, ref System.Collections.Generic.List<DwarfCorp.MoveAction> toReturn, float weight, System.Func<bool> continueFunc) Line 516	C#
 	DwarfCorp.exe!DwarfCorp.AStarPlanner.FindPath(DwarfCorp.CreatureMovement mover, DwarfCorp.VoxelHandle start, DwarfCorp.GoalRegion goal, DwarfCorp.ChunkManager chunks, int maxExpansions, float weight, int numPlans, System.Func<bool> continueFunc, out DwarfCorp.AStarPlanner.PlanResultCode resultCode) Line 677	C#
 	DwarfCorp.exe!DwarfCorp.PlanService.HandleRequest(DwarfCorp.AstarPlanRequest req) Line 83	C#
 	DwarfCorp.exe!DwarfCorp.Service<DwarfCorp.AstarPlanRequest, DwarfCorp.AStarPlanResponse>.Update() Line 196	C#
 	DwarfCorp.exe!DwarfCorp.Service<DwarfCorp.AstarPlanRequest, DwarfCorp.AStarPlanResponse>.ServiceThread() Line 157	C#
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()	Unknown``

Output:
``'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\Microsoft.Xna.Framework.Xact\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.Xact.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Xna.Framework.GamerServices\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.GamerServices.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\bin\x86\Release\LibNoise.dll'. Symbols loaded.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\bin\x86\Release\ICSharpCode.SharpZipLib.dll'. Module was built without symbols.
The thread 0x8a4 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
The thread 0x15c8 has exited with code 0 (0x0).
The thread 0x6e8 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
The thread 0xf44 has exited with code 0 (0x0).
The thread 0x227c has exited with code 0 (0x0).
The thread 0x138c has exited with code 0 (0x0).
The thread 0x1fc0 has exited with code 0 (0x0).
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Dynamic\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Dynamic.dll'. Cannot find or open the PDB file.
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
The thread 0x2408 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
The thread 0x188 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
The thread 0x2944 has exited with code 0 (0x0).
Exception thrown: 'System.NullReferenceException' in DwarfCorp.exe
An unhandled exception of type 'System.NullReferenceException' occurred in DwarfCorp.exe
Object reference not set to an instance of an object.``

No crash log produced.

27b0c862

**Comment by com1clyf3** [comment]
2. Original crash
![image](https://user-images.githubusercontent.com/6562812/42537732-c53b4df8-8463-11e8-9ca6-74f6d37421f3.png)

Didn't have time to collect other info at the time.

**Comment by mklingen** [comment]
Crashes unrelated to large dig tasks, and cannot reproduce them by creating large dig tasks. First crash is in the planner. Will try to address that one first.

**Comment by mklingen** [comment]
I'm getting sick of the "I made the whole world a dig task, why doesn't it work?" bugs. I'm just going to set a hard maximum limit on the number of dig tasks that maybe you can change in the settings.

**Comment by mklingen** [comment]
The first crash is a really tricky one. It seems to be related to threading, and maybe a creature dying while it's doing path planning. I'm putting in some more caching there to make that less of a problem. Nevertheless it's pretty worrying.

**Comment by mklingen** [comment]
Second crash is due to voxel designations deleting designations of another type (maybe farm designations) while the rebuild thread was attempting to access the list of designations. I made both threads now enumerate from a cached list to make that a little less likely.

**Comment by com1clyf3** [comment]
Regressing.

> I'm getting sick of the "I made the whole world a dig task, why doesn't it work?" bugs. I'm just going to set a hard maximum limit on the number of dig tasks that maybe you can change in the settings.

Still plan to do this?

As for large dig tasks, just tried one now and got no crash, but usual bad stuff: Not responding for ten seconds, a brief overheating, and then game coming back with slowed FPS.

**Comment by mklingen** [comment]
I have limited the number of dig and plant tasks to 1024.
