### ISSUE TITLE
Accessability: Add colorblind settings

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#795]
Number of options here if we want to do full support, as there are a few different kinds of color-blindness, but the lowest hanging fruit from my understanding is to introduce a gray scale mode, play it to make sure everything makes sense (preferably by someone with colorblindness), and then make any appropriate adjustments to UI. 

This Reddit thread has some good general info on what paths to take: https://www.reddit.com/r/gamedev/comments/1nkduo/adding_colourblind_modes_to_a_game/

**Comment by mklingen** [comment]
This feature is basically done. I just allow players to select the colors they want for most of the stuff we draw. Should be easy to add more categories as the pop up.

![color_picker](https://user-images.githubusercontent.com/241184/43049696-10da8656-8dca-11e8-9ff8-07ce71899f05.png)

**Comment by com1clyf3** [comment]
Sweet. Looks good!

**Comment by mklingen** [comment]
Colorblind profiles are now active. Would need feedback from an actual colorblind person on whether it's helpful, but we at least now have the framework in place.
