### ISSUE TITLE
Accessability:  Key remapping menu

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#796]
Being able to rebind the controls of the games to whatever keyboard keys (or combo of keyboard keys) the player wants. Generally this just looks like a list of player controls in a settings menu with a box displaying the default key used currently. The player would then click in that box and press whatever key(s) they wanted that control bound to.

**Comment by Blecki** [comment]
...look in the settings screen.

**Comment by mklingen** [comment]
This already exists? Every keybinding already uses this....
