### ISSUE TITLE
Zone: Can't build new balloon port after old balloon port blown up

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#798]
![image](https://user-images.githubusercontent.com/6562812/43019430-ed271526-8c2a-11e8-8ee4-e98cb7482fcc.png)

From Steam: https://steamcommunity.com/app/252390/discussions/0/1710690018665071800/

Will try for a repro soon.

**Comment by com1clyf3** [comment]
Found repro.

1. Start new game.
2. Destroy original balloon port.
3. Order a balloon port be built somewhere. Doesn't need to be over your original balloon port.
4. Cancel the balloon port task.
5. Try to plan another balloon port. Observe the game thinks there is already a baloonport built.

![image](https://user-images.githubusercontent.com/6562812/43021078-5ec29d04-8c30-11e8-9935-6a0549a115d0.png)

6f5bf6cf

**Comment by mklingen** [comment]
This is now fixed in master.
