### ISSUE TITLE
Art: Female dwarf art not being generated 

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#799]
Female dwarves are not being assigned female heads.

![image](https://user-images.githubusercontent.com/6562812/43020675-d78f7b0a-8c2e-11e8-95a0-073c81a8cd0b.png)

6f5bf6cf

**Comment by com1clyf3** [comment]
Found repro.

1. Start new game.
2. Destroy original balloon port.
3. Order a balloon port be built somewhere. Doesn't need to be over your original balloon port.
4. Cancel the balloon port task.
5. Try to plan another balloon port. Observe the game thinks there is already a baloonport built.

![image](https://user-images.githubusercontent.com/6562812/43021078-5ec29d04-8c30-11e8-9935-6a0549a115d0.png)

6f5bf6cf

**Comment by mklingen** [comment]
That is infact the female head.

**Comment by com1clyf3** [comment]
Oh! My bad then. Thought we had a more lipsticky mouth. Guess not.
