### ISSUE TITLE
Input dropped during poor performance

### ISSUE THREAD

**Issue by Blecki** [CompletelyFairGames/dwarfcorp#8]
The game uses a polling system and generates mouse and keyboard events from them. This means that it is easy to drop mouse clicks and key presses when performance is degraded. These should be switched to use the underlying OS message queues. For example, on windows, you can use a message filter to catch the actual mouse events, even when performance is degraded.

OS support will also allow proper detection of the actual symbol the player typed, rather than relying on a hardcoded if-else block that only works for American keyboards. See https://github.com/Blecki/GnomeColony/blob/master/GnomeColony/Gem/Common/KeyboardMessageFilter.cs for an example implementation handling keyboards.

I have this implemented for the windows version, including mouse events, and ready to go.

**Comment by mklingen** [comment]
Good idea.

**Comment by Blecki** [comment]
As I rewrite gamestates to use the new GUI, and the input queue that comes with it, this problem will disappear.

**Comment by com1clyf3** [comment]
Fix disabled pgup, pgdn, and e key.

**Comment by mklingen** [comment]
Ah, forgot to fix this for Gamemaster.

**Comment by com1clyf3** [comment]
Bug fixed. Pgup and pgdn still awaiting fix. Closing bug.
