### ISSUE TITLE
Sprint 1 July 29th to August 4th Dwarf Interaction 

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#801]
https://docs.google.com/document/d/1IE79bD78biPbuTgDVX8S12qd-HuN49_eMKnhGtuR6qw/edit?userstoinvite=mklingen89@gmail.com&ts=5b468953&actionButton=1#

1. Dwarf Interaction (customized dwarves).

- [x] New Dwarf art.*
- [x] Dwarf titles.
- [ ] Better Dwarf UI (for seeing their status and assigning them  jobs)*
- [x] Better notion of dwarf health and healing (dwarves should be able to heal other dwarves. Dwarves should get diseases from the environment and not at random).

**Comment by com1clyf3** [comment]
@mklingen Back from traveling. Where are we on this sprint's progress?

**Comment by mklingen** [comment]
New dwarf art is in. Custom dwarf titles are in. Dwarves now heal each other and can carry their friends to beds when they pass out.

Still missing

- Better Dwarf UI (unclear what this means still)
- Diseases from the environment

**Comment by com1clyf3** [comment]
@mklingen Want to cut these for now or carry them on to another sprint?

**Comment by com1clyf3** [comment]
Twas decided these last two are being added to the wishlist! Closing sprint now,
