### ISSUE TITLE
BUG: Trading Window Issue and No Sound

### ISSUE THREAD

**Issue by EvilEldy** [CompletelyFairGames/dwarfcorp#806]
I can only see the first word of any conversation with a trade caravan. And I have no sound

**Comment by Blecki** [comment]
The block menu should have arrows to scroll left and right. Can I get a
screenshot?

**Comment by mklingen** [comment]
> Make a way to remove the tresurary zone.
To delete any zone, go to the build menu, click "build zone" and then right click in any zone.

**Comment by mklingen** [comment]
> I am sure your aware of this.. i have one save that keeps crashing 5
minutes after loading. But it does have a large amount of small mining
operations.

That's not good. What is the error message?

**Comment by EvilEldy** [comment]
Log Name:      Application
Source:        .NET Runtime
Date:          8/4/2018 1:57:54 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-D3T44LT
Description:
Application: DwarfCorp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at DwarfCorp.CreatureMovement.GetNeighborhood(DwarfCorp.VoxelHandle)
   at DwarfCorp.CreatureMovement+<GetMoveActions>d__34.MoveNext()
   at
System.Linq.Enumerable+WhereEnumerableIterator`1[[DwarfCorp.MoveAction,
DwarfCorp, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=null]].MoveNext()
   at DwarfCorp.CreatureMovement+<GetInverseMoveActions>d__38.MoveNext()
   at DwarfCorp.AStarPlanner.InversePath(DwarfCorp.CreatureMovement,
DwarfCorp.VoxelHandle, DwarfCorp.GoalRegion, DwarfCorp.ChunkManager, Int32,
System.Collections.Generic.List`1<DwarfCorp.MoveAction> ByRef, Single,
System.Func`1<Boolean>)
   at DwarfCorp.AStarPlanner.FindPath(DwarfCorp.CreatureMovement,
DwarfCorp.VoxelHandle, DwarfCorp.GoalRegion, DwarfCorp.ChunkManager, Int32,
Single, Int32, System.Func`1<Boolean>, PlanResultCode ByRef)
   at DwarfCorp.PlanService.HandleRequest(DwarfCorp.AstarPlanRequest)
   at DwarfCorp.Service`2[[System.__Canon, mscorlib, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon,
mscorlib, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089]].Update()
   at DwarfCorp.Service`2[[System.__Canon, mscorlib, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon,
mscorlib, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089]].ServiceThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
   at
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
   at
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-08-04T18:57:54.200161700Z" />
    <EventRecordID>4692</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-D3T44LT</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: DwarfCorp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at DwarfCorp.CreatureMovement.GetNeighborhood(DwarfCorp.VoxelHandle)
   at DwarfCorp.CreatureMovement+&lt;GetMoveActions&gt;d__34.MoveNext()
   at
System.Linq.Enumerable+WhereEnumerableIterator`1[[DwarfCorp.MoveAction,
DwarfCorp, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=null]].MoveNext()
   at
DwarfCorp.CreatureMovement+&lt;GetInverseMoveActions&gt;d__38.MoveNext()
   at DwarfCorp.AStarPlanner.InversePath(DwarfCorp.CreatureMovement,
DwarfCorp.VoxelHandle, DwarfCorp.GoalRegion, DwarfCorp.ChunkManager, Int32,
System.Collections.Generic.List`1&lt;DwarfCorp.MoveAction&gt; ByRef,
Single, System.Func`1&lt;Boolean&gt;)
   at DwarfCorp.AStarPlanner.FindPath(DwarfCorp.CreatureMovement,
DwarfCorp.VoxelHandle, DwarfCorp.GoalRegion, DwarfCorp.ChunkManager, Int32,
Single, Int32, System.Func`1&lt;Boolean&gt;, PlanResultCode ByRef)
   at DwarfCorp.PlanService.HandleRequest(DwarfCorp.AstarPlanRequest)
   at DwarfCorp.Service`2[[System.__Canon, mscorlib, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon,
mscorlib, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089]].Update()
   at DwarfCorp.Service`2[[System.__Canon, mscorlib, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon,
mscorlib, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089]].ServiceThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
   at
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)
   at
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
</Data>
  </EventData>
</Event>

**Comment by EvilEldy** [comment]
Weird Dwarf Location. The dig blocks were added after finding him stuck and
there are no holes above him to fall into

**Comment by EvilEldy** [comment]
Found an intresting issue. If you layout a spot for baloon port over yet to
be built blocks it lets you create a baloon port below the min size. If you
delete the baloon port before completion. The game thinks there is one
still built.

**Comment by com1clyf3** [comment]
Regressing. @mklingen Take a look at this crash?

**Comment by mklingen** [comment]
Too many bugs listed here for a proper issue, and most don't have enough info to reproduce. I will look for the crash in sentry and create another issue for it.
