### ISSUE TITLE
Unable to pay tribute

### ISSUE THREAD

**Issue by EvilEldy** [CompletelyFairGames/dwarfcorp#808]
Unable to pay tribute to the goblins. The tribute button when clicked starts the dialog all over. The war button works and the dwarfs have been glorious at defending their stronghold so far. 

Attached is a screenshot of the goblin's demands....

![image](https://user-images.githubusercontent.com/42097361/44001949-be41999c-9e00-11e8-9b21-7822d74b1ad2.png)

**Comment by mklingen** [comment]
Fixed this in master. It was a problem with the new conversation system, and the variable `$envoy_demands_tribute` which was not being set. Fix will be in the next release.
