### ISSUE TITLE
Walk: Mouse icon not visible in Walk view 

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#815]
1. Enter walk view.
2. Move mouse. Observe that you can't see it.
3. Attempt to exit walk view. Observe showstopping bug that forces player to quit game.

1fb82458

**Comment by mklingen** [comment]
Lol not a bug, read the tutorial text. Press shift to use the mouse.

**Comment by mklingen** [comment]
I also made pressing ESC get you out of walk mode, for confused players.
