### ISSUE TITLE
Universal Selector: Multiple entity right click only gathers single entity

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#816]
Might be as designed, but expected behavior was:
1. Select lots of resources.
2. Right click on the selected resource.
3. Select gather.
4. Collect all selected.

Instead only the resource under the mouse was gathered.

1fb82458

**Comment by mklingen** [comment]
As designed. The stuff at the bottom is what you're supposed to be clicking. The right clicking stuff is for single items only.
