### ISSUE TITLE
GUI: All first items in a build menu have offset text

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#820]
![image](https://user-images.githubusercontent.com/6562812/44743082-799bb580-aacf-11e8-8a61-23e717e7fcf9.png)

![image](https://user-images.githubusercontent.com/6562812/44743159-b798d980-aacf-11e8-8473-2377e1a9dfb4.png)

![image](https://user-images.githubusercontent.com/6562812/44743173-c2536e80-aacf-11e8-90fd-fe0ef9f4c36c.png)

b8d13dd8

**Comment by Blecki** [comment]
I've seen this a few times lately. I believe it's a bug in the word
wrapping of the new fonts.

**Comment by com1clyf3** [comment]
Yeah. In general random things are offset. Figure I might as well track them.

**Comment by Blecki** [comment]
Unrelated, and it always being the first item was a coincidence; but regardless, fixed.
