### ISSUE TITLE
All generated worlds are over-populated with trolls

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#821]
Not a destructive bug, but not a wanted feature either.
![image](https://user-images.githubusercontent.com/6562812/44933507-4bb8aa00-ad37-11e8-893a-86fe95342874.png)

1. New game (advanced)
2. Generate World
3. Observe high amount of troll population. Continue making worlds to observe ongoing troll population explosion.

5bd9f3c4

**Comment by mklingen** [comment]
Ah, this is due to the new icons for creatures overwriting what's supposed to be a tree icon.

**Comment by mklingen** [comment]
Fixed in master.
