### ISSUE TITLE
Save/load: Saved games won't load

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#823]
![image](https://user-images.githubusercontent.com/6562812/44936490-f4b8d200-ad42-11e8-9d1e-49e83ce65317.png)

Try and load a current save (auto or otherwise). Observe  that game can't.

5bd9f3c4

**Comment by mklingen** [comment]
@Blecki seems like this is your doing? Is this currently fixed?

**Comment by mklingen** [comment]
Can't reproduce, so it's either been fixed or it only happens under certain circumstances.

**Comment by com1clyf3** [comment]
Seems fixed now. Whatever it was isn't reproing anyhow. But  i'll keep an eye on save/load this week.

cef3643e

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/44963744-89196500-aefa-11e8-8b49-934801567718.png)

Whatever it is, it has to do with saves from that previous version. Got this when trying to load a save from 5bd9f3c.

**Comment by Blecki** [comment]
Incrementing the version before release will render the old saves obsolete.
