### ISSUE TITLE
Crash: Loading an advanced world crashed to desktop  - System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#825]
![image](https://user-images.githubusercontent.com/6562812/45123781-0a107080-b136-11e8-88ff-ab73d461ebd1.png)

No repro crash occurred:

1. Quit game in this save: 
[Sea of Tin_6_Autosave.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2354723/Sea.of.Tin_6_Autosave.zip)

[Sea of Tin.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2354727/Sea.of.Tin.zip)

2. Went to advanced game menu, and decided to load Sea of Tin.

3. Crash to desktop

Log: [201809051801110970_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2354721/201809051801110970_Crashlog.txt)

Wasn't able to repro. I do notice that there's a substantial little pause when I press the Load World button, so guessing there's something happening there.

0cf60354

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/45125309-e94b1980-b13b-11e8-899f-7eeccfcb4ef0.png)

Got another.  Investigating if I've found a repro now.

**Comment by mklingen** [comment]
wasn't able to reproduce loading that file of yours, and the location of the crash isn't jumping out to me as a source of error. I'm worried there's actually another crash in a different part of the program, and threading is messing up the crash report.

**Comment by mklingen** [comment]
Ah, but you're running out of video memory. It's probably because this overworld is so huge. I wonder if it's actually the map icons that were causing this. #826

**Comment by com1clyf3** [comment]
Yeah. I just got a crash on a very low sized world, so I don't think we've figured this one out yet.

Got another no repro crash to desktop. Was generating worlds. This one specifically was very low sized with high population. Started game. Crash. No repro found.

> "System.ObjectDisposedException: Cannot access a disposed object."

Happened 

![image](https://user-images.githubusercontent.com/6562812/45389474-06736280-b5ea-11e8-966b-278ca3a34501.png)

[201809111737594511_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2372821/201809111737594511_Crashlog.txt)

0c9a7de8

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/45454743-ecea1d80-b6b2-11e8-9dcd-2133c5fca0a1.png)

[201809121737408551_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2376963/201809121737408551_Crashlog.txt)

Usual repro. Advanced world generated. Start game. Crash to desktop.

0c9a7de8

**Comment by com1clyf3** [comment]
Going to call this a low repro crash. Took me four tries to get one crash.

![image](https://user-images.githubusercontent.com/6562812/45455245-75b58900-b6b4-11e8-9dc9-e4edc5f3551a.png)
[201809121748192802_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2376990/201809121748192802_Crashlog.txt)

0c9a7de8


Output:
`'DwarfCorp.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\bin\x86\Release\DwarfCorp.exe'. Symbols loaded.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\Microsoft.Xna.Framework.Game\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.Game.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\bin\x86\Release\Steamworks.NET.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\Microsoft.Xna.Framework.Graphics\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.Graphics.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\Microsoft.Xna.Framework\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\bin\x86\Release\SharpRaven.dll'. Symbols loaded.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Xna.Framework.Input.Touch\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.Input.Touch.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\bin\x86\Release\Newtonsoft.Json.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Cannot find or open the PDB file.
Loaded settings {
  "TutorialDisabledGlobally": false,
  "ResolutionX": 1280,
  "ResolutionY": 600,
  "GuiScale": 1,
  "GuiAutoScale": true,
  "ChunkDrawDistance": 100.0,
  "VertexCullDistance": 1000.0,
  "AntiAliasing": 0,
  "Fullscreen": false,
  "EnableGlow": false,
  "DrawSkyReflected": true,
  "DrawChunksReflected": false,
  "DrawEntityReflected": false,
  "AmbientOcclusion": true,
  "CalculateRamps": true,
  "CameraScrollSpeed": 10.0,
  "CameraZoomSpeed": 0.5,
  "EnableEdgeScroll": false,
  "WorldScale": 4.0,
  "DisplayIntro": true,
  "MasterVolume": 0.0,
  "SoundEffectVolume": 1.0,
  "MusicVolume": 0.0,
  "CursorLightEnabled": true,
  "EntityLighting": true,
  "SelfIlluminationEnabled": true,
  "ParticlePhysics": true,
  "GrassMotes": true,
  "NumMotes": 512,
  "InvertZoom": false,
  "ChunkRebuildTime": 0.1,
  "ChunkUnloadDistance": 250.0,
  "DrawDebugData": false,
  "VisibilityUpdateTime": 0.05,
  "ChunkGenerateTime": 0.5,
  "FogofWar": true,
  "AutoSave": true,
  "AutoSaveTimeMinutes": 7.0,
  "SaveLocation": "",
  "VSync": true,
  "AllowReporting": true,
  "ZoomCameraTowardMouse": true,
  "CameraFollowSurface": true,
  "LocalModDirectory": "Mods",
  "SteamModDirectory": "C:/Program Files/Steam/steamapps/workshop/content/252390",
  "EnabledMods": [],
  "MaxSaves": 15,
  "EnableSlowMotion": false,
  "ConsoleTextSize": 1,
  "HoursUnhappyBeforeQuitting": 4.0,
  "Colors": {
    "Colors": {
      "Dig": [
        255,
        0,
        0,
        255
      ],
      "Farm": [
        50,
        205,
        50,
        255
      ],
      "Guard": [
        0,
        0,
        255,
        255
      ],
      "Attack": [
        255,
        0,
        0,
        255
      ],
      "Harvest": [
        144,
        238,
        144,
        255
      ],
      "Highlight": [
        139,
        0,
        0,
        255
      ],
      "Positive": [
        0,
        128,
        0,
        255
      ],
      "Negative": [
        255,
        0,
        0,
        255
      ],
      "Low Health": [
        255,
        0,
        0,
        255
      ],
      "Medium Health": [
        255,
        165,
        0,
        255
      ],
      "High Health": [
        144,
        238,
        144,
        255
      ],
      "Catch": [
        255,
        99,
        71,
        255
      ],
      "Gather": [
        255,
        69,
        0,
        255
      ]
    }
  },
  "Boredom_Gamble": -10.0,
  "Boredom_NormalTask": 0.1,
  "Boredom_Sleep": -0.1,
  "Boredom_ExcitingTask": -0.1,
  "Boredom_BoringTask": 0.5,
  "Boredom_Eat": -0.1,
  "Boredom_Walk": -0.2
} 
 C:\Users\kingofarabi1\AppData\Roaming\DwarfCorp\settings.json
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\Microsoft.Xna.Framework.Xact\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.Xact.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Xna.Framework.GamerServices\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.GamerServices.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\bin\x86\Release\LibNoise.dll'. Symbols loaded.
The thread 0x37c has exited with code 0 (0x0).
The thread 0x1c04 has exited with code 0 (0x0).
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\bin\x86\Release\YarnSpinner.dll'. Module was built without symbols.
The thread 0x1188 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
The thread 0x1394 has exited with code 0 (0x0).
The thread 0x1b9c has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
The thread 0x5f0 has exited with code 0 (0x0).
The thread 0x80c has exited with code 0 (0x0).
The thread 0x2328 has exited with code 0 (0x0).
The thread 0xa0c has exited with code 0 (0x0).
The thread 0x2850 has exited with code 0 (0x0).
The thread 0xa08 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
The thread 0x1f48 has exited with code 0 (0x0).
The thread 0x1088 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
The thread 0x138c has exited with code 0 (0x0).
The thread 0x19e0 has exited with code 0 (0x0).
The thread 0xc98 has exited with code 0 (0x0).
The thread 0x2304 has exited with code 0 (0x0).
The thread 0x1acc has exited with code 0 (0x0).
The thread 0x23f0 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
The thread 0x2428 has exited with code 0 (0x0).
The thread 0x204c has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
The thread 0xa9c has exited with code 0 (0x0).
The thread 0xaa4 has exited with code 0 (0x0).
The thread 0x177c has exited with code 0 (0x0).
The thread 0x510 has exited with code 0 (0x0).
The thread 0x1030 has exited with code 0 (0x0).
Exception thrown: 'System.ObjectDisposedException' in Microsoft.Xna.Framework.dll
Exception thrown: 'System.ObjectDisposedException' in Microsoft.Xna.Framework.dll
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Dynamic\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Dynamic.dll'. Cannot find or open the PDB file.
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'System.ObjectDisposedException' in DwarfCorp.exe
Exception thrown: 'Microsoft.Xna.Framework.Content.ContentLoadException' in Microsoft.Xna.Framework.Graphics.dll
Microsoft.Xna.Framework.Content.ContentLoadException: Error loading "Content\Sky\moon". GraphicsDevice component not found.
   at Microsoft.Xna.Framework.Graphics.GraphicsContentHelper.GraphicsDeviceFromContentReader(ContentReader contentReader)
   at Microsoft.Xna.Framework.Content.Texture2DReader.Read(ContentReader input, Texture2D existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.InvokeReader[T](ContentTypeReader reader, Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObjectInternal[T](Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T]()
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
   at DwarfCorp.AssetManager.GetContentTexture(String _asset) in C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\AssetManagement\AssetManager.cs:line 272
Exception thrown: 'Microsoft.Xna.Framework.Content.ContentLoadException' in Microsoft.Xna.Framework.Graphics.dll
The thread 0x2a98 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
The program '[6176] DwarfCorp.exe' has exited with code 0 (0x0).
`
Errors:
![image](https://user-images.githubusercontent.com/6562812/45455435-11df9000-b6b5-11e8-93fb-681bd3f8e581.png)
![image](https://user-images.githubusercontent.com/6562812/45455441-15731700-b6b5-11e8-9788-408d7641d636.png)

**Comment by com1clyf3** [comment]
Okay. Yup. I've found a repro. It's a little annoying.

1. Advanced game. Generate map. Change all the advanced settings. Start game.
2. Once in game, Quit game.
3. Repeat Steps 1 and 2 about three to five times.
4. Observe crash to desktop.

If it's a memory leak issue, I'm guessing it might take a lot more tries than my PC. If needed, I can do some profiling on it.

**Comment by com1clyf3** [comment]
Closing, since writing an updated related bug.
