### ISSUE TITLE
New Game: Too many icons on large world maps

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#826]
![image](https://user-images.githubusercontent.com/6562812/45124338-f36b1900-b137-11e8-938e-e2c58120d238.png)

When choosing from certain extreme maps, the map icons can completely blot out the map, unless the player is willing to room in and slowly click around. Allowing them to toggle the icons will give them a more flexible map generation experience.

0cf60354

**Comment by mklingen** [comment]
what... What?!? How did this happen? I've never seen anything like this before!

**Comment by mklingen** [comment]
Fixed. Problem was that tree spawn probability wasn't normalized by world size.
