### ISSUE TITLE
Design: Add exit to advanced gen menu

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#827]
![image](https://user-images.githubusercontent.com/6562812/45124423-4a70ee00-b138-11e8-8a98-29e362e546eb.png)

If the player accidentally clicks on the advanced menu, there is no way to exit this menu without completely destroying the map they already made.

0cf60354

**Comment by mklingen** [comment]
I'm more concerned with the fact that there are a billion icons on your screen

**Comment by com1clyf3** [comment]
Cool, but we fixed that.
