### ISSUE TITLE
Art: Water isn't rendering

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#828]
![image](https://user-images.githubusercontent.com/6562812/45124725-66c15a80-b139-11e8-8fcc-6a5fad422b4e.png)

![image](https://user-images.githubusercontent.com/6562812/45125005-9c1a7800-b13a-11e8-9835-6572befd2708.png)

Place a colony anywhere  near water. Observe that all the lakes, oceans, and streams are dry. 

0cf60354

**Comment by mklingen** [comment]
Fixed in master. The water was not getting generating due to height normalization.
