### ISSUE TITLE
Lava rarely does not spawn on vocanoes.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#829]
![image](https://user-images.githubusercontent.com/6562812/45182762-3b4d7700-b1f0-11e8-8295-433d8969a239.png)

![image](https://user-images.githubusercontent.com/6562812/45182940-aeef8400-b1f0-11e8-9e90-5d946da35d98.png)

a6e468d2

**Comment by mklingen** [comment]
This was fixed when I fixed #828

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/46041933-1c048400-c0e2-11e8-9b66-dd23641a003e.png)
Nope.

233bc5a8

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/46756345-366b5f80-cc95-11e8-8390-fd6a0004a6ef.png)

Appears that it's come back for some reason.

d75ada8b

**Comment by mklingen** [comment]
Can you provide a save file? I can't reproduce this at all.

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/47044627-b7779a80-d15e-11e8-8fb4-f126f90a9c2c.png)

Here's a save:

[Bead Realm_83_131841943784793647.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2484752/Bead.Realm_83_131841943784793647.zip)
[Bead Realm.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2484753/Bead.Realm.zip)

29d321c4

**Comment by mklingen** [comment]
Question, when you put a dwarf in there does he burn? I'm trying to determine if this is a graphical glitch or a generation problem. I suspect the former since I still can't reproduce this issue.

**Comment by com1clyf3** [comment]
Dwarf doesn't burn. There's no lava in effect or rendered as far as I can see.

**Comment by mklingen** [comment]
Okay, I've confirmed from that save there really is no lava in the volcano. Now to figure out why it sometimes doesn't spawn.

**Comment by mklingen** [comment]
Discovered the problem. This happens when you *load a world*. Something that I have almost never tried. Turns out information about where lava goes is completely missing from save files for worlds after we compressed them to 3 channel images. Bummer. I'm going to completely redo the way volcano lava works so that it just creates a shaft down to sea level in the middle.

**Comment by mklingen** [comment]
here's how volcanoes look now: a big shaft straight down into lava. I think it looks cooler and will also work with (new) saved overworlds.

![volcano_shaft](https://user-images.githubusercontent.com/241184/47262117-9fc94a80-d4ad-11e8-8fe1-b169cf98a8fb.png)
