### ISSUE TITLE
Text: Selector calls animal pens "fixtures"

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#830]
![image](https://user-images.githubusercontent.com/6562812/45184130-06432380-b1f4-11e8-8279-cb7cf7f4e33a.png)

1. Make some animal pens
2. Scroll over the fence
3. Observe the label "fixture"

a6e468d2

**Comment by Blecki** [comment]
Fixed in blecki-dev

![image](https://user-images.githubusercontent.com/1297068/45248672-2bae5b00-b2e2-11e8-887c-147c32afe59c.png)
