### ISSUE TITLE
AI: dwarfs getting stuck inside animal pens.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#831]
![image](https://user-images.githubusercontent.com/6562812/45184283-810c3e80-b1f4-11e8-9798-d791248483a4.png)

[Sea of Tin_603_131807403209938171.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2358713/Sea.of.Tin_603_131807403209938171.zip)
[Sea of Tin.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2358715/Sea.of.Tin.zip)

Somehow their bound is stuck  on there. Also observed traders waiting at animal pens as well.

![image](https://user-images.githubusercontent.com/6562812/45184419-dba59a80-b1f4-11e8-8690-86533d102160.png)

Hunting repro now.

a6e468d2

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/45184595-66869500-b1f5-11e8-93bf-5f7a04b52b17.png)


Caught them! They think animal pens are balloon ports, i think.

1. New game.  Get some dirt. Make an animal pen.
2. Make some tasks around the animal pen to get dwarves to walk back and forth around the pen.
3. Fast forward a bit, and observe them pathing to the animal pen to gamble. Then eventually not be able to path out.

**Comment by com1clyf3** [comment]
There might also be something going on with gamble?

So I got rid of every feasible obstacle and we've got this:
![image](https://user-images.githubusercontent.com/6562812/45186597-0b0bd580-b1fc-11e8-9b49-d0fe7d96ab36.png)
Those are two gambling dwarves. That third is the one who dug them out. They keep walking back and forth into this pit, stuck in a path loop.

![image](https://user-images.githubusercontent.com/6562812/45186652-35f62980-b1fc-11e8-8319-0a540fcca874.png)

Here's another. Never was stuck on anything, but seems to be stuck in gamble for eternity.

**Comment by Blecki** [comment]
Going to the animal pen to gamble is technically correct. They just go to the nearest room.

The rest though. There is a timer that should abort gambling if no other dwarves join the game. To be stuck, I'd think the dwarf would have to be continiously re-starting it.

**Comment by mklingen** [comment]
Found and fixed the bug.  It was caused by the context menu not realizing that dwarves should not be wrangleable. I bet that you at some point told dwarves to wrangle themselves, which causes this behavior.
