### ISSUE TITLE
Redesign: Put hire new employee first in the employee list

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#833]
![image](https://user-images.githubusercontent.com/6562812/45186192-a0a66580-b1fa-11e8-81ed-0dfd9b2b80a4.png)

We are kind of hiding this feature, and the more employees player gets, the more inconvenient it is. Let's list it first in the roster or make it its own button.

a6e468d2

**Comment by Blecki** [comment]
Good idea - it's done.

![image](https://user-images.githubusercontent.com/1297068/45248502-682c8780-b2df-11e8-828f-2a1a8773f138.png)
