### ISSUE TITLE
Settings / Design: Disable Kobold event during Tranquil Mode

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#835]
Kobold stole during tranquil mode. Seems we should either allow a non-harmful way of disposing of the Kobold, or disable kobold during tranquil mode. I suppose we could add some options like pay off kobold or maybe add an object that wards of kobolds?

a6e468d2

**Comment by Blecki** [comment]
Fixed in blecki-dev - Negative events (Kobolds, Gremlins, War Parties, Plagues) should not happen in tranquil mode. If they do it is a bug.
