### ISSUE TITLE
Trade: Auto trade should try harder to make more interesting trades.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#836]
![image](https://user-images.githubusercontent.com/6562812/45187484-c9c8f500-b1fe-11e8-907f-1b5508d6cd70.png)

1. Enter trade with a variety of resources
2. Press auto. Clear. Auto. Clear.
3. Observe Auto only produces trades of low amounts of wood, and doesn't use the players resoures effectively in trade.

a6e468d2

**Comment by Blecki** [comment]
Working as designed. The idea is that the player picks what they want, and the auto button puts up enough of their stuff to make the other party accept the trade. What we are seeing here is it coming up with a sort of 'minimal viable trade'.

A better option may be to simply tell the player they are doing something dumb when they click auto on an empty trade.

**Comment by mklingen** [comment]
@Blecki I think you renamed "What will make this work?" to "Auto".

**Comment by Blecki** [comment]
Oh yeah, to make it fit at low resolutions. How about just "make this work"?

**Comment by com1clyf3** [comment]
I'd suggest a few things.

1. Disable the auto button unless there is at least one thing proposed by the player in the trade UI.
2. Change the auto button's visual to show when it is disabled versus not.
3. "Make this work" should work, I think.

**Comment by Blecki** [comment]
Okay, I'll handle this.

**Comment by Blecki** [comment]
In blecki-dev.
