### ISSUE TITLE
Build: Cannot place ladder designation adjacent to voxel

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#837]
![image](https://user-images.githubusercontent.com/6562812/45187751-d3069180-b1ff-11e8-83c1-2b44e8d6f719.png)

Will not allow being placing ladder designation to complete this ladder.

![image](https://user-images.githubusercontent.com/6562812/45187802-fb8e8b80-b1ff-11e8-959f-f6b25340fe4f.png)

Will not allow placing ladder in spot left of ladder preview art in image.

1. Attempt to make a ladder near the corner of a square space such as show in image.
2. Observe building ladders is disabled when next to adjacent voxels.

a6e468d2

**Comment by Blecki** [comment]
Can't reproduce.

![image](https://user-images.githubusercontent.com/1297068/45248341-9610cc80-b2dd-11e8-9166-a7942f2ace62.png)

**Comment by com1clyf3** [comment]
Weird. I'll investigate a repro.

**Comment by mklingen** [comment]
Do you have a save of this that we can try?

**Comment by com1clyf3** [comment]
@mklingen Not totally sure, but pretty sure the save on #831 should be it.

**Comment by com1clyf3** [comment]
Found another. 

![image](https://user-images.githubusercontent.com/6562812/45459829-2d07cb00-b6c8-11e8-8cc8-1a525844416e.png)


[Argumentland_508_131812708378641162.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2377245/Argumentland_508_131812708378641162.zip)
[Argumentland.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2377246/Argumentland.zip)

0c9a7de8

**Comment by Blecki** [comment]
Can you get a screenshot with bounding boxes turned on?

Also try pressing r. Does it work when you override rotation?

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/45463050-97286c00-b6d8-11e8-8da2-21f269f000e0.png)
In this image, ladder can't be place to the left, where the red lines are extended from the blue bounding. Looks like it's the same all the way up, so that's prolly it. Red is some kind of orientation marker?

Rotating fixes it.

**Comment by Blecki** [comment]
If rotating fixes it, then is the cause not just that the default rotation
puts them in the same spot?

**Comment by Blecki** [comment]
Is it rotating to match the other walls automatically? That's expected.. it doesn't necessarily guess what the player intends correctly when it can snap to two or more walls.

**Comment by mklingen** [comment]
tried reproducing this myself and was unable to.

**Comment by com1clyf3** [comment]
Tried new build bdac6426
Still repros for me.

@Blecki Yes. It's rotating to match the other walls automatically. I'd suggest just trying it out. Go into a square/ rectangular shaft and trying making a ring of ladders without manually rotating.

**Comment by Blecki** [comment]
In that case it's working as designed. Building a ring of ladders will
require rotating them.

**Comment by com1clyf3** [comment]
Hmmm. But the weirdness is that if I set a ladder task for a wall that is autodirected, it works. But then if I go right next to it, it doesn't. So something is going on where the auto isn't valid any longer.

**Comment by Blecki** [comment]
It's auto directed to a different wall is all.

**Comment by com1clyf3** [comment]
Weird. Whelp, it's just a minor bug, so I'm gonna just make this a WNF and move on.
