### ISSUE TITLE
Graphics Issue

### ISSUE THREAD

**Issue by RandomWrapperDude** [CompletelyFairGames/dwarfcorp#838]
I was playing the game with some friends when one of them decided to change the resolution while I was gone. Currently, I am unable to access the graphics menu to change it back, as the resolution does not allow me to select the tab on the main menu with my mouse. 

![image](https://user-images.githubusercontent.com/43056780/45198245-994f7e00-b233-11e8-958f-8b4f4860c125.png)

As seen in the screenshot, the lowest my mouse is able to move at the selected resolution is not low enough to allow access to the options menu. When I attempt to move lower, my mouse moves out of the game's window. I am running the game through Steam, and re-installing the game does not help as the resolution selected seems to be saved. 

Trying to access the graphics menu from in a game also does not work, as the tabs at the top of the menu are off the main screen, and are unaccessable.

![image](https://user-images.githubusercontent.com/43056780/45198361-35798500-b234-11e8-8792-6039fa54134e.png)

Is there a file I can edit to set the resolution to my native resolution, or is another simple fix available?

**Comment by Blecki** [comment]
Look for the settings in users/your name/roaming/appdata/dwarfcorp.

**Comment by com1clyf3** [comment]
@RandomWrapperDude  Try the above suggestion for a short term solution.

For a long term solution, you are probably encountering #822 

We just fixed this the other day, and it'll be out wih our next release.

**Comment by Blecki** [comment]
Not related to that bug and there is no fix. What's probably happening is
the graphics device is offering resolutions it doesn't actually support. A
lot of cards will claim they support a resolution but actually use a higher
or lower one and stretch it to fit. Unfortunately the windows messaging
system will go ahead and use the resolution you actually asked for and then
the mouse won't be able to reach the whole screen... It's the same as the
bullshit Mac bug with retina screens. Afaik there's no way to detect it and
compensate, user just needs to pick a different resolution.

**Comment by RandomWrapperDude** [comment]
I edited the log file in the DwarfCorp appdata folder, just to see if it would change anything, it did not. But I just deleted the folder and the resolution returned to the default one after I reinstalled it. Thanks for the fix!
