### ISSUE TITLE
Art: Beartrap preview art doesn't show up on some terrrain

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#840]
![image](https://user-images.githubusercontent.com/6562812/45459188-29bf1000-b6c5-11e8-9ac2-671bc15e43b5.png)

Placing a beartrap when paused sometimes will not show the preview shadow. Looks like it is sometimes under the terrain art layer. Unpausing will fix the issue.
0c9a7de8

**Comment by Blecki** [comment]
Was not confined just to beartraps. It was perhaps more obvious with them because the actual graphic is so hard to see in preview mode. Should now be fixed for all shadows in general when paused.
