### ISSUE TITLE
Art: Voxels at top layer not rendering all faces

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#843]
![image](https://user-images.githubusercontent.com/6562812/45459967-f9797080-b6c8-11e8-85d0-d08dc27ae867.png)

0c9a7de8

**Comment by Blecki** [comment]
Wtf.

Repro?

**Comment by com1clyf3** [comment]
1. Build blocks to top layer of world.

**Comment by Blecki** [comment]
They're cut off by the slice plane. Suggest preventing construction in top
layer.

**Comment by com1clyf3** [comment]
Alright. Doesn't like a problem to me. Let's restrict construction up there,

**Comment by Blecki** [comment]
Done in blecki-dev
