### ISSUE TITLE
Cook: Repeat tasks show wrong number of tasks in confirmation message

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#844]
Going to the repeat drop down menu and selecting 5x/10x/100x whatever (meals, ales, or bakes) will result in a "Cooking One Meal", "Brewing One Ale", and "Baking One Bread".

1. Get resources to cook something.
2. Cook/Brew/Bake something in multiples by selecting from the repeat task option in the the drop down menu.
3. Observe the message does not detect the task larger than one you've selected, by printing a message referencing to just one cooking task.

1299186a

**Comment by Blecki** [comment]
Working correctly for both crafting and cooking. Some items may need to have their PluralDisplayName property set in the craft-items json to fix grammar as by default they just add an s.
