### ISSUE TITLE
Zones: Overlapping planned animal pens will delete one of the planned pens

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#847]
![image](https://user-images.githubusercontent.com/6562812/45572634-d0c3b900-b837-11e8-963a-44cac71f9053.png)

1. Plan an animal pen. Then plan an animal pen that overlaps the first.
2. Watch the first pen be crafted. 
3. Observe the second planned pen remove itself after the first pen is built.

1299186a

**Comment by Blecki** [comment]
No longer possible as rooms can't overlap.
