### ISSUE TITLE
Walk Mode: Player can walk OOW

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#853]
![oow](https://user-images.githubusercontent.com/6562812/45708306-0a096b00-bb4f-11e8-99a8-473e6e233428.gif)

Player can fall/walk out of world.  

1. Find a ridge on terrain.
2. Enter walk mode.
3. Go to the top of the ridge where terrain flattens out.
4. Walk back until you begin to fall. As soon as you begin to fall, push the camera forwards. You may also want to try jumping forwards, but just pushing forwards should work. 

012018c8

**Comment by mklingen** [comment]
I have fixed this in master, though in a bit of a hacky way.
