### ISSUE TITLE
New Game: Creating underground balloon port under the  sea breaks water physics

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#858]
[Important Hills_634_131822958134854525.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2412824/Important.Hills_634_131822958134854525.zip)
[Important Hills.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2412825/Important.Hills.zip)

1. Place your starting colony underground at sea.
2. Dig up to the water.
3. Observe the water doesn't flow down and fill any of the empty space.

233bc5a8

**Comment by com1clyf3** [comment]
Although prolly not too helpful, this kind of environment has a plethora of pathing issues too. Might be indicative of real bugs or not. Dunno.

[Important Hills_634_131822969978255534.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2412897/Important.Hills_634_131822969978255534.zip)
[Important Hills.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2412896/Important.Hills.zip)

**Comment by Blecki** [comment]
I'm calling this an Easter egg. How did you manage to not immediately die?

**Comment by com1clyf3** [comment]
I created an entire world like this. Anyone who thinks a little about the advanced settings can. 

As mentioned above, the water has no physics. When I dug up, the water didn't fall. It remains a single floating layer. Alternatively, a player could stay underground and never dig to the water anyway, but I wanted to see what would happen.

**Comment by Blecki** [comment]
Odd. Bug in the water sim then.

**Comment by mklingen** [comment]
Probably nothing triggers that layer to update, we probably only ever check adjacent blocks.

**Comment by mklingen** [comment]
Well, I tried this and nope you're not actually starting underground. You're starting underwater. Drawing is completely messed up, so you think you're seeing the surface but you're actually seeing water. Going to look at fixing.

**Comment by mklingen** [comment]
One interesting issue: if you start under a glacier, it will put you in the water below. I think the algorithm for starting underground should be redesigned to place you in the first stone layer beneath the surface.

**Comment by mklingen** [comment]
Fixed in master. Components of fix.

1. When starting underground, find the first rock layer and spawn 5 below that. before, it just naively looked for the first non empty voxel (including water).
2. Fix some camera issues while underwater.

As for the water physics, that is working just fine. It's slow, but it works. Water physics are expected to be much slower in the ocean, since there is so much more water than normal!
