### ISSUE TITLE
Redesign: Starting food doesn't last longer than a day

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#859]
Multiple Steam users have complained about the new game resources getting eaten too quickly. Tested it out, unless you're in a very habitable place with fruit trees, animals to kill, and so on, they're right. Starting underground, for instance, you will run out of food in less than a day unless you know what's up. 

I'd say let's just up the starting food resources. How about triple them to allow players a little starting time. I think you can keep it the same for hard difficulties.

233bc5a8

**Comment by mklingen** [comment]
okay I will increase the amount of food available.

**Comment by mklingen** [comment]
I've increased the starting layout on `normal` to 32 mushrooms and 16 ales.
