### ISSUE TITLE
Build: No preview for deleting block tasks

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#860]
1. Set some blocks to be built.
2. Right click and drag.
3. Observe that there isn't any art being rendered for selected block tasks to be canceled.

233bc5a8

**Comment by mklingen** [comment]
struggling to understand what you mean by this issue. What is "preview art"? When I right click and drag I see a little red dot on each thing that's supposed to be cancelled, which is as intended. When I release the mouse the artwork disappears, also as intended. Is it just that the dots need to be bigger, or you want some other style of artwork here?

**Comment by Blecki** [comment]
Changes to the voxel selector and build tool fixed this and made the behavior more user friendly.
