### ISSUE TITLE
Trade: Player can't hire new dwarves because game doesn't recognize balloonport

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#862]
From Discord. Looking into it.

> howdy  all.  anyone had any issues hiring dwarfs with the latest build
> ?
> keeps telling me i need a baloon port to hire, but im pretty sure ive got one
> PumpkinSpiceHamToday at 12:09 PM
> @HerbalArchenon  You still having an issue?
> HerbalArchenonToday at 1:27 PM
> Haven't played this evening but it was still happening when I played earlier.
> Tried demolishing the old one but that didn't help.
> PumpkinSpiceHamToday at 1:28 PM
> Hm
> This sounds like an old bug.
> You update your build?
> HerbalArchenonToday at 1:28 PM
> I have the diplomacy menu
> I reckon that's the most recent
> PumpkinSpiceHamToday at 1:29 PM
> You reckon accurately
> I
> will look into it
> Thanks for letting us know
> 

> And it was only when trying to hire new units that the port wasn't recognised. Trading worked fine, and it appeared in the zone list

233bc5a8

**Comment by com1clyf3** [comment]
Hiring is just plain broken.

1. New game.
2. Go to economy and try to hire any kind of dwarf.
3. Observe error message reporting dwarves can't be hired without balloonport (although port is already there).

**Comment by mklingen** [comment]
Pretty sure this is due to @Blecki renaming of `BalloonPort` to `Balloon Port` earlier. Will fix.

**Comment by mklingen** [comment]
fixed.
