### ISSUE TITLE
GUI: Zone task messages overlap map

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#864]
![image](https://user-images.githubusercontent.com/6562812/46103539-0f923100-c19f-11e8-8f29-f74da8d0177f.png)

1. Place some zones.
2. Move the task messages into the map. Observe the messages overlapping the map. The other menus occupy the front layer and the messages are hidden behind the GUIs.

233bc5a8

**Comment by mklingen** [comment]
Fixed.
