### ISSUE TITLE
Trade screen is confusing.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#866]
1. Open trade menu with an envoy. 
2. Try to give them some money for nothing in return and/or make a profitable trade and then up the Dwarfbux until the number turns red again.
3. Observe the trader prints a negative message when giving them more money than they asked for.

233bc5a8

**Comment by mklingen** [comment]
New artwork is looking good as well.
![balance_composite](https://user-images.githubusercontent.com/241184/46262389-6fa21380-c4ce-11e8-8140-2d325b3be273.png)
