### ISSUE TITLE
Task starvation (pun intended)

### ISSUE THREAD

**Issue by droe** [CompletelyFairGames/dwarfcorp#868]
The current task model (strict priority bands, each task type has hard-coded default priority, player can only influence priorities manually per task) leads to task starvation if the player has a play-style that avoids idling dwarfs. Task starvation leads to dwarf starvation because planting and harvesting have a low default priority. This is especially an issue early in the game when you cannot afford to have a dwarf exclusively for harvesting and food production. To survive, the player has to manually bump the priority on all food-related tasks as soon as they are generated. This is tedious and not fun.

The current situation seems to be a result of dealing with #649 in a way that I personally think makes the game worse. I find it much more playable with all tasks having the same default priority of medium. As a player I then have to simply gauge the size of my farms with my actual needs. That is fun. Constantly having to adjust individual task priorities manually is not.

Of course the situation is also avoided if the player never creates an actual backlog of tasks with medium or higher priority. However, that kills the fun for me too, because I cannot plan my digging ahead and I do not like useless idling dwarfs on my payroll.

While #859 and #867 address other factors that contribute to dwarf starvation, I feel that task starvation is a fundamental issue in the current strict priority band task model that should be addressed independently of the food-related fixes mentioned. Either task priorities should automatically be modified by the game based on player-adjustable strategic goals (like a player-configurable target number of food or beer that I want to have stocked, food-related task priority is higher if I am far from that target number). Additionally, there could be a round robin mechanism in the task scheduler that ensures that regardless of priorities, all task types are worked on from time to time, avoiding task starvation.

Another solution might be to allow the player to set the default priority for each task type during the game. This way the player can manually prioritize some tasks over others.

I propose the following:

1. Immediate fix: Move all tasks currently on low priority from low to medium priority to avoid dwarf starvation. Can submit a patch.
1. Long-term fix: Improve the task scheduler, either by avoiding task starvation generically, or by dynamically adjusting priority on all lower priority tasks based on needs or configurable targets, or both. Alternatively, make initial priority per task type configurable in the UI.

**Comment by mklingen** [comment]
Okay, for now I'm going to have most tasks default to medium except the urgent tasks such as "not dying" or "fighting this giant snake that's about to eat me".

**Comment by mklingen** [comment]
Most tasks have medium priority now. Exceptions include healing sick friends, running away from stuff, fighting creatures, going to sleep and getting something to eat.
