### ISSUE TITLE
GUI: Opening game menu will open random tutorials

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#871]
1. Start new game
2. Dismiss 1st tutorial
3. Press Esc to access the game menu. Observe that the Time tutorial opens up.
4. Exit menu and dismiss the tutorial. Press Esc again. Observe the Brush tutorial opens.

e8d2312b

**Comment by Blecki** [comment]
The time tutorial came up because you paused the game.

**Comment by com1clyf3** [comment]
Still doesn't explain the Brush tut.

**Comment by mklingen** [comment]
Brush and time tutorials are activated due to pressing ESC. This is intentional because pressing ESC activates the block brush. I'm going to prevent any tutorials from being displayed while the pause menu is active.

**Comment by mklingen** [comment]
Fixed in master.
