### ISSUE TITLE
Tut: Typo in death and stockpiles tutorial

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#873]
![image](https://user-images.githubusercontent.com/6562812/46372339-da7f5600-c658-11e8-952e-be224807a56e.png)

"That/'s bad news."

![image](https://user-images.githubusercontent.com/6562812/46375489-90e73900-c661-11e8-8b98-2873f85b3db7.png)

"... grab resources from stockpiles when they\'re needed."

e8d2312b

**Comment by mklingen** [comment]
Fixed.
