### ISSUE TITLE
Fast Forward: Skip to Day feature only moving an hour at a time

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#874]
1. Play game til skip to day message appears. Enable it.
2. Observe that it only move an hour forward (game time)
3. Click it again to observe same behavior

e8d2312b

**Comment by Blecki** [comment]
Able to replicate, but the logic around the feature is sound. What I noticed though was one of my dwarves waking up for a single frame every hour. So the bug is in the sleeping itself.

**Comment by mklingen** [comment]
Fixed this.
