### ISSUE TITLE
AI: Fleeing enemy causes dwarves to path to and fight enemy

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#879]
![image](https://user-images.githubusercontent.com/6562812/46380004-b595dd80-c66e-11e8-87de-cb286ac276c0.png)

Dwarves were all trying to kill this demon. I canceled the task. The redhighlight is no longer around the demon, however many dwarves still are attempting to perform the kill demon task.

[Family Reaches_4_131829918491655702.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2439898/Family.Reaches_4_131829918491655702.zip)
[Family Reaches.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2439899/Family.Reaches.zip)

e8d2312b

**Comment by com1clyf3** [comment]
Closing this for now. Not sure if it was a fluke or demon was just very very  high and away from camera.

**Comment by com1clyf3** [comment]
This is still occurring in b089ea7 . This time observed with snakes.

[Bead Realm.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2480855/Bead.Realm.zip)
[Bead Realm_53_131841185261470759.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2480856/Bead.Realm_53_131841185261470759.zip)

**Comment by com1clyf3** [comment]
Technically they have the flee task after canceling the attack, but they path to the enemy anyhow.

![image](https://user-images.githubusercontent.com/6562812/46983858-6c9f4980-d0b0-11e8-8e0b-c93e78de09a7.png)

**Comment by com1clyf3** [comment]
Still occurring in 2d713bbc

**Comment by mklingen** [comment]
I read this a little more carefully, and you seem to be describing not dwarfs running off to fight a creature, but rather dwarfs getting assigned a "Flee" task when another dwarf dies. This is a legitimate bug that I have now fixed.
