### ISSUE TITLE
Economy: If you destroy your treasury, Dwarfbuxs break

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#884]
Connected to #875 and reported in the Steam thread in that issue, this is a showstopping bug.

1. Start a new game,
2. Build a treasury.
3. Destroy original treasury, at your baloonport.
4. Gather dwarfbux pile. Oberseve it is in the overhead inventory GUI as an item. It will now be tradeable.
5. Observe the dwarf that gathers this will not then deliver it to the new treasury. The player from this point on is unable to actually hold any money in treasuries, making them unable to successfully use the trade feature, pay dwarves, buy items,etc.

b01a304e

**Comment by Blecki** [comment]
There must be more to this bug.

OR - it's already fixed.

I was not able to reproduce.

**Comment by com1clyf3** [comment]
It was repro'd in today's build, so it's not fixed.

**Comment by Blecki** [comment]
One hell of a corner case but I think I got it. It did not exist in my branch but did in master which helped track it down.
