### ISSUE TITLE
AI: Mole stopped multiple times to dig random blocks on its not especially difficult path

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#885]
![image](https://user-images.githubusercontent.com/6562812/46501026-4b0daa80-c7f2-11e8-95ec-3816610652de.png)

The mole envoy has stopped twice to dig at random blocks since entering the map. It's kind of comical, but dunno if this is intended behavior either. It'll take quite a long time for the mole envoy to reach player.

![image](https://user-images.githubusercontent.com/6562812/46501570-e3585f00-c7f3-11e8-8d71-7144e9dea409.png)
As long as I'm mentioning odd digging, in a natural cave below the mole is also this dwarf digging for no clear reason. Are they knowingly digging towards one another?  In general dwarves seem to path to this cave more often than they should, seeing as it's out of the way of the main tasks.

[Family Reaches_4_131831581576510680.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2448015/Family.Reaches_4_131831581576510680.zip)
[Family Reaches.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2448016/Family.Reaches.zip)

b01a304e

**Comment by com1clyf3** [comment]
Witnessed a Mole standing in lava, trying to dig.

**Comment by mklingen** [comment]
Moles now dig slightly less often.
