### ISSUE TITLE
AI: Water breaks scorpion/spider/rabbit pathing

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#887]
![image](https://user-images.githubusercontent.com/6562812/46502114-4e566580-c7f5-11e8-88b6-2a16b1a5f526.png)

Not totally sure how it happened naturally, but as far as I can tell a scorpion pathed a few blocks away from the shore and then became stuck on the water. Easy repro tho:

1. God mode some scorpions on the water
2. Observe some are stuck in place, unable to path out of the water

b01a304e

Edit: After some experimenting, seems this bug is at least affecting spiders/scorpions/ and (slightly) rabbits,

**Comment by mklingen** [comment]
spiders, scorpions and rabbits cannot swim. I should probably just make them die when they hit the water.

**Comment by mklingen** [comment]
spiders and scorpions now die when they are in water for too long. Rabbits can swim, and don't suffer this problem.
