### ISSUE TITLE
GUI: Bring all current expeditions to top of list

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#888]
In list of expeditions, current expeditions stay where the faction is originally located, meaning player might have to scroll to the very bottom to the list, back and forth, in order to compare current expeditions.

**Comment by Blecki** [comment]
I don't even know where this list is. XD

**Comment by com1clyf3** [comment]
The list of expeditions is the main menu of the diplomacy feature.

**Comment by Blecki** [comment]
Done.
