### ISSUE TITLE
AI: Dwarves will auto-dig next to a door, versus take the door

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#889]
![image](https://user-images.githubusercontent.com/6562812/46504524-21598100-c7fc-11e8-9b0d-6ae83f978686.png)

We should allow dwarves to check if there is a nearby entrance before digging a hole. At the every least check for a door.

At the moment if there is a one voxel deep wall that separatea them between  A room, and a hole already made with or without a door built (within a few voxels of them), the dwarves will (eventually) dig a new hole next to that hole. 

b01a304e

These pics are a row of doors as a result of dwarves continually digging holes (over time) next to established entrances, and me putting doors in their place.

![image](https://user-images.githubusercontent.com/6562812/46505407-01778c80-c7ff-11e8-8cd5-925a981536f1.png)

[Family Reaches.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2448257/Family.Reaches.zip)
[Family Reaches_4_131831637398320282.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2448258/Family.Reaches_4_131831637398320282.zip)

**Comment by mklingen** [comment]
so, this is a result of relaxing the constraints on digging. I can make digging a little more expensive to compensate. Before, it cost 1000, and now costs 100, so I will try some intermediate values.

**Comment by mklingen** [comment]
I've tuned the weights a bit, and while this does occasionally still happen dwarves will prefer to take doors now. However it's always a balancing act with these things and sometimes it might be desirable for the dwarfs to dig more.

**Comment by com1clyf3** [comment]
Yup. Polishing what seems the most urgent for release. Closing for now.
