### ISSUE TITLE
Trade: Holding arrow up/down in trade does not continue continue adding/subtracting DB

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#893]
1. Enter trade
2. Select DB GUI
3. Hold up or down area
4. Observe this no longer causes the number to go up or down more than 1 DB at a time

2c9141b4

**Comment by mklingen** [comment]
Keeping this one open as it will affect linux and mac.

**Comment by com1clyf3** [comment]
This is also occurring in XNA 29d321c4

**Comment by Blecki** [comment]
Not really a bug. GUI doesn't handle 'mouse held' at all. So, nothing is
technically broken.

**Comment by mklingen** [comment]
oh this is the mouse? I assumed this was the arrow key being held. In that case yeah it's not a bug, just a design feature.

**Comment by com1clyf3** [comment]
This isn't the mouse. I'm talking about holding down the arrow keys.

**Comment by mklingen** [comment]
If that's the case @Blecki seems that key repeat doesn't work in the FNA build right?

**Comment by Blecki** [comment]
It needs to be manually implemented in the input mapper for fna.

**Comment by mklingen** [comment]
@Blecki this is implemented right?
