### ISSUE TITLE
GUI: Task progress bars flicker on and off as dwarf performs a task

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#895]
Pick any task, and observe progress bar flicker on and off.

2c9141b4

**Comment by Blecki** [comment]
Can I just tag things NOMY? Is that allowed?

**Comment by com1clyf3** [comment]
Probably connected to my graphics issue, but also, make sure you're testing master?

**Comment by com1clyf3** [comment]
Also occurs on XNA

d75ada8b

**Comment by com1clyf3** [comment]
[Continent of Faucet_801_131836671272210057.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2466099/Continent.of.Faucet_801_131836671272210057.zip)
[Continent of Faucet.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2466100/Continent.of.Faucet.zip)

Checked on this. Doesn't happen in a fresh game. Only seems to occur once things have gotten more complicated. Try out these saves to observe.

**Comment by mklingen** [comment]
This is just the entities updating in chunks as intended. If this didn't happen you would have much worse performance.
