### ISSUE TITLE
Art: "Shadow dwarves"/ Users report sightings of dwarf sprites vanishing/ The XNA minimize bug

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#897]
Several steam users have reported seeing dwarf sprites vanish, leaving only their shadows, calling them "shadow dwarves", reminiscent of our re-occuring XNA problems. 

https://steamcommunity.com/app/252390/discussions/1/1730963192540672622/

This user reports it starting to occur an hour into the game.

Figured I'd make a bug for it, since we're working on it again.

**Comment by com1clyf3** [comment]
#692

**Comment by mklingen** [comment]
Closing as duplicate of #692.
