### ISSUE TITLE
Crash: User reported a repro crash after playing 15-20 minutes

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#898]
https://steamcommunity.com/app/252390/discussions/1/1730963192540672622/

https://www.dropbox.com/s/sqnzchwtzy1twou/DwarfCorp.zip?dl=0

Crashlogs and saves in link above.

**Comment by mklingen** [comment]
Fixed in master. This is due to a crash on load of a summoning circle that has zero charges.
