### ISSUE TITLE
CollideMinions uses worst possible case algorithm

### ISSUE THREAD

**Issue by Blecki** [CompletelyFairGames/dwarfcorp#9]
It is checking every minion against every other minion. Disabling this function (Just returning at the top and doing nothing) singlehandedly made the game playable.

**Comment by mklingen** [comment]
Yep, its bad, but there should only be like 5 minions to start with. For me this function takes a negligible amount of time and only starts being a problem after I have like 50 Dwarves. Is this in the monogame or XNA build? Are you in debug or release mode? Also what are your system specs?

**Comment by Blecki** [comment]
Assume my specs are the worst possible - barely runs at all.

It appears to be running on bats and woodland creatures as well as a separate faction. There were 73 bats when I looked in the debugger.

**Comment by mklingen** [comment]
Ha interesting. The function can be removed altogether. The only purpose of the function is to prevent dwarves from bunching up while they're wandering.

**Comment by yueranyuan** [comment]
The game runs pretty smoothly on my machine as well (my specs are also pretty good). I'm glad Blecki has a bad computer because otherwise performance testing will be a mere theoretical exercise.

**Comment by mklingen** [comment]
Closed for now.
