### ISSUE TITLE
Economy: Starting underground creates issues for hiring (and secondary bugs)

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#901]
1. Start underground (under an ocean for brownie points)
2. Hire a dwarf
3. Observe new hire cannot has some issues getting to baloonport

d75ada8b

If one starts underwater, you may observe a series of bugs, from the new hiring pathing odd, while swimming in water, to the water no longer rendering.
![image](https://user-images.githubusercontent.com/6562812/46753761-b215de00-cc8e-11e8-9874-7e2e68a727ba.png)

**Comment by mklingen** [comment]
Removing the underground feature.
