### ISSUE TITLE
Art: Spawning a small colony in the middle of a volcano will make no lave render

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#902]
![image](https://user-images.githubusercontent.com/6562812/46754041-6e6fa400-cc8f-11e8-986e-ccfcab49e763.png)

![image](https://user-images.githubusercontent.com/6562812/46753871-fdc88780-cc8e-11e8-9ac2-43367b7f6af3.png)

1. Place a small colony in a map that is %90 lava/orange on the biome map
2. Start game
3. Observe all lava is not rendered

d75ada8b

**Comment by com1clyf3** [comment]
#829

**Comment by mklingen** [comment]
Fixed.
