### ISSUE TITLE
Crash: System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Effect'

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#903]
![image](https://user-images.githubusercontent.com/6562812/46754328-3157e180-cc90-11e8-9547-efa410e1807b.png)

[201810101323270652_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2465728/201810101323270652_Crashlog.txt)

Not totally sure where to start with this one. Just logging info for now, until I catch another instance. Believe it started when loading a world, but was looking away for a second.

d75ada8b

**Comment by mklingen** [comment]
Same issue as the minimization problems. Graphics device has gotten disposed.

**Comment by mklingen** [comment]
I fixed this particular crash. I also made a tool to trigger these events more reliably to make sure the game can handle them. While in debug mode and playing the game, you can press the HOME key to trigger a graphics device reset. Pressing it too frequently will result in an `InvalidOperationException`, so I'd press it about once per second for a realistic idea of what graphics device resets will do to the game. I also fixed several more instances of artwork disappearing and crashes using this tool.
