### ISSUE TITLE
Performance: Trade envoy event spawning  to an underground colony causes lag

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#904]
1. Start an underground colony
2. God mode trade envoy
3. Observe performance data. Observe drop in FPS . Mine went from about 15-18 to 2-5 for about two seconds. When game is busier, can be a more noticeable lag.

Anyways, worth looking into.

d75ada8b

**Comment by mklingen** [comment]
I'm going to remove the "start underground" feature, as it breaks many things.

**Comment by mklingen** [comment]
Starting underground disabled.
