### ISSUE TITLE
Dwarfs: GUI gets stuck if present dwarf is sent on diplomacy mission

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#906]
Very minor bug.

1. Open Dwarfs menu. Observe which dwarf is being presented.
2. Open diplomacy and send this dwarf on a mission
3. Return to Dwarfs menu. Press arrows and observe that dwarf won't change. Close and open menu to observe dwarf won't change. Select an dwarf sprite to correct bug.

d75ada8b

**Comment by mklingen** [comment]
Fixed in master.
