### ISSUE TITLE
GUI: X-ray overlaps time gui at 600x800 res

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#909]
![image](https://user-images.githubusercontent.com/6562812/46763813-c4047a80-cca8-11e8-89e7-d869cf924734.png)

d75ada8b

**Comment by mklingen** [comment]
I'm gonna remove 800 x 600.

**Comment by mklingen** [comment]
Minimum GUI size is now 1280 x 720.
