### ISSUE TITLE
Move libraries to data files

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#91]
Currently the static data associated with rooms, voxel types, etc. are mostly generated at runtime with harcoded C# structures. Ideally these should be in data files instead so that we're not tempted to hardcode special cases for different kinds of rooms/entities/voxels.

- [ ] RoomLibrary -- A collection of room types and objects that spawn in the rooms
- [ ] ResourceLibrary -- A collection of the different resource types (wood, stone, etc.) and their properties
- [ ] CraftLibrary -- a collection of objects that can be crafted and the requirements for crafting them
- [x] VoxelLibrary -- a collection of Voxel types and their metadata
- [ ] PrimitiveLibrary -- a collection of 3D primitives (meshes) generated at runtime for trees, beds, etc.
- [x] ParticleManager -- a collection of particle effects. (BONUS: could write an editor for these)
- [ ] EntityFactory -- all the entities that can be created in the game. Likely only small parts of this can be converted into data files (perhaps some of the more simple Fixtures)
- [x] BiomeLibrary -- this has already been converted. A collection of Biomes and their properties.

**Comment by com1clyf3** [comment]
Was this ever finished? If so, go ahead and close the issue.

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/39261235-dfb47210-4889-11e8-8ca1-9bd1e922488e.png)
