### ISSUE TITLE
Crash: When a diplomatic mission returns to a colony with no balloonport game crashes to desktop

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#910]
![image](https://user-images.githubusercontent.com/6562812/46764206-d59a5200-cca9-11e8-9fb8-e11dfbf3f04f.png)

[201810101627196827_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2466390/201810101627196827_Crashlog.txt)

1. Send off a diplomatic mission
2. Wait til they are coming back
3. Destroy balloon port
4. Observe crash to desktop when mission returns

d75ada8b

[in case you need a spot right before a colony returns]
[Land of Keyrunner_399_131836767638921832.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2466410/Land.of.Keyrunner_399_131836767638921832.zip)
[Land of Keyrunner.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2466413/Land.of.Keyrunner.zip)

**Comment by mklingen** [comment]
Fixed.
