### ISSUE TITLE
Farm: Can't plant in soil next to zones 

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#933]
1. Build any zone next to some soil
2. Try to farm in the soil directly outside of the zone
3. Observe that player can't farm next to zones

b089ea7a

**Comment by com1clyf3** [comment]
Figured it out. You can't build soil objects with dark soil

**Comment by mklingen** [comment]
I think you meant to post that comment in response to #932 . The farming next to a zone seems to be a problem with bounding box checks on the farm tool. @Blecki want to fix that again? Pretty sure it was a bug in the past that we fixed and then it somehow regressed.

**Comment by com1clyf3** [comment]
You right about #932 Too many open tabs.

Yeah. I would guess this is a regression as well.

**Comment by Blecki** [comment]
![image](https://user-images.githubusercontent.com/1297068/47259347-56113d80-d476-11e8-94e8-a95d8c9d0a65.png)

For some reason zone bounding boxes are expanded when checking for collision with them. I don't know why, or what would break if I fixed it, so I shrunk the bounding box the farm tool uses to check instead.
