### ISSUE TITLE
AI: Dwarf sprites flicker between sleeping and walking art while pathing is generally breaking

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#936]
![image](https://user-images.githubusercontent.com/6562812/46982767-a457c280-d0ab-11e8-955a-4a34c6052bf1.png)

No repro yet. So far observing two dwarves here doing it, which is in the save. The changing art appears as a moving flicker, unless you pause at the right time. Their general pathing is odd too. Just observed them walk back and forth in the same loop, almost synchronized. From what I can tell from their task info, looks like something is going on inbetween wanting to fall asleep and gamble, so I'll look there.

[Bead Realm_53_131841177200369796.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2480827/Bead.Realm_53_131841177200369796.zip)

[Bead Realm.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2480829/Bead.Realm.zip)

b089ea7

**Comment by mklingen** [comment]
Their energy is high, so they're not sleeping.  Their health is fine so they shouldn't be unconscious. Difficult problem. Will take a look at your save.

**Comment by mklingen** [comment]
Thanks for the save, I fixed it!

This was caused by a comedy of errors. Root cause was me trying to fix #908 and realizing that dwarves were randomly waking up in the night. My fix caused them to not realize they were supposed to be awake during the day. This was competing with another system that was telling them to be awake to complete tasks. The result was the dwarf constantly waking up and falling back asleep, which was causing their tasks to fail.

**Comment by com1clyf3** [comment]
Another version of this occurring. A dwarf is sleeping while brewing. Sprite flickers.

![image](https://user-images.githubusercontent.com/6562812/47545066-510a1f00-d8b8-11e8-8924-2aba2c3681f1.png)

[Giruholand_34_131850025034408785.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2517721/Giruholand_34_131850025034408785.zip)
[Giruholand.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2517719/Giruholand.zip)

77e0c8e8

**Comment by mklingen** [comment]
Instead of opening old bugs can you create new ones?

**Comment by com1clyf3** [comment]
Sure. Looking over the newest first I gather?

**Comment by com1clyf3** [comment]
#967 #968
