### ISSUE TITLE
Design: Turn down high-level enemy spawns in normal difficulty

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#937]
My colony was attacked by six snakes on my first day. Let's turn that down a bit or maybe add a restriction to only spawn snakes on normal or lower after, let's say, the first three days?

b089ea7

**Comment by mklingen** [comment]
Snakes are no different than any animal, so the game will spawn them randomly. To support this we need a better way of telling which enemies are the hardest and spawning them in increasing difficulty.

**Comment by com1clyf3** [comment]
Can't we just make a list of high difficulty enemies (we don't have many), and then restrict their spawning until a certain time stamp? Then just attach that to normal and below difficulty.

**Comment by mklingen** [comment]
Yeah can do. Will look into it.

**Comment by mklingen** [comment]
I've done the following:

1. Snakes now migrate out of the world when there are more than 5.
2. No more than 4 snakes get spawned per biome (excluding Hell).
