### ISSUE TITLE
Low Repro Crash: Graphics Device disposed after pressing start game in Advanced map menu

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#938]
![image](https://user-images.githubusercontent.com/6562812/47046469-27881f80-d163-11e8-9f80-052f94a021cc.png)

[201810161643433159_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2484851/201810161643433159_Crashlog.txt)

No repro as of yet. This is how it orginally occurred:
1. New Game
2. Load World (below)
3. Selected a spot over a mountain  with cave and waste biomes with a large colony, and lots of caves.
4. Start game
5. Crash to desktop

[Bead Realm.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2484860/Bead.Realm.zip)

29d321c4

**Comment by com1clyf3** [comment]
Possibly #918

**Comment by mklingen** [comment]
This has been fixed. Unlike all other game states, the Intro state lacked a guard for disposed graphics device.
