### ISSUE TITLE
AI: Dwarves will auto-dig a player built block

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#939]
![image](https://user-images.githubusercontent.com/6562812/47050858-e8ac9680-d16f-11e8-8305-d07d3d228a9d.png)

Built a wall and dwarves dug right through it. Building a top-down fort where dwrves must climb up to a porthole, and then climb down, versus pathing horizontally.

Probably should just make them respect all player built blocks, unless pathing really fails to find any other way,

29d321c4

**Comment by mklingen** [comment]
I'll think about it.

**Comment by Blecki** [comment]
We are currently tracking the 'player built - ness' of all voxels so the bookkeeping to implement this exists.

**Comment by mklingen** [comment]
This is fixed now.
