### ISSUE TITLE
Mismatch between map preview and actual world after creation.

### ISSUE THREAD

**Issue by Solsund** [CompletelyFairGames/dwarfcorp#94]
After creating multiple worlds to test out the water system I realized that the water level seemed to be lower on the actual created world than it was on the preview screen.  This might go further than just a water level issue as even the types of land created were different.

![worldmismatch1](https://cloud.githubusercontent.com/assets/6342605/22783757/d0208f02-ee92-11e6-9c10-8e88485929b3.jpg)
![worldmismatch2](https://cloud.githubusercontent.com/assets/6342605/22783758/d02402d6-ee92-11e6-94d3-98bbca85b533.jpg)

**Comment by mklingen** [comment]
Seems to be an off-by-one issue in integer rounding the sea level. You can see that the sea level is intended to be just one voxel higher.

**Comment by mklingen** [comment]
Fixed by #96
