### ISSUE TITLE
Build: Placing pre-existing built objects breaks after placing a pre-existing Cutting Board

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#942]
1. Spawn and or build a cutting board
2. Destroy and gather cutting board
3. Build this existing cutting board
4. Build another object, destroy and gather it
5. Place this already existing object
6. Observe the craftdwarf will not take on the task

2d713bbc

**Comment by Blecki** [comment]
I was able to duplicate without the initial steps.

What was happening was the task was checking to see if you had the resources to build the item from scratch - so if you did not, it refused even though you had the item itself.
