### ISSUE TITLE
CTD Error on Fedora 28

### ISSUE THREAD

**Issue by alexpattyn** [CompletelyFairGames/dwarfcorp#943]
OS: Fedora 28 Silverblue
CPU: Ryzen 5 1600
GPU: RX 580  (POLARIS10 / DRM 3.26.0 / 4.18.13-200.fc28.x86_64, LLVM 6.0.1)

Got the following error when launching the newest release (18.10.17)
![screenshot from 2018-10-19 19-06-26](https://user-images.githubusercontent.com/28536677/47247562-7d163380-d3d2-11e8-8ec5-dd9826231142.png)

**Comment by mklingen** [comment]
I'm sorry. Is this happening on every launch for you? Or is this something you saw one time?

**Comment by koenigjaeger** [comment]
Looks like just a one time thing. I'll play a game soon and see if any other errors pop up. But you can close the issue.

**Comment by mklingen** [comment]
If it's a one time thing it's still a bug that needs addressing. I'll look for possible causes.

**Comment by koenigjaeger** [comment]
Okay, thanks! I did upgrade from a previous version so I am not sure if that will affect anything in this case. 

Also I just had a CTD after playing for ~1hour. Is there a place where these get automatically saved so I can make a new issue and upload the error?

**Comment by mklingen** [comment]
In linux I believe it ends up getting saved to `~/.local/share/DwarfCorp`

**Comment by com1clyf3** [comment]
@koenigjaeger ^ As mentioned, crash logs will not be in your Steam folder usually. Try the suggested path above.

**Comment by koenigjaeger** [comment]
@com1clyf3 I did for this issue https://github.com/CompletelyFairGames/dwarfcorp/issues/945. I didn't see anything related for the OP issue in this current thread, but I would have to check again.

**Comment by alexpattyn** [comment]
Haven't experienced this issue in since I opened the issue. Following in https://github.com/CompletelyFairGames/dwarfcorp/issues/945 Fedora 28 is EOL so I'll close this issue unless I see it the next time I play.
