### ISSUE TITLE
CTD During Game Play [Fedora 28]

### ISSUE THREAD

**Issue by alexpattyn** [CompletelyFairGames/dwarfcorp#945]
OS: Fedora 28 Silverblue
CPU: AMD® Ryzen 5 1600 six-core processor × 12 
GPU: Radeon RX 580 Series (POLARIS10 / DRM 3.26.0 / 4.18.13-200.fc28.x86_64, LLVM 6.0.1)
Flatpak version of steam (https://flathub.org/apps/details/com.valvesoftware.Steam)

Got a crash to desktop after ~1hr of playing. the following was logged...
[log_error.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2500025/log_error.txt)

A file in .local/share/Dwarfcorp/Logging was created called 201810181806380296_Crashlog.txt with nothing in it; size was 0 bytes.

If anything else is useful let me know (i.e. saves)

**Comment by mklingen** [comment]
Okay, sadly there's nothing useful in that log. It didn't pop up a dialog box by chance? Looks like it crashed out before it could write the crash log even.

**Comment by koenigjaeger** [comment]
Nothing that I remember. I believed it just crashed. I can try and load the save and see if it happens again.

**Comment by alexpattyn** [comment]
Fedora 28 is EOL therefore I'll close the issue. If I see it on Fedora >= 30 I'll reopen.
