### ISSUE TITLE
Art: Lava spawns as a single layer, floating above an empty cavern

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#946]
![image](https://user-images.githubusercontent.com/6562812/47378364-e42f3300-d6c5-11e8-9835-b9d846662ef2.png)

We should fill the rest of the cave with lava, yeah?

27c42f81

**Comment by mklingen** [comment]
The rest of the cave is filled with lava. (if you put a dwarf down there he will burn). We only draw the top surface of the lava for obvious reasons. We don't have any kind of volumetric renering system for water or lava.
