### ISSUE TITLE
Crash: System.ArgumentOutOfRangeException when holding down mouse in trade screen

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#948]
![image](https://user-images.githubusercontent.com/6562812/47378906-76840680-d6c7-11e8-8278-d8af7f619a88.png)

Got this crash on 27c42f81

[201810231323274044_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2507259/201810231323274044_Crashlog.txt)

Occurred while holding the mouse down on a resource in the trade menu in order to increase the number of resources traded. Then a crash to desktop.

**Comment by com1clyf3** [comment]
Trying for a simple repro of holding down mouse on resource, and so far nada.

**Comment by mklingen** [comment]
Fixed. This was caused by holding SHIFT or CTRL while also holding the mouse button, and only for columns in the middle. In this corner case more than 1 item is removed at a time, and the mouse holding logic didn't consider this.
