### ISSUE TITLE
Dwarfs try to hard to fight demons in the air.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#950]
![image](https://user-images.githubusercontent.com/6562812/47394303-69c7d880-d6f0-11e8-8c2d-75aa43ca2fa3.png)

Dwarves became stuck pathing upwards for about a minute. All their sprites remained in place. Eventually they gave up on their paths and moved on, but it appears they were all trying to path out of the world. I think these were also all newly hired dwarves as well, which had come in a group about ten minutes before save.

Could be connected to #846 or recent fixes on #944 

[Giruholand_34_131847996771433191.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2508280/Giruholand_34_131847996771433191.zip)
[Giruholand.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2508283/Giruholand.zip)

27c42f81

**Comment by mklingen** [comment]
What do you expect the dwarfs to do? Demons are flying creatures, so if dwarfs want to fight them, they have to make a best effort to get near them.

**Comment by mklingen** [comment]
I can just make fighting creatures just give up if the creature they're fighting flies too far above the ground I suppose.

**Comment by mklingen** [comment]
Okay, examining this save, the problem isn't that they're trying their best to fight the demon, the problem is that the logic for determining when to replan is broken for flying targets.

**Comment by mklingen** [comment]
Fixed (in the sense that they won't stand around replanning forever, but they will chase demons to the ends of the earth to kill them).
