### ISSUE TITLE
New Game: Ladders no longer auto-generate at baloonport

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#954]
![image](https://user-images.githubusercontent.com/6562812/47454696-d5b44a80-d79d-11e8-8c15-0d38ce4761cd.png)

When player starts new game, player will observe ladders no longer auto generate at their colony baloonport. 

@mklingen  I remember you touching a bug related to this. Is this intentionally disabled?

cf5eaf96

**Comment by mklingen** [comment]
It was to fix #931 , but maybe that was too aggressive...

**Comment by mklingen** [comment]
Fixed.
