### ISSUE TITLE
Diplomacy: Sending a selected dwarf on a mission will leave behind selection UI art

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#955]
![image](https://user-images.githubusercontent.com/6562812/47454934-79055f80-d79e-11e8-8dd7-91f05c75edd0.png)

1. Select a dwarf with your mouse, so it has a UI circle around it.
2. Go into diplomacy menu and send this dwarf on any mission.
3. Observe the circle from the selection UI is leftover after the dwarf sprite is no longer rendered. 

cf5eaf96

**Comment by mklingen** [comment]
Fixed.
