### ISSUE TITLE
Crash: Player reported - NullReferenceException - PlantGrowthTower /OctTree

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#956]
![image](https://user-images.githubusercontent.com/6562812/47457592-7ce8b000-d7a5-11e8-8454-dcb9195917a5.png)

https://steamcommunity.com/app/252390/discussions/1/1730963192540672622/

Follow link for logs and saves: https://steamcommunity.com/linkfilter/?url=https://www.dropbox.com/s/mp3vj5bxyhuxb16/DwarfCorp%2018.10.01.zip?dl=0

**Comment by mklingen** [comment]
They are, but I bet crash logs aren't working anymore.

**Comment by com1clyf3** [comment]
I mean, I still get them, but not for every crash, so yeah. Probably could use a look. I'll make a bug for it.

**Comment by com1clyf3** [comment]
It's also very possible they gave us the wrong crash logs.

**Comment by mklingen** [comment]
I wasn't able to reproduce any crashes in this save. I did see other unrelated issues however which I have fixed.

**Comment by com1clyf3** [comment]
@mklingen What are you talking about? These logs say 2018 and the .log has output from 2018 sessions.

**Comment by mklingen** [comment]
Sorry I meant September 2018.

**Comment by mklingen** [comment]
Underlying crashes in those logs have been fixed anyway.
