### ISSUE TITLE
Production: Crash logs are broken

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#957]
Investigate crash log feature for bugs, given that many people are not receiving logs during heir crashes.

**Comment by mklingen** [comment]
I believe that if crash reporting is enabled, crash logs are not produced. I think that's intentional, but perhaps it should do both.

**Comment by com1clyf3** [comment]
I'd definitely suggest doing both. We fix player reported crashes way faster than auto-reported crashes.

**Comment by mklingen** [comment]
I agree, I will make it always spit out crash logs.

**Comment by mklingen** [comment]
Crash logs now get written for all release builds.
