### ISSUE TITLE
AI: Moleman dig when auto-dig is turned off

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#960]
![image](https://user-images.githubusercontent.com/6562812/47530926-0669b200-d87a-11e8-871e-dffd483fae77.png)

Player reported mole people auto-digging when they had toggled it off.

**Comment by mklingen** [comment]
Not a bug. Mole men are just like that.

**Comment by mklingen** [comment]
Btw since the last release I made mole men dig slightly less. But again, that's just how molemen are, they like digging!
