### ISSUE TITLE
AI: Yufmum becomes stuck floating in a sitting position above empty hole

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#962]
Somehow our friend Yufmum the dwarf ended up stuck in a sitting position above a hole in the dirt, unable to path away. Canceling their task will free them. However they will end up floating above a few other holes. Unclear repro.

[Giruholand_34_131849986779065720.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2517595/Giruholand_34_131849986779065720.zip)
[Giruholand.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2517596/Giruholand.zip)

77e0c8e8

**Comment by mklingen** [comment]
Fixed in master. Problem was dwarf not setting his animation properly when digging.
