### ISSUE TITLE
Build: Move object breaks in save

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#964]
No idea what broke move object, but so far have only observed it broken in the save below. Not broken in a new game, and not broken in older saves. Will hunt repro.

1. Move a built object with move tool
2. Observe it highlights blue but can't be dragged

[Giruholand.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2517687/Giruholand.zip)
[Giruholand_34_131849986779065720.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2517688/Giruholand_34_131849986779065720.zip)

77e0c8e8

**Comment by mklingen** [comment]
Bug definitely persists on all saves. Good catch. For some reason `CraftDetails` isn't getting serialized. Will investigate.

**Comment by mklingen** [comment]
@Blecki has discovered a fix. This is due to the build tool erroneously setting the preview body to not be serialized -- this infects the `CraftDetails` component which then doesn't get saved.
