### ISSUE TITLE
AI: One member of elf envoy correctly pathed through door to balloonport and other members decided to dig a path

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#965]
![image](https://user-images.githubusercontent.com/6562812/47545668-7187a880-d8bb-11e8-9b14-b7f87d6662a6.png)
![image](https://user-images.githubusercontent.com/6562812/47545672-7c423d80-d8bb-11e8-84fc-b24d5038230e.png)

Elven trade envoy approached. First two members decided to dig through wall. Last member found the door at the bottom of structure and went right to balloonport. Perhaps add logic check to see if other members have pathed successfully, and if so, path to them?

[Giruholand.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2517777/Giruholand.zip)
[Giruholand_34_131850025034408785.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2517778/Giruholand_34_131850025034408785.zip)

77e0c8e8

**Comment by mklingen** [comment]
> Perhaps add logic check to see if other members have pathed successfully, and if so, path to them?

Nope. Way too hard.

> Elven trade envoy approached. First two members decided to dig through wall. Last member found the door at the bottom of structure and went right to balloonport.

Not surprising. The heuristic weight is randomized.

Not a bug.
