### ISSUE TITLE
AI: Dwarf sleeping while brewing

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#967]
Another version of this occurring. A dwarf is sleeping while brewing. Sprite flickers.

![image](https://user-images.githubusercontent.com/6562812/47545066-510a1f00-d8b8-11e8-8924-2aba2c3681f1.png)

[Giruholand_34_131850025034408785.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2517721/Giruholand_34_131850025034408785.zip)
[Giruholand.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2517719/Giruholand.zip)

77e0c8e8

**Comment by mklingen** [comment]
Fixed in master. Problem was task priority for sleeping was erroneously set to "medium". There were also some incorrect usages for determining when a creature was sleepy. Not sure how I broke all that.
