### ISSUE TITLE
AI: Miner sleeping while harvesting

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#968]
[Giruholand_34_131850025034408785.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2517721/Giruholand_34_131850025034408785.zip)
[Giruholand.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2517719/Giruholand.zip)

Find this miner as well:
![image](https://user-images.githubusercontent.com/6562812/47545144-a6dec700-d8b8-11e8-8e4b-1dce5f608268.png)
They are sleeping while harvesting.

77e0c8e

**Comment by mklingen** [comment]
Fixed in master. Problem was task priority for sleeping was erroneously set to "medium". There were also some incorrect usages for determining when a creature was sleepy. Not sure how I broke all that.
