### ISSUE TITLE
Crash: Loading world crashes to desktop

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#969]
Loading any world for an advanced game causes crash.

![image](https://user-images.githubusercontent.com/6562812/47594284-8eb68880-d948-11e8-98c3-cad9ff9123f2.png)

Maybe related to #825 

1. Advanced game
2. Load a previously generated advanced world
3. Observe crash to desktop

[201810261750359333_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2521074/201810261750359333_Crashlog.txt)

77e0c8e8

**Comment by mklingen** [comment]
Fixed. This was caused by a fix I added for disposed graphics device during load time.
