### ISSUE TITLE
New path planning changes have reduced performance.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#970]
![image](https://user-images.githubusercontent.com/6562812/47733236-2e706100-dc3e-11e8-9d2b-df8ccce4cdc2.png)
![image](https://user-images.githubusercontent.com/6562812/47733254-34fed880-dc3e-11e8-8d71-06af7973e3ae.png)

[Borderland_413_131853894854936125.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2530519/Borderland_413_131853894854936125.zip)
[Borderland.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2530522/Borderland.zip)

[DwarfCorp181030_IPSummary.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2530542/DwarfCorp181030_IPSummary.zip)

Performance is measurably worse. It went from spikes of 60% before to a sustained 80% CPU. On 1x with ten dwarves or so, FPS is staying at 0 FPS.

I'm guessing something in our refactor missed something because things were running totally fine until I switched to 64f01d10.

This a repro, as far as I can tell:
1. New game.
2. Set a dig task to the bottom
3. God/hire five more miners (for some reason reaching 10 hires appears to be exactly when perf drops. Not 9. Not 8. If this is actually perf related, I'm guessing it'll take more for you all to repro the bug.)
4. Observe game perf drop to 0 FPS after about a minute or two.

**Comment by mklingen** [comment]
Huh that's too bad, as we saw measurably much better performance from our recent changes. Will take a look.

**Comment by mklingen** [comment]
@Blecki I thought we disabled inverse path planning?

**Comment by com1clyf3** [comment]
Looking deeper into this. It appears it has something to do with auto-mining and a new pathing/auto-dig pattern I'm observing.

So I went and god moded up to ten dwarves all at once at the start of a fresh game. A forgivable second of lag, but then things were fine. They began to dig down and then hit a certain layer, and at this point the perf plummeted. So I went to check out what they might be doing, and it's something I've been seeing in this build.

When ordered to dig down, eventually the dwarves will give up on the planned dig tasks, and instead of giving up will begin to essentially dig out their own little cave. They seem to be wandering a lot to find these individual voxels. Eventually these caves form a direct path back to terrain. My guess is this is probably helping push pathing to its limits, though I'm assuming something we changed in pathing in general is the real issue.

**Comment by mklingen** [comment]
can I get a screenshot?

**Comment by com1clyf3** [comment]
Of the secondary cave they auto-dig? Sure.

**Comment by com1clyf3** [comment]
They've just started this one. Appears they're all trying to get to the surface like before. With blecki's fix, instead of going for it, they now all kind of stand in place after a while.

![image](https://user-images.githubusercontent.com/6562812/47737182-ab9fd400-dc46-11e8-8901-4a3c64ae0e5f.png)

Looks like they keep giving up on their paths.

**Comment by mklingen** [comment]
Looks like planning is taking too long, and the task is getting cancelled before the planner finishes.

**Comment by mklingen** [comment]
I should actually maybe check to see if the old plan is relevant and use it rather than dropping it if it achieves the dwarf's goals.

**Comment by mklingen** [comment]
Changes made to address this: 

* default planner threads reduced from 4 to 2
* fixed bug that prevented dwarfs from climbing
* made dwarfs use old paths when they are relevant.
