### ISSUE TITLE
Art: Trolls walk on water

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#971]
![image](https://user-images.githubusercontent.com/6562812/47800326-748ef880-dd02-11e8-902f-4eb6c3a2a258.png)

Troll envoys aren't submerged in water and have no splash anim.

4865c09a

**Comment by mklingen** [comment]
Same as with the elf, trolls are just too tall. I should make swimming respect creature height. As for the animation, we just didn't bother making swimming animations for most creatures. Only dwarfs have them.

**Comment by mklingen** [comment]
Fixed.
