### ISSUE TITLE
AI: Dwarves can't path to land from water around a corner

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#974]
![image](https://user-images.githubusercontent.com/6562812/47879777-daa97780-ddf7-11e8-9b37-dbdb3225badf.png)

Keeps swimming back and forth. Pathing seems to suggest that they're trying to get to the corner of this balloonport but rather than climb up from here, go to the ladder, or go to the land and then path again, the dwarf just keeps repathing over and over.

[Mokofaia_539_131855796430260036.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2540110/Mokofaia_539_131855796430260036.zip)
[Mokofaia.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2540111/Mokofaia.zip)

4865c09a

**Comment by mklingen** [comment]
I broke the `FindLand` task with a change to path planning. This is now fixed.
