### ISSUE TITLE
Art: Rain frozen in mid-air

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#975]
![image](https://user-images.githubusercontent.com/6562812/47890559-c67c6f00-de25-11e8-9f69-08b625b0c3f1.png)
[Mokofaia_539_131855992661977551.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2540824/Mokofaia_539_131855992661977551.zip)
[Mokofaia.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2540825/Mokofaia.zip)
4865c09a

**Comment by mklingen** [comment]
This is fixed
