### ISSUE TITLE
dwarfcorp	Source file 'AssemblyInfo.cs' could not be found.

### ISSUE THREAD

**Issue by eurabilis** [CompletelyFairGames/dwarfcorp#978]
Hey guys thanks for the update. I am trying to update my version to the latest master branch and I am getting the full error below while compiling. I googled how to fix it, right clicked the project and had VS recreate/add the assembly info file but I still get the error plus errors about duplicates. Is this something I am doing wrong or did you guys misplace a file? Also is there only a 32 bit version for windows? Thanks.

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file 'F:\CODE\dwarfcorp\DwarfCorp\DwarfCorpXNATests\Properties\AssemblyInfo.cs' could not be found.	DwarfCorpXNATests	F:\CODE\dwarfcorp\DwarfCorp\DwarfCorpXNATests\CSC	1	Active

`

**Comment by Blecki** [comment]
Looks like a missing file in the test project. I suggest simply deleting the project from your solution as you do not need it to build the game.

**Comment by eurabilis** [comment]
Ok thank you i dont know how all this works i do this by the skin of my teeth i didnt know i could remove that part without breaking stuff.
