### ISSUE TITLE
Can't build here: intersects with bed

### ISSUE THREAD

**Issue by kirill-stepanoff** [CompletelyFairGames/dwarfcorp#979]
18.11.24, clean install from Steam.
Cannot place bed anywhere, looks like it is because bed is 2-tile object and that counted as self-intersection.

There are other reports of same issue:
https://steamcommunity.com/app/252390/discussions/0/1743352529782148481/

**Comment by PaxJaromeMalues** [comment]
This, so much. Tho I kinda can keep them borderline happy with the stuff I give them to eat, but no beds really tents to kill dwarf mood.

**Comment by kirill-stepanoff** [comment]
Bed can still be placed via cheat menu.

**Comment by mklingen** [comment]
This is fixed.
