### ISSUE TITLE
Animals swimming on the surface of the water stop changing direction as they move.

### ISSUE THREAD

**Issue by Solsund** [CompletelyFairGames/dwarfcorp#98]
I see it mostly with the deer because they are the fastest and widest ranging.  They'll enter the water going left and stay facing left the whole time they change directions, snapping back to the correct orientation the instant they get back onto land.

**Comment by mklingen** [comment]
This is because they have no swimming animations, so they default to Idle. Instead they should default to Idle in the correct direction.

**Comment by mklingen** [comment]
Fixed in my branch.
