### ISSUE TITLE
Save game bloat

### ISSUE THREAD

**Issue by Etarnalazure** [CompletelyFairGames/dwarfcorp#988]
Talked to Blecki, every instance of an animation seems to be saved multiple times (Over 100.000 times, same animation over and over again)

**Comment by Etarnalazure** [comment]
[Dwarfclaimed Island_999_131922380659158922.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2771402/Dwarfclaimed.Island_999_131922380659158922.zip)

**Comment by Etarnalazure** [comment]
[Dwarfclaimed Island.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2771417/Dwarfclaimed.Island.zip)

**Comment by mklingen** [comment]
Thank you, we've tracked down the problem and have a fix in the works.
