### ISSUE TITLE
Build dwarf Builds graves, then deconstructs them to build marble floor

### ISSUE THREAD

**Issue by dyingdemon** [CompletelyFairGames/dwarfcorp#991]
**Build Number:** 19.01.08_XNA (latest public)

**OS:** Windows 10

**Issue:** Graves (that aren't needed) are build upon the purchase of marble from a trade. The Craft Dwarf proceeds to Deconstruct the graves to then build the marble flooring I have queued up.

**Bug Type:** Noncritical / In Game Mechanics

**Does Your Game Crash:** No
[bug.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2785158/bug.zip)

Video Clip taken from my Live stream where I noticed it happening.

**Comment by mklingen** [comment]
oh shit, looks like grave yards are currently used as stockpiles.

**Comment by mklingen** [comment]
can't reproduce. I can definitely see the bug happening in your video, and it would be consistent with stockpiles not using the blacklist correctly. Going to try to work it out a.priori as to how it could have happened.

**Comment by dyingdemon** [comment]
[help Realm_411 Save.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2799446/help.Realm_411.Save.zip)
This is the save file. Sorry for not uploading it with it. Guess that should of been obvious that it was needed.

**Comment by mklingen** [comment]
Okay, how did you get this marble? Was it mined or traded? I think I found the sequence of events which would lead to this, and it would be if you trade with another faction, but you have no space left in your stockpiles. I think in that case they get put in the graveyard.

**Comment by dyingdemon** [comment]
It was traded. I havent found any marble yet on my map. However, My stockpiles and balloon port are no where near full. Even then, Only marble is being Thrown in. no other material

**Comment by mklingen** [comment]
Ok, I think I'm on the right track with trading though. It could be that the order in which the stockpiles are built matters. Thanks for pointing this out.

**Comment by mklingen** [comment]
I've put in a fix which makes it not possible for trade goods to end up in a graveyard. I've also put checks in place to prevent  a dwarf from putting anything other than a corpse in a graveyard.
