### ISSUE TITLE
Promotion prompt

### ISSUE THREAD

**Issue by Thyr0s** [CompletelyFairGames/dwarfcorp#992]
The tip window saying a dwarf wants a promotion only opens after one has been promoted.
Apparently only for the dwarves you start with. New hires work fine.

**Comment by Blecki** [comment]
Found a bug, but the new hires working fine might have been accidental. Looks like the tutorial is only triggered if the announcement is made, and the announcement is only made if it wasn't made at this level before - but both the last level announced and the current level are 0.

**Comment by Blecki** [comment]
Fix is in master.
