### ISSUE TITLE
Backpay bug

### ISSUE THREAD

**Issue by BlazedLucario** [CompletelyFairGames/dwarfcorp#994]
Messing around with new update and when a staff had to collect backpay it took all money and he still refused to work. sounds like a simple fix tho.

**Comment by Blecki** [comment]
I've not been able to replicate this one. Do you remember what tasks were queued up when it happened?

**Comment by BlazedLucario** [comment]
making ale, harvesting crops, and mining. it happened when only a few were paid. same day I sold things and the staff that weren't paid repeated took there daily salary

**Comment by mklingen** [comment]
OK, so a dwarf might still be unhappy even after collecting back pay, and so may still go on strike. So this is working as intended, but it might be unbalanced.

**Comment by Blecki** [comment]
I've seen a couple similar issues on steam. Seems there's more to it than the strike - dwarves are continually collecting back pay without actually catching up.

**Comment by Blecki** [comment]
Ah I squashed it. The Dwarf's counter for days without pay wasn't being reset.
