### ISSUE TITLE
Save: exception when trying to save

### ISSUE THREAD

**Issue by spirritus** [CompletelyFairGames/dwarfcorp#997]
Saves throws an excpetion when a hired dwarf has not yet arrived (at least i guess that is the issue, it worked whenthe dwarf arrived)

**Comment by Blecki** [comment]
Looks like a debug exception that got left in.

![image](https://user-images.githubusercontent.com/1297068/52186035-ed668a80-27f2-11e9-8feb-d2b031a76178.png)

**Comment by Blecki** [comment]
Okay, despite the fix appearing simple, the save system is more broken with it. This will take a bit to unravel.

**Comment by Blecki** [comment]
Testing shows it appears to work, but I am not confident this bug won't rear it's head again.
