### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Etarnalazure** [CompletelyFairGames/dwarfcorp#998]
Seems the game goes crazy if dwarves try to restock the stock as things get taken out.

Stock was full as craft dwarf started to build with dirt, other dwarves tried to empty their inventory into the stock faster than things got taken out, game quickly slowed down to a crawl and eventually wouldnt respond. (At this point the game had gone from 200k megabytes of Ram to 1gb Ram within seconds.

Also, you cant sell to traders when you have your stock full. Tried to unload some dirt onto Elvish traders for money, kept saying I didnt have any room (I only had like 100 coins, so there was plenty of room for the money).

Should be able to reproduce with this save, happens within seconds of load.
[Futuristicland_342_Autosave.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2830575/Futuristicland_342_Autosave.zip)
World settings
[Futuristicland.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2830576/Futuristicland.zip)

Edit:
This happened on the newest branch. (Literally updated a few minutes ago to help out testing.)

**Comment by Etarnalazure** [comment]
Yeah, has to do with dwarves adding to the stockpile even though its full. I assume it has to do with dwarves trying to add 2 items for every 1 item being removed.

This is the code its stuck on:
var resource = i.Resource;
                    if (toReturn.ContainsKey(resource))
                    {
                        toReturn[resource].Second.NumResources += 1;
                    }
                    else
                    {
                        toReturn[resource] = new Pair<ResourceAmount>(new ResourceAmount(resource, 0), new ResourceAmount(resource));
                    }

---------------------------------------
Class: Factions.cs
Line: 591

**Comment by Blecki** [comment]
Confirmed fixed in master.
